(function(z){
var qR=function(){z.Q.call(this)};var rR=function(){sR();tR();(0,window.$)(".qrcode-app-download .app-link").on({mouseenter:function(){z.wi({category:"app",action:"hover_download_app",label:"home_download_app"})},click:function(){z.wi({oc:!0,category:"app",action:"visit_app",label:"home_download_app"})}})};var sR=function(){var a=(0,window.$)(".sign-flow");if(a.length){var b=new uR;b.w(a[0]);b.g("trackRequested",function(a){a.preventDefault();a.label="home_default";z.wi(a)})}};
var tR=function(){function a(){var a=window.particlesJS;a&&((0,window.$)("\x3cdiv\x3e",{id:"particles"}).appendTo("body"),a("particles",c))}var b=!!window.HTMLCanvasElement,c={particles:{number:{value:20,density:{enable:!0,value_area:1E3}},color:{value:"#e1e1e1"},shape:{type:"circle",stroke:{width:0,color:"#000000"},polygon:{nb_sides:5},image:{src:"img/github.svg",width:100,height:100}},opacity:{value:.5,random:!1,anim:{enable:!1,speed:1,opacity_min:.1,sync:!1}},size:{value:15,random:!0,anim:{enable:!1,
speed:180,size_min:.1,sync:!1}},line_linked:{enable:!0,distance:650,color:"#cfcfcf",opacity:.26,width:1},move:{enable:!0,speed:2,direction:"none",random:!0,straight:!1,out_mode:"out",bounce:!1,attract:{enable:!1,rotateX:600,rotateY:1200}}},interactivity:{detect_on:"canvas",events:{onhover:{enable:!1,mode:"repulse"},onclick:{enable:!1,mode:"push"},resize:!0},modes:{grab:{distance:400,line_linked:{opacity:1}},bubble:{distance:400,size:40,duration:2,opacity:8,speed:3},repulse:{distance:200,duration:.4},
push:{particles_nb:4},remove:{particles_nb:2}}},retina_detect:!0};(0,window.$)(function(){b&&window.$.ajax({url:"/static/revved/components/particles.js/particles.min.00debcf6.js",dataType:"script",cache:!0}).then(a)})};var uR=function(){z.Q.call(this)};var vR=function(a){return!/^\+?[0-9]+$/.test(a)};var wR=function(a,b){a.account&&(a[b]=a.account,delete a.account)};
var xR=function(a){var b=(0,window.$)(".index-tab-navs a",a.m()),c=(0,z.q)(function(){var a=window.location.hash||"#"+("signin"===window.location.pathname.slice(1)?"signin":"signup"),c=b.filter(function(){return(0,window.$)(this).attr("href")===a});c.addClass("active").siblings().removeClass("active");c.parent().attr("data-active-index",c.index());"#signin"===a?yR(this):"#signup"===a&&zR(this)},a);a.o().g(window,"hashchange",c);c()};
var AR=function(a){a.Ym=(0,window.$)(".view-signin",a.m());var b=(0,window.$)("form",a.Ym),c=(0,window.$)("button.submit",b);b.validate(window.$.extend({},z.Vm,{submitHandler:z.pk(c,window.$.proxy(a.Uz,a))}));var d=(0,window.$)('input[name\x3d"account"]',b);(0,window.$)(".unable-login",a.Ym).click(function(){(new z.yk(d.val())).show()});b=(0,window.$)(".captcha-module",b).get(0);a.vz=new z.Yj("login");a.vz.w(b);z.Zj(a.vz)};
var BR=function(a){a.yg=(0,window.$)(".view-signup",a.m());var b=(0,window.$)("form",a.yg);a.th=!(0,window.$)('input[name\x3d"phone_num"]',b).length;var c=(0,window.$)("button.submit",b);b.validate(window.$.extend({},z.Vm,{submitHandler:z.pk(c,window.$.proxy(a.jp,a))}));var d=(0,window.$)('input[name\x3d"account"]',b);a.yg.on("click",".switch-to-login",function(){yR(a);var b=d.val();b&&(0,window.$)('input[name\x3d"account"]',a.mW).val(b)});c=(0,window.$)(".captcha-module",b).get(0);a.hu=new z.Yj;
a.hu.w(c);z.Zj(a.hu);a.Sm=new z.Kk(b);a.Sm.start()};var yR=function(a){a.Ym.is(":visible")||(a.yg.hide(),a.Ym.show(),a.rl())};var zR=function(a){a.yg.is(":visible")||(a.Ym.hide(),a.yg.show(),a.rl())};var CR=function(){var a=z.Vi.get("accountcallback");z.Vi.remove("accountcallback");if(a){a=(0,window.decodeURIComponent)(a);try{var b=JSON.parse(a);z.X.dispatchEvent(new z.Tj("accountcallback",b))}catch(c){}}};z.v(qR,z.Q);qR.prototype.init=function(){this.w(window.document.body)};
qR.prototype.C=function(a){qR.v.C.call(this,a);rR();z.wi({category:"view_home",action:"visit_home"})};z.v(uR,z.Q);z.e=uR.prototype;z.e.C=function(){uR.v.C.call(this);this.Ly()};z.e.ia=function(a){this.dispatchEvent(window.$.extend({type:"trackRequested"},a))};
z.e.Ly=function(){function a(a,b){(0,window.$)(":submit",a).click(function(){b(a)});(0,window.$)("keydown",a).click(function(c){13===c.keyCode&&b(a)})}AR(this);BR(this);this.xo();CR();this.rl();xR(this);var b=this,c=this.m();(0,window.$)(".view-signin .js-signup",c).click(function(){zR(b)});(0,window.$)(".view-signup .js-signin",c).click(function(){yR(b)});a((0,window.$)(".view-signin form",c),function(a){a=a.ke().account;var c=vR(a);b.ia({category:"sign_in",action:a?"click_sign_in_submit_"+(c?"email":
"phone"):"click_sign_in_submit_no_channel"})});a((0,window.$)(".view-signup form",c),function(a){a=a.ke();a=a.phone_num||a.account;var c=b.th?vR(a):!1;b.ia({category:"sign_up",action:a?b.th?"click_sign_up_submit_"+(c?"email":"phone"):"click_sign_up_submit_phone":"click_sign_up_submit_no_channel"})});(0,window.$)(".js-bindweibo",c).click(function(){b.ia({category:"sign_in_or_sign_up",action:"click_sign_with_weibo_start"});z.Uj("sina",b)});(0,window.$)(".js-bindqq",c).click(function(){b.ia({category:"sign_in_or_sign_up",
action:"click_sign_with_qq_start"});z.Uj("qq",b)});(0,window.$)(".js-bindwechat",c).click(function(){b.ia({category:"sign_in_or_sign_up",action:"click_sign_with_wechat_start"});z.Uj("wechat",b)});(0,window.$)(".js-toggle-sns-buttons").click(function(){var a=(0,window.$)(".sns-buttons");a.hasClass("is-visible")?a.onTransitionEnd(function(){a.css("visibility","hidden")},250).removeClass("is-visible"):a.css("visibility","visible").addClass("is-visible")})};
z.e.Uz=function(a){var b=this,c=(0,window.$)(a);a=c.ke();var d=vR(a.account);b.ia({category:"sign_in",action:"sign_in_front_end_pass_"+(d?"email":"phone")});var f=d?"/login/email":"/login/phone_num";d?wR(a,"email"):wR(a,"phone_num");return window.$.post(f,a,function(a){a&&a.r?(z.Zj(b.vz),c.data("validator").showErrors(a.data)):(b.ia({oc:!0,category:"sign_in",action:"sign_in_success_"+(d?"email":"phone")}),b.je())})};
z.e.jp=function(a){var b=this;a=(0,window.$)(a);var c=a.ke(),d=b.th?vR(c.account):!1;b.ia({oc:!0,category:"sign_up",action:"sign_up_front_end_pass_"+(d?"email":"phone")});var f=d?"/register/email":"/register/phone_num/validation";d?wR(c,"email"):wR(c,"phone_num");var g=this.Sm.stop();c.userInfo=JSON.stringify(g);var h=a.data("validator");return d?window.$.post(f,c,function(a){a&&a.r?(z.Zj(b.hu),h.showErrors(a.data)):(b.ia({oc:!0,category:"sign_up",action:"sign_up_success_email"}),b.je({from:"register"}))}):
window.$.post(f,c,function(a){a.r?(z.Zj(b.hu),b.th||wR(a.data,"phone_num"),h.showErrors(a.data)):(a=new z.Rv(c),a.Ob(b),a.G(!0))})};z.e.rl=function(){if(!z.sk){var a=this.m();(0,window.setTimeout)(function(){(0,window.$)("input[placeholder]:visible",a).placeholder()},10)}};z.e.xo=function(){z.Xj(this.o(),this.ER)};
z.e.ER=function(a){a=a.zf;var b={qqconn:"qq",wechat:"wechat",sina:"weibo"}[a.type];1===a.login?(this.ia({oc:!0,category:"sign_in",action:"sign_in_success_"+b}),this.je()):(a=new z.Ck(a),a.Ob(this),a.show())};z.e.je=function(a){a=void 0===a?{}:a;var b=(new z.oh(window.location.href)).Jd().get("next");b?window.location.href=b:"register"===a.from?z.nk():window.location.reload()};z.Fa("ZH.entrySignPage",function(){(new qR).init()});z.kg("page-index");}).call(this, __z_z__);
//# sourceURL=/static/revved/-/js/closure/page-index.8bdcf6d9.js