(function(z){
var zI=function(a,b){return a.ca.m(b?a.BJ:a.PE)};var AI=function(a){if(z.A&&!(9<=z.Ug)){var b=!1;try{b=a.parentNode}catch(c){}return!!b}return z.mf(a.ownerDocument.body,a)};var BI=function(a){z.yc.call(this);this.BJ=z.pq();this.PE=z.pq();this.GA=a.Yg();this.ca=z.H(a.wa());a.uh(this.ca.B("SPAN",{id:this.BJ}),this.ca.B("SPAN",{id:this.PE}))};var CI=function(a,b){var c=b.nd();a.Sb[c]=b;for(var d in z.cz)b[z.cz[d]]&&a.Ij[d].push(b);b.F=a;a.xc()&&b.enable(a)};
var DI=function(a){return a.F&&z.Hc?(a=a.F.gb.Va(),a.scrollTo.bind(a,a.scrollX,a.scrollY)):function(){}};var EI=function(a){return a.F&&a.F.gb};var FI=function(a){var b=a.node.parentNode;return new z.Ju(b,z.mb(b.childNodes,a.node))};var GI=function(a,b,c,d){return z.bu(a,b,c,d)};var HI=function(a){return a.Y()&&a.la()?new BI(a):null};
var II=function(a){var b;if(3==a.node.nodeType)for(b=a.node.previousSibling;b&&3==b.nodeType;b=b.previousSibling)a.offset+=z.Du(b);else b=a.node.previousSibling;var c=a.node.parentNode;a.node=b?b.nextSibling:c.firstChild;return a};var JI=function(a,b){return b?z.Iu(a.Y(),a.xa()):z.Iu(a.la(),a.La())};var KI=function(a){for(var b=null,c=a.firstChild;c;){var d=c.nextSibling;3==c.nodeType?""==c.nodeValue?a.removeChild(c):b?(b.nodeValue+=c.nodeValue,a.removeChild(c)):b=c:(KI(c),b=null);c=d}};
var LI=function(a){var b=a&&a.nodeName;return!(!a||"block"!=(1!=a.nodeType?null:z.A?z.xg(a,"display"):z.wg(a,"display"))&&"TD"!=b&&"TABLE"!=b&&"LI"!=b)};
var MI=function(a){var b=a.Yg(),c=II(JI(a,!b)),d=FI(c),f=c.node.previousSibling;3==c.node.nodeType&&(c.node=null);var g=II(JI(a,b)),h=FI(g),k=g.node.previousSibling;3==g.node.nodeType&&(g.node=null);return function(){!c.node&&f&&(c.node=f.nextSibling,c.node||(c=new z.Ju(f,z.Du(f))));!g.node&&k&&(g.node=k.nextSibling,g.node||(g=new z.Ju(k,z.Du(k))));return z.bu(c.node||d.node.firstChild||d.node,c.offset,g.node||h.node.firstChild||h.node,g.offset)}};var NI=function(a){return z.vf(a,LI,!0)};
var OI=function(a,b){if(b)var c=MI(b),d=NI(b.Qb());d?(d=z.Sp(d,a),z.A?KI(d):d.normalize()):a&&(z.A?KI(a):a.normalize());return c?c():null};var PI=function(a,b,c){z.Vr.call(this,b,a||z.OC.aa(),c)};var QI=function(a){return a.getAttribute&&"true"==a.getAttribute("g_editable")};var RI=function(a){BI.call(this,a)};
var SI=function(a,b,c){for(var d=(b=1==b)?a.Y():a.la(),f=b?a.xa():a.La(),g=a.Qb();d!=g&&d!=c&&!(b&&0!=f||!b&&f!=z.Du(d));)var h=d.parentNode,d=z.mb(h.childNodes,d),f=b?d:d+1,d=h;return GI(b?d:a.Y(),b?f:a.xa(),b?a.la():d,b?a.La():f)};
var TI=function(a){z.Ip(a,!1);if(z.hG){var b=a;for(a=a.parentNode;a&&"HTML"!=a.tagName;){if(z.am?"none"==a.style[z.am].toLowerCase():(z.A||z.vg)&&"on"==a.getAttribute("unselectable")){z.Ip(a,!1,!0);for(var c=0,d=a.childNodes.length;c<d;c++){var f=a.childNodes[c];f!=b&&1==f.nodeType&&z.Ip(a.childNodes[c],!0)}}b=a;a=a.parentNode}}};var UI=function(a){var b=a.target.tagName;"TEXTAREA"!=b&&"INPUT"!=b&&a.preventDefault()};
var VI=function(a){var b=z.Od(a);a=new z.Nd;var c=null;a.next=function(){for(;;){if(null==c){var a=b.next();c=z.Od(a)}try{return c.next()}catch(f){if(f!==z.Pd)throw f;c=null}}};return a};var WI=function(a){var b=a.Qb();return a.Y()!=b.parentElement&&QI(b)||!!z.vf(b,QI)};var XI=function(a,b){var c=SI(a,1,b),c=SI(c,0,b),d=c.Y(),f=c.la(),g=c.xa(),c=c.La();if(d==f){for(;f!=b&&0==g&&c==z.Du(f);)d=f.parentNode,g=z.mb(d.childNodes,f),c=g+1,f=d;d=f}return z.bu(d,g,f,c)};
var YI=function(a,b){z.hG&&b.g(a,"mousedown",UI,!0);z.Ip(a,!0);for(var c=a.getElementsByTagName("INPUT"),d=0,f=c.length;d<f;d++){var g=c[d];g.type in ZI&&TI(g)}z.w(a.getElementsByTagName("TEXTAREA"),TI)};var $I=function(a,b,c){for(var d;a!=c&&(d=a.parentNode);){for(var f=d.cloneNode(!1);a.nextSibling;)f.appendChild(a.nextSibling);b&&f.insertBefore(b,f.firstChild);b=f;a=d}return b};var aJ=function(a){return!!bJ[a.tagName]};var cJ=function(a){return z.zu(z.eq(new z.wu(a),z.Au))};
var dJ=function(a){return(a=String(a).toLowerCase())?z.qb([".jpg",".jpeg",".png"],function(b){return z.Yo(a,b)}):!1};var eJ=function(a,b){var c=z.Od(a),d=new z.Nd;d.next=function(){var a=c.next();if(b.call(void 0,a,void 0,c))return a;throw z.Pd;};return d};var fJ=function(a,b){var c=z.Od(a),d=new z.Nd,f=!0;d.next=function(){for(;;){var a=c.next();if(!f||!b.call(void 0,a,void 0,c))return f=!1,a}};return d};var gJ=function(a){return VI(arguments)};
var hJ=function(a,b){a=z.Od(a);try{for(;;)if(b.call(void 0,a.next(),void 0,a))return!0}catch(c){if(c!==z.Pd)throw c;}return!1};var iJ=function(a){z.F.call(this);this.ld=a};var jJ=function(a){this.ol=a;this.Oi=new z.vj("",!0,this.ol.ld);this.xn=new z.Ij(this.ol.ld);this.wn={};this.Ih("tr-dialog")};var kJ=function(a,b){var c=z.u("OK");a.xn.set("ok",b||c,!0);a.wn.ok=(0,z.q)(a.ol.rP,a.ol)};var lJ=function(a,b){var c=z.Im,d=z.u("Cancel");a.xn.set(c,b||d,!1,!0);a.wn[c]=(0,z.q)(a.ol.lo,a.ol);return a};
var mJ=function(a){a.xn.Xg()&&(kJ(a),lJ(a));z.Fj(a.Oi,a.xn);var b=a.wn;a.wn=null;a.Oi.g(z.Hj,function(a){if(b[a.key])return b[a.key](a)});a.Oi.Kp(!0);var c=a.Oi;a.Oi=null;return c};var nJ=function(a){z.Xy.call(this);this.bN=a;this.YI=function(){}};var oJ=function(a){var b=a.F,c=a.gJ;c&&c.restore();b.focus();a.gJ=null};var pJ=function(a){a.Ia&&!a.Vy&&(a.Vy=!0,a.Ia.H(),a.Ia=null,a.Vy=!1)};var qJ=function(a){this.te=a;this.rx=[]};
var rJ=function(a){if(!a.Pw){var b=z.yu(a.te);a.Pw=b.tagName&&"IMG"==b.tagName?b.getAttribute("alt"):z.Qp(a.te)}return a.Pw};var sJ=function(a,b,c,d){var f=new qJ(a);f.te.href=b;c&&(a.target=c);d&&(f.rx=d);return f};var tJ=function(a,b){var c=new qJ(a),d;d=(0,z.bb)(rJ(c));d=uJ(d)?0>d.search(/:/)?"http://"+z.sq(d):d:vJ.test(d)?"mailto:"+d:null;c.te.href=d?d:"";b&&(a.target=b)};
var uJ=function(a){if(/\s/.test(a)||vJ.test(a))return!1;var b=!1;/^[^:\/?#.]+:/.test(a)||(a="http://"+a,b=!0);a=a.match(z.se);if(-1!=z.mb(["mailto","aim"],a[1]))return!0;var c=a[3];if(!c||b&&-1==c.indexOf(".")||/[^\w\d\-\u0100-\uffff.%]/.test(c))return!1;b=a[5];return!b||0==b.indexOf("/")};var wJ=function(){z.Xy.call(this)};var xJ=function(a){return EI(a).wa()};
var yJ=function(a){if(z.A||z.vg){var b=a.Ae(),c=b.Qb(),d=xJ(a);zJ.lastIndex=0;zJ.test(c.innerHTML)&&(a=HI(b),"P"==c.tagName?AJ(c,!0):(b=c.innerHTML.replace(zJ,'\x3cp$1 trtempbr\x3d"temp_br"\x3e'),z.Eu(c,b),c=z.wb(c.getElementsByTagName("P")),z.Qd(c,function(a){"temp_br"==a.getAttribute("trtempbr")&&(a.removeAttribute("trtempbr"),z.vq(z.pf(a))&&a.appendChild(z.A?d.createTextNode(" "):d.createElement("BR")),AJ(a))})),a.restore())}};
var AJ=function(a,b){if(z.A||z.vg){var c=a.outerHTML.replace(/<(\/?)p/gi,"\x3c$1div");b&&(c=c.replace(zJ,"\x3c/div\x3e\x3cdiv$1\x3e"));z.vg&&!/<\/div>$/i.test(c)&&(c+="\x3c/div\x3e");a.outerHTML=c}};var BJ=function(a){return 0==a.indexOf("+")?a.substring(1):a};var CJ=function(a){a=NI(a);a.align&&(a.style.textAlign=a.align,a.removeAttribute("align"))};
var DJ=function(a,b,c,d,f){var g=null;d&&(g=a.F.queryCommandValue("rtl")?"rtl":a.F.queryCommandValue("ltr")?"ltr":null);b=BJ(b);var h,k;if(z.A){var m=b;k=[];d=null;var n=a.Ae();h=EI(a);if(m in EJ){var t=n&&n.Qb();if(t){for(var C=z.Me(window.document,"BLOCKQUOTE",null,t),J,K=0;K<C.length;K++)if(n.containsNode(C[K])){J=C[K];break}if(t=J||z.uf(t,"BLOCKQUOTE"))d=h.B("DIV",{style:"height:0"}),t.appendChild(d),k.push(d),J?n=z.bu(J,0,d,0):n.containsNode(d)&&(n=GI(n.Y(),n.xa(),d,0)),n.select()}}J=a.F;!J.qc()&&
!d&&m in FJ&&(J=J.m(),n&&n.isCollapsed()&&!z.hf(J)&&(d=n.Be(0).de(),n=d.duplicate(),n.moveToElementText(J),n.collapse(!1),n.isEqual(d)&&(n=h.createTextNode(" "),J.appendChild(n),d.move("character",1),d.move("character",-1),d.select(),k.push(n))),d=h.B("DIV",{style:"height:0"}),J.appendChild(d),k.push(d));h=k[0];k=k[1]}if(z.B){h=b;var O;GJ[h]&&(O=EI(a).B("DIV",{style:"height: 0"},"x"),a.F.m().appendChild(O));!z.D(534)&&HJ[h]&&(h=a.F.m(),O=EI(a).B("DIV",{style:"height: 0"},"x"),h.insertBefore(O,h.firstChild));
h=O}z.y&&(O=b,z.D("1.9")&&"formatblock"==O.toLowerCase()&&(O=a.Ae(),J=O.Y(),O.isCollapsed()&&J&&"BODY"==J.tagName&&(d=O.xa(),(J=J.childNodes[d])&&"BR"==J.tagName&&(O=O.de(),O.setStart(J,0),O.setEnd(J,0)))));z.vG&&"fontsize"==b.toLowerCase()&&IJ(a);O=xJ(a);f&&z.lG&&(O.execCommand("styleWithCSS",!1,!0),z.vg&&JJ(a));O.execCommand(b,!1,c);f&&z.lG&&O.execCommand("styleWithCSS",!1,!1);z.B&&!z.D("526")&&"formatblock"==b.toLowerCase()&&c&&/^[<]?h\d[>]?$/i.test(c)&&KJ(a);/insert(un)?orderedlist/i.test(b)&&
(z.B&&!z.D(534)&&LJ(a),z.A&&(MJ(a),k&&z.N(k)));h&&z.N(h);g&&a.F.execCommand(g)};
var NJ=function(a,b,c,d){var f=null,g=[],h=b&&b.Qb();if(h&&"IMG"==h.tagName||!b)return null;if(b.isCollapsed())b=b.Be(0).de(),z.eG?(f=EI(a).createElement("A"),b.insertNode(f)):z.dG&&(b.pasteHTML("\x3ca id\x3d'newLink'\x3e\x3c/a\x3e"),f=EI(a).m("newLink"),f.removeAttribute("id"));else{var k=z.pq();DJ(a,"CreateLink",k);z.w(a.F.m().getElementsByTagName("A"),function(a){z.Yo(a.href,k)&&g.push(a)});g.length&&(f=g.pop());a=function(a){return uJ(z.Qp(a))};if(g.length&&z.uo(g,a)){for(a=0;b=g[a];a++)tJ(b,
d);g=null}}return sJ(f,c,d,g)};var IJ=function(a){var b=XI(z.xz(a.F),a.F.m());z.Qd(z.eq(b,function(a,d,f){return 1==f.Vb&&b.containsNode(a)}),function(a){z.sg(a,"font-size","");z.y&&0==a.style.length&&null!=a.getAttribute("style")&&a.removeAttribute("style")})};var KJ=function(a){z.Qd(a.Ae(),function(a){"Apple-style-span"==a.className&&(a.style.fontSize="",a.style.fontWeight="")})};
var LJ=function(a){var b=!1;z.Qd(a.Ae(),function(a){var d=a.tagName;if("UL"==d||"OL"==d)if(b){if(d=z.Up(a)){var f=a.ownerDocument.createRange();f.setStartAfter(d);f.setEndBefore(a);if(z.Xo(f.toString())&&d.nodeName==a.nodeName){for(;d.lastChild;)a.insertBefore(d.lastChild,a.firstChild);d.parentNode.removeChild(d)}}}else b=!0})};
var MJ=function(a){for(a=(a=a.Ae())&&a.vc();a&&"UL"!=a.tagName&&"OL"!=a.tagName;)a=a.parentNode;a&&(a=a.parentNode);if(a){var b=z.wb(a.getElementsByTagName("UL"));z.xb(b,z.wb(a.getElementsByTagName("OL")));z.w(b,function(a){var b=a.type;b&&!("UL"==a.tagName?OJ:PJ)[b]&&(a.type="")})}};var JJ=function(a){var b=[],c=z.xz(a.F).Qb();do b.push(c);while(c=c.parentNode);a=gJ(z.Od(z.xz(a.F)),z.Od(b));a=z.eq(a,LI);z.Qd(a,function(a){var b=a.style.outline;a.style.outline="0px solid red";a.style.outline=b})};
var QJ=function(a){var b=null;z.Qd(a,function(a,d,f){if(-1!=f.Vb){a=NI(a).tagName;b=b||a;if(b!=a)throw b=null,z.Pd;f.Sp()}});return b};var RJ=function(a,b){var c=b.replace("+justify","").toLowerCase();"full"==c&&(c="justify");var d=a.F.Sb.Bidi;if(d)return c==d.GX();var f=a.Ae();if(!f)return!1;for(var g=f.Qb(),d=z.nb(g.childNodes,function(a){return z.Au(a)&&f.containsNode(a,!0)}),d=d.length?d:[g],g=0;g<d.length;g++){var h=NI(d[g]);if(c!=SJ(h))return!1}return!0};
var SJ=function(a){var b=z.yg(a,"textAlign"),b=b.replace(/^-(moz|webkit)-/,"");TJ[b]||(b=a.align||"left");return b};var UJ=function(a,b,c,d,f){d=BJ(d);if(f){var g=xJ(a);g.execCommand("styleWithCSS",!1,!0)}a=b?c.queryCommandState(d):c.queryCommandValue(d);f&&g.execCommand("styleWithCSS",!1,!1);return a};
var VJ=function(a,b){z.yc.call(this);this.Gt=[];for(this.Bt=[];a&&"BODY"!=a.nodeName&&a!=b;){for(var c=0,d=a.previousSibling;d;)d=d.previousSibling,++c;this.Gt.unshift(c);this.Bt.unshift(a.nodeName);a=a.parentNode}};var WJ=function(a,b){for(var c,d=b,f=0;c=a.Bt[f];++f)if(d=d.childNodes[a.Gt[f]],!d||d.nodeName!=c)return null;return d};var XJ=function(){z.Xy.call(this)};
var YJ=function(a,b){for(var c=z.xz(a.F),d=c.vc(),f=a.F.m(),g;d&&d!=f;){var h=d.nodeName,k;(k="DIV"==h)||!(k=ZJ[h])||(k=!b)||(k=d,k=!(z.Bu(k)&&1==k.getElementsByTagName("BR").length));if(k){if(z.vg&&g){"DIV"==h&&g==d.lastChild&&z.Bu(g)&&(z.cf(g,d),z.tu(g).select());break}return}z.vg&&b&&"P"==h&&"DIV"!=h&&(g=d);d=d.parentNode}if(z.A&&!z.D(9)){var m=!1,c=c.de(),d=c.duplicate();d.moveEnd("character",1);d.text.length&&(m=d.parentElement(),d=d.duplicate(),d.collapse(!1),d=d.parentElement(),m=m!=d&&d!=
c.parentElement())&&(c.move("character",-1),c.select())}a.F.gb.wa().execCommand("FormatBlock",!1,"\x3cDIV\x3e");m&&(c.move("character",1),c.select())};
var $J=function(a){if(z.eG){if((a=z.xz(a.F))&&!a.isCollapsed()){var b=!0;if(z.vg){var c=a.Y(),d=a.xa();c==a.la()&&c.lastChild&&"BR"==c.lastChild.tagName&&d==c.childNodes.length-1&&(b=!1)}if(b){var f=a;if(f&&!f.isCollapsed()){var g=!0,b=f.Qb(),c=new VJ(f.Y(),b),d=f.xa(),h;h=f;var k=h.Y();LI(k)&&(k=k.childNodes[h.xa()]||k);var k=NI(k),m=h.la();LI(m)&&(m=m.childNodes[h.La()]||m);m=NI(m);h=k==m;if(k=!h)a:{var m=f,k=m.la(),m=m.La(),n=k;if(LI(n)){var t=n.childNodes[m];if(!t||1==t.nodeType&&LI(t)){k=!1;
break a}}for(t=NI(n);t!=n;){if(cJ(n)){k=!0;break a}n=n.parentNode}k=m!=z.Du(k)}f.bd();(f=WJ(c,b))?f=z.uu(f,d):(f=z.uu(b,b.childNodes.length),g=!1);f.select();h&&(h=NI(f.Y()),z.Bu(h,!0)&&(g="\x26nbsp;",z.vg&&"LI"==h.tagName&&(g="\x3cbr\x3e"),z.Eu(h,g),z.Gu(h.firstChild),g=!1));k&&(f=NI(f.Y()),h=cJ(f),f&&h&&(z.$e(f,h.childNodes),z.N(h)));g&&(f=z.uu(WJ(c,b),d),f.select())}}}a=JI(a,!0)}else a=EI(a).wa(),b=a.selection.createRange(),c=z.pq(),b.pasteHTML('\x3cspan id\x3d"'+c+'"\x3e\x3c/span\x3e'),a=a.getElementById(c),
a.id="";return a};var aK=function(){};var bK=function(a){z.F.call(this);this.av=a||window;this.qz=z.E(this.av,"resize",this.my,!1,this);this.yc=z.Pe(this.av)};
var cK=function(a,b){z.F.call(this);this.ca=z.H(a);this.S=new z.zd(this);this.dC=new bK(this.ca.Va());this.td={};this.Dd=this.ca.B("DIV",{className:dK});z.P(this.Dd,!1);a.appendChild(this.Dd);z.sg(this.Dd,"zIndex",b);this.tn=this.Dd;this.MD=this.ca.B("DIV",{className:"tr_bubble_closebox",innerHTML:"\x26nbsp;"});this.tn.appendChild(this.MD);YI(this.Dd,this.S);this.lg=new z.Tn(this.Dd)};var eK=function(a,b){return z.Gb(a.td,function(a){return a.type==b})};
var fK=function(a,b,c,d){var f=null,g;for(g in a.td){var h=a.td[g].wB;if(!f||z.mf(h,f))f=a.td[g].wB}return z.Es(f,b,a.Dd,c,null,gK,d,null,a.qO())};var hK=function(a,b,c,d,f,g){this.type=c;this.wB=f;this.AT=g;this.element=a.B("DIV",{className:"tr_bubble_panel",id:b},a.B("DIV",{className:"tr_bubble_panel_title"},d?d+":":""),a.B("DIV",{className:"tr_bubble_panel_content"}))};var iK=function(){z.Xy.call(this);this.ic=new z.zd(this);this.IM=null};var jK=function(a,b){return new cK(a,b)};
var kK=function(a){var b=a.tX||a.F.Uk.document.body;a.ca=z.H(b);var c=lK[a.F.id];c||(c=(a.IM||jK).call(null,b,a.F.BM||0),lK[a.F.id]=c);return c};var mK=function(a){if(a.si){var b=kK(a),c=a.si;z.N(b.td[c].element);delete b.td[c];c=z.to(b.td);1>=c&&z.dj(b.Dd,"tr_multi_bubble");0==c?b.ND():b.ha();a.KF()}};var nK=function(a){return a?z.Zp("//www.zhihu.com/equation","tex",a):""};var oK=function(){iK.call(this)};var pK=function(a){this.UN=a};var qK=function(a){z.Mc.call(this,"change");this.isValid=a};
var rK=function(a){z.Q.call(this,a)};var sK=function(a,b,c,d,f,g,h,k){this.dc=b;this.cn=h||[];b=k||tK.aa();k=[];c=-c;d=-d;for(var m=0;m<h.length;m++)k.push(a.L().B("DIV",{"class":b.T()+"-item",style:"width:"+f+"px;height:"+g+"px;background-position:"+c+"px "+d+"px;"})),c-=f;this.jg=a;z.HC.call(this,k,b,a.L())};var uK=function(a,b,c){z.Mc.call(this,a,c);this.mT=b};var tK=function(){};var vK=function(a,b,c){z.Q.call(this,c);this.Dj=b;this.jg=a.lT};
var wK=function(a){var b=a.El();if(b!=a.VG){a.VG=b;var c=!(1024<b.length);a.dispatchEvent(new qK(c));a=a.FT;var d=z.H(a);d.vp(a);b&&(c?(b=nK(b),b=d.B("IMG",{src:b})):(b=z.u("Equation is too long"),b=d.B("DIV",{"class":"ee-warning"},b)),d.appendChild(a,b))}};var xK=function(a,b,c){z.Q.call(this,c);this.YD=a;this.Dj=b};var yK=function(a,b,c,d){iJ.call(this,b);this.nj=new xK(a,d,b);this.nj.render();this.nj.UA(c);this.nj.addEventListener("+equation",this.Rz,!1,this)};
var zK=function(a){sK.call(this,a,"a",0,150,18,18,"\\leftarrow \\rightarrow \\leftrightarrow \\Leftarrow \\Rightarrow \\Leftrightarrow \\uparrow \\downarrow \\updownarrow \\Uparrow \\Downarrow \\Updownarrow".split(" "));z.JC(this,new z.Ie(12,1))};var AK=function(a){sK.call(this,a,"c",0,70,18,18,"\\leq \\geq \\prec \\succ \\preceq \\succeq \\ll \\gg \\equiv \\sim \\simeq \\asymp \\approx \\ne \\subset \\supset \\subseteq \\supseteq \\in \\ni \\notin".split(" "));z.JC(this,new z.Ie(7,3))};
var BK=function(a){sK.call(this,a,"g",0,30,18,18,"\\alpha \\beta \\gamma \\delta \\epsilon \\varepsilon \\zeta \\eta \\theta \\vartheta \\iota \\kappa \\lambda \\mu \\nu \\xi \\pi \\varpi \\rho \\varrho \\sigma \\varsigma \\tau \\upsilon \\phi \\varphi \\chi \\psi \\omega \\Gamma \\Delta \\Theta \\Lambda \\Xi \\Pi \\Sigma \\Upsilon \\Phi \\Psi \\Omega".split(" "));z.JC(this,new z.Ie(7,6))};
var CK=function(a){sK.call(this,a,"m",0,90,30,56,"x_{a};x^{b};x_{a}^{b};\\bar{x};\\tilde{x};\\frac{a}{b};\\sqrt{x};\\sqrt[n]{x};\\bigcap_{a}^{b};\\bigcup_{a}^{b};\\prod_{a}^{b};\\coprod_{a}^{b};\\left( x \\right);\\left[ x \\right];\\left\\{ x \\right\\};\\left| x \\right|;\\int_{a}^{b};\\oint_{a}^{b};\\sum_{a}^{b}{x};\\lim_{a \\rightarrow b}{x}".split(";"));z.JC(this,new z.Ie(10,2))};var DK=function(a){sK.call(this,a,"mn",0,0,46,18,["g","s","c","m","a"],EK.aa());z.JC(this,new z.Ie(5,1))};
var EK=function(){};var FK=function(a){sK.call(this,a,"s",0,50,18,18,"\\times \\div \\cdot \\pm \\mp \\ast \\star \\circ \\bullet \\oplus \\ominus \\oslash \\otimes \\odot \\dagger \\ddagger \\vee \\wedge \\cap \\cup \\aleph \\Re \\Im \\top \\bot \\infty \\partial \\forall \\exists \\neg \\angle \\triangle \\diamond".split(" "));z.JC(this,new z.Ie(7,5))};var GK=function(a){z.F.call(this);this.HN=a;this.pI={};this.dn=null;this.S=new z.zd(this);this.Qw=new z.ud(300);this.S.g(this.Qw,"tick",this.yF)};
var HK=function(a){this.Dj=a||"";nJ.call(this,"+equation")};var IK=function(){z.Xy.call(this)};var JK=function(){z.Xy.call(this)};var KK=function(a,b){var c=z.xz(a.F);return z.uf(c.Qb(),"LI")||hJ(c,function(a){return"LI"==a.tagName})?(a.F.execCommand(b.shiftKey?"+outdent":"+indent"),b.preventDefault(),!0):!1};var LK=function(a){z.Xy.call(this);this.qR=a};var MK=function(a){z.F.call(this);this.pM=a};var NK=function(){z.F.call(this);this.mR=100;this.Td=[];this.sk=[];this.Rt=[]};
var OK=function(a,b,c){if(b.length){var d=b.pop();c.push(d);a.Rt.push({type:b==a.Td?"before_undo":"before_redo",iF:b==a.Td?d.QB:d.xA,state:d});1==a.Rt.length&&a.Jg();0!=b.length&&1!=c.length||a.dispatchEvent("state_change")}};var PK=function(a){z.Xy.call(this);a=a||new NK;this.iH&&z.od(this.iH);this.If=a;this.iH=z.E(this.If,"state_change",this.DN,!1,this);this.oj={};this.Mn={};this.tG=null;this.EM=(0,z.q)(this.jU,this)};
var QK=function(a,b){var c=b.Sg,d,f;b.queryCommandValue("usinglorem")?(d="",f=null):(d=b.m().innerHTML,f=new RK(b),f=f.isValid()?f:null);var g=a.Mn[c];if(g){if(g.Ji==d)return;if(""==d||""==g.Ji){var h;h=b.eu(8,"",{});if(d==h&&""==g.Ji||g.Ji==h&&""==d)return}g.yA=d;g.PT=f;h=a.If;if(0==h.Td.length||!g.equals(h.Td[h.Td.length-1])){h.Td.push(g);h.Td.length>h.mR&&h.Td.shift();var k=h.sk.length;h.sk.length=0;h.dispatchEvent({type:"state_added",state:g});(1==h.Td.length||k)&&h.dispatchEvent("state_change")}}a.Mn[c]=
new SK(c,d,f,a.EM)};var SK=function(a,b,c,d){MK.call(this,!0);this.Vn=a;this.ZI=d;this.Ji=b;this.$J=c};
var RK=function(a){this.ae=a;var b=a.gb.Va();a=(a=z.xz(a))&&a.cg()&&a.Va()==b?a:null;if(z.eG){if(b=a,this.at=!1,b){var c=z.zt(b),d=z.Bt(b);if(c&&d){a=z.At(b);var c=new VJ(c,this.ae.m()),f=z.Ct(b),d=new VJ(d,this.ae.m());b.Yg()?(this.Fa=d,this.lB=f,this.Da=c,this.hx=a):(this.Fa=c,this.lB=a,this.Da=d,this.hx=f);this.at=!0}}}else z.dG&&(b=a,this.at=!1,b&&(a=b.Be(0).de(),z.mf(this.ae.m(),a.parentElement())&&(b=this.ae.gb.wa().body.createTextRange(),b.moveToElementText(this.ae.m()),d=a.duplicate(),d.collapse(!0),
d.setEndPoint("StartToStart",b),this.Fa=TK(d),a=a.duplicate(),a.setEndPoint("StartToStart",b),this.Da=TK(a),this.at=!0)))};var TK=function(a){var b=a.duplicate(),c=a.text,d=c.length;b.collapse(!0);b.moveEnd("character",d);for(var f,g=10;(f=b.compareEndPoints("EndToEnd",a))&&(d-=f,b.moveEnd("character",-f),--g,0!=g););a=0;for(b=c.indexOf("\n\r");-1!=b;)++a,b=c.indexOf("\n\r",b+1);return d+a};
var UK=function(a,b){z.F.call(this);this.ea=new z.zd(this);this.ae=a;this.Cb=b;this.tA=[];z.ch(this.Cb,function(a){a.jb&&this.tA.push(VK(a.ee()))},this);this.Cb.Pe(!1);this.ea.g(this.ae,"cvc",this.VV).g(this.Cb,"action",this.uO)};var VK=function(a){return a};var WK=function(a,b){z.gy.call(this,a||z.NC.aa(),b)};var XK=function(a){z.Xy.call(this);this.UB=z.pm.Wu+"/upload";z.Nb(this.J={},this.defaults,a||{})};
var YK=function(a){var b=EI(a),c=(0,window.$)('\x3cdiv class\x3d"editable-dropzone"\x3e\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"cell"\x3e\x3cdiv\x3e拖拽至此处上传\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e');b.Ry(c[0],a.F.m());return c};var ZK=function(a){var b=EI(a),c=b.B("IMG",{"class":"",style:"display:block",src:z.pm.oB+"/img/spinner2.gif"}),d=z.xz(a.F);d&&WI(d)&&z.mf(a.F.m(),d.Qb())?d.mg(c):z.Bu(a.F.Ha)?z.df(a.F.m(),c,0):a.F.m().appendChild(c);z.A||(z.Hu(c,!1),b.Va().focus());z.zz(a.F);return(0,window.$)(c)};
var $K=function(a,b){var c=[{display:"none"},{display:"table",width:a.oC.width(),height:a.oC.height(),"background-color":"rgba(255, 255, 255, 0.5)"}];c[2]=window.$.extend({},c[1],{"background-color":"rgba(245, 245, 245, 0.5)"});a.LK.css(c[b])};
var aL=function(a,b){var c=new window.FormData;c.append("via","xhr2");c.append("upload_file",b);var d;d=window.$.ajaxSettings.xhr();d.withCredentials=!0;var f=window.$.ajax({url:a.UB,data:c,processData:!1,contentType:!1,xhr:function(){return d},type:"POST"}).done(function(a){"string"===window.$.type(a)&&(a=JSON.parse(a));if(1===a.code)z.W.message(a.msg);else{var b=new window.Image;b.src=a.msg[0];b.setAttribute("originImgSrc",b.src.replace("_m.jpg","_r.jpg"));b.setAttribute("data-rawWidth",a.msg[1]);
b.setAttribute("data-rawHeight",a.msg[2]);f.yC.after(b)}}).fail(function(){z.W.message("上传失败！\x3e_\x3c")}).always(function(){f.yC.remove()});f.yC=ZK(a)};var bL=function(){z.Xy.call(this)};var cL=function(a){return a&&"BR"===a.tagName};
var dL=function(a,b){function c(a,b){return{$A:a,CH:b}}z.B&&(a.normalize(),b=z.qu());var d=eL(b);if(!d)return c(!1,null);if(z.Bu(a))return c(!0,a);for(var f=d;f!==a;){if(cJ(f))return c(!1,null);f=f.parentNode}if(cL(d)&&cL(d.previousSibling))return c(!0,d);d=b.Qb();return!d||1!==d.nodeType||d.childNodes.length&&!z.Bu(d)?c(!1,null):c(!0,d)};var eL=function(a){var b=a.la(),c=a.La();a=a.vc();var d=a.childNodes.length;3!==b.nodeType&&d&&(b=a.childNodes[c===d?d-1:c]);return b};
var fL=function(a){z.Q.call(this);z.Nb(this.J={},this.defaults,a||{});this.ne=null};var gL=function(a){var b=z.ha(a);a=b.next().value;b=b.next().value;return{label:a,value:b,toString:z.jb(a)}};var hL=function(a){var b=z.rb(iL,function(b){var d=z.ha(b);b=d.next().value;d=d.next().value;return b===a||d===a});return b&&gL(b)};
var jL=function(a,b,c){var d=a.J,f={},g=new z.es(kL,!1),h=new z.Is(c,f);c=new z.vs(null,null,!1);g.wi=function(a){return function(b,c,d){(0,z.bb)(b)?a.apply(this,arguments):d(b,kL)}}(g.wi);f.ud=function(b,c,f){b=b.data;b.value===a.ne&&(z.V.add(f,d.JD),f.appendChild(z.M("i","icon "+d.JD)));f.appendChild(window.document.createTextNode(b.toString()))};f=new z.hs(g,h,c);c.Z=f;c.Vk(b);return f};
var lL=function(a,b,c){var d=a.J,f=a.o(),g=jL(a,b,c);g.cm=20;f.g(g,"suggestionsupdate",function(){g.ag(g.Wc+0)}).g(g,"update",function(a){this.Wz(a.xi)}).g(g,"dismiss",function(){this.Bi(!0)});b=g.M;b.className=d.XQ;b.lh=d.gT;b.Ev=d.Cg;a.Z=g};var mL=function(a){z.Xy.call(this);z.Nb(this.J={},this.defaults,a||{});this.ox=this.Cb=null};var nL=function(a){return"P"===a.tagName};var oL=function(a){return 3===a.nodeType};var pL=function(a){return a&&"PRE"===a.tagName};
var qL=function(a){var b,c=new z.ex(pL,!1,null,a),d=z.M("div",{style:"display:none"});z.Qw(c,new z.qg(4,0,0,0));z.cx(c,new z.qg(4,0,0,0));c.Qp=150;c.so=100;c.oh(d);c.className="hc-lang-select";z.E(c,"beforeshow",function(a){b=a.target.anchor;c.setPosition(new z.Nw(b,1));if(b.lang){a=f;var d=hL(b.lang);d&&a.Ea(d.value);f.Bi(!0)}else f.wk("选择语言")});z.E(c,"beforehide",function(c){b=null;f.Ea(null);if((c=c.target)&&a.contains(c)&&pL(c))return!1});var f=new fL;f.render(d);z.E(f,"change",function(a){b&&
(b.lang=a.fT.value,c.G(!1))});return{Qx:z.jb(c),EX:z.jb(f),H:function(){c.H();f.H()}}};
var rL=function(a){function b(a){return z.x(f,a)}function c(){var a=window.document.createTextNode("\n");f.push(a);return a}var d=window.document.createElement("div");d.innerHTML=a;var f=[],g=z.lq(b);a=z.Lo(d,aJ);z.w(a,function(a){a.lastChild&&"BR"===a.lastChild.tagName&&a.removeChild(a.lastChild);a.firstChild||a.appendChild(window.document.createTextNode(""));a.insertBefore(c(),a.firstChild);a.appendChild(c())});a=z.wb(d.getElementsByTagName("br"));z.w(a,function(a){a!==a.parentNode.lastChild&&z.Wp(window.document.createTextNode("\n"),
a)});d=z.Lo(d,oL);d=z.Vo(function(a){return z.nb(a,function(c,d){var f=a[d-1];return!f||!(b(f)&&b(c))})},function(a){var b=z.jq(a,g);return-1!==b?a.slice(0,b+1):a},function(a){var b=z.sb(a,g);return-1!==b?a.slice(b):a})(d);return z.ob(d,function(a){return a.nodeValue}).join("").replace(/\xa0/g," ")};var sL=function(a,b){a.Cb&&a.ox&&z.ch(a.Cb,function(a){a instanceof z.QC&&a.Wa(!b||z.x(this.ox,a.ee()))},a)};var tL=function(a,b,c){for(a=a.F.Ha;b!==a;){if(c(b))return b;b=b.parentNode}};
var uL=function(a){var b,c=z.qu();c&&a.F.Ha.contains(c.Qb())?(b=c.Y(),a=(b=tL(a,b,pL))?"1":"2"):a="0";return{state:a,du:c,code:b}};var vL=function(a,b){var c=window.document.createTextNode(b);a.mg(c);z.Hu(c)};var wL=function(a,b,c){a.Fn("i",function(a,f){b.mg(a);a=f();c=z.Ma(c);z.Wp(window.document.createTextNode(c),a)})};var xL=function(a,b){for(var c=a,d=[];c&&c!==b;)d.push([c.parentNode.childNodes.length,z.mb(c.parentNode.childNodes,c)]),c=c.parentNode;return d};
var yL=function(a){var b=uL(a);a=b.du;var c=b.code;if("1"===b.state){var b=function(a,b){return b===a.length||zL&&b===a.length-1&&"\n"===a.slice(-1)},d=a.la(),f=xL(d,c),f=!f.length||z.uo(f,function(a){return a[0]===a[1]+1}),g=oL(d);f&&(!g||g&&b(d.nodeValue,a.La()))&&AL(c)}};var AL=function(a){cJ(a)||z.cf(window.document.createElement("br"),a)};var BL=function(a,b){a.Fn("i",function(a,d){b.mg(a);(0,window.setTimeout)(function(){var b=window.document.createTextNode("\r");a=d();z.Wp(b,a);z.Hu(b)})})};
var CL=function(a,b,c){var d=a.J,f;b.bd();var g=DL(a,b);g?(f=window.document.createElement("PRE"),g.parentNode.insertBefore(f,g)):a.Fn("PRE",function(a,c){b.insertNode(a);f=c()});!c&&z.A&&(c=" ");f.lang=d.uN;z.nf(f,c);z.Bu(f)?z.Gu(f.firstChild):z.Hu(f.lastChild);AL(f)};
var DL=function(a,b){function c(a){return a.parentNode.insertBefore(window.document.createTextNode(""),a)}var d=JI(b,!0),f=d.node,g,h=a.F.Ha,k=tL(a,f,z.mq(aJ,z.lq(nL)))||h;if(oL(f)){var m=f.parentNode;!f.nodeValue&&m!==h&&z.Bu(m)?(g=c(m),f=c(g),m.parentNode.removeChild(m)):g=z.A&&d.offset===f.length?z.cf(window.document.createTextNode(""),f):f.splitText(d.offset)}else"BR"===f.tagName&&(g=f,f=c(f));return g?(d=$I(f,g,k),f=d.firstChild,z.$e(k,d.childNodes),f):null};
var EL=function(){z.Xy.call(this);this.dT=null};var FL=function(a){a.push("\x3cbr\x3e")};var GL=function(a){if(!z.xz(a.F).isCollapsed()){var b=a.dT||(0,z.q)(a.RI,a);HL(a,b);EI(a).wa().execCommand("RemoveFormat",!1,void 0);z.pG&&HL(a,function(a){var b=z.D("528")?/&nbsp;/g:/\u00A0/g;return a.replace(b," ")})}};var IL=function(a,b){for(var c=a.F.m();b&&b!=c;){if("TABLE"==b.tagName)return b;b=b.parentNode}return null};
var HL=function(a,b){var c=z.xz(a.F);if(!(1<c.xj())){if(z.y||z.Hc){var d=XI(c,a.F.m()),f=IL(a,d.Y()),g=IL(a,d.la());if(f||g){if(f==g)return;var h,k=c;h=f;var c=g,d=new RI(k),m=k.Y(),n=k.xa(),t=k.la(),k=k.La(),C=EI(a);if(h){var J=C.createTextNode("");z.cf(J,h);m=J;n=0}c&&(J=C.createTextNode(""),z.bf(J,c),t=J,k=0);z.bu(m,n,t,k).select();h=d;f||(c=z.N(zI(h,!0)),a.kB=c);g||(c=z.N(zI(h,!1)),a.gx=c);c=z.xz(a.F);d=XI(c,a.F.m())}d.select();c=d}m=c;c=EI(a).B("DIV");d=m.de();z.eG?c.appendChild(d.cloneContents()):
z.dG&&(n=m.Kd(),n=n.replace(/\r\n/g,"\r"),t=n.length,m=t-z.sq(n).length,n=t-z.rq(n).length,d.moveStart("character",m),d.moveEnd("character",-n),m=d.htmlText,"Formatted"==d.queryCommandValue("formatBlock")&&(m=z.Na(d.htmlText)),c.innerHTML=m);m=b(c.innerHTML);C=z.xz(a.F);c=EI(a);n=z.pq();d=z.pq();m='\x3cspan id\x3d"'+n+'"\x3e\x3c/span\x3e'+m+'\x3cspan id\x3d"'+d+'"\x3e\x3c/span\x3e';k=z.pq();t='\x3cspan id\x3d"'+k+'"\x3e\x3c/span\x3e';if(z.dG){J=C.Be(0).de();J.pasteHTML(t);for(var K;(K=J.parentElement())&&
z.Bu(K)&&!QI(K);){C=K.nodeName;if("TD"==C||"TR"==C||"TH"==C)break;z.N(K)}J.pasteHTML(m);(k=c.m(k))&&z.N(k)}else if(z.eG){c.wa().execCommand("insertImage",!1,k);C=new RegExp("\x3c[^\x3c]*"+k+"[^\x3e]*\x3e");K=z.xz(a.F).Qb();3==K.nodeType&&(K=K.parentNode);for(;!C.test(K.innerHTML);)K=K.parentNode;if(z.y)z.Eu(K,K.innerHTML.replace(C,m));else{z.Eu(K,K.innerHTML.replace(C,t));for(K=k=c.m(k);(K=k.parentNode)&&z.Bu(K)&&!QI(K);){C=K.nodeName;if("TD"==C||"TR"==C||"TH"==C)break;z.cf(k,K);z.N(K)}z.Eu(K,K.innerHTML.replace(new RegExp(t,
"i"),m))}}K=c.m(n);c=c.m(d);z.bu(K,0,c,c.childNodes.length).select();z.N(K);z.N(c);(z.y||z.Hc)&&h&&(c=z.xz(a.F),K=a.F.m(),a.kB&&(K.insertBefore(a.kB,K.firstChild),a.kB=null),a.gx&&(K.appendChild(a.gx),a.gx=null),K=null,d=zI(h,!0),m=zI(h,!1),d&&m&&(K=z.bu(d,0,m,0)),f=f?K:c,g=g?K:c,GI(f.Y(),f.xa(),g.la(),g.La()).select(),h.H())}};var JL=function(){EL.call(this)};var KL=function(a){iJ.call(this,a);this.S=new z.zd(this);this.UB=z.pm.Wu+"/upload";this.MM=!z.A};
var LL=function(a){z.Mc.call(this,"ok");var b=a[0];this.Vl=b;this.nI=b.replace("_m.jpg","_r.jpg");this.JI=a[1];this.II=a[2]};var ML=function(a,b){function c(a){a.eq(b).addClass("selected").siblings().removeClass("selected")}var d=(0,window.$)(".tab-nav",a.uB),f=(0,window.$)(".tab-content",a.form);z.P(a.hf,!1);var g=f.eq(b);g.find("input").val("");c(d);c(f);g.find(":text").focus()};var NL=function(a,b){z.P(a.dh,!1);a.hf.innerHTML=b;z.P(a.hf,!0)};var OL=function(){nJ.call(this,"image");this.S=new z.zd(this)};
var PL=function(a){iJ.call(this,a);this.S=new z.zd(this)};var QL=function(a,b,c,d,f){z.Mc.call(this,"ok");this.dW=a;this.cW=b;this.qK=f;this.eV=c;this.poster=d};var RL=function(a,b){b=z.Ao(b);if(!b)return!1;var c=b.match(/[\-a-zA-Z0-9@:%_\+.~#?&\/\/=]{2,256}\.[a-z]{2,4}\b(\/[\-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)?/gi);c||(z.P(a.dh,!1),a.hf.innerHTML="我们无法识别你输入的视频页地址",z.P(a.hf,!0));return c};var SL=function(){nJ.call(this,TL);this.S=new z.zd(this)};var UL=function(){};
var VL=function(a,b){var c=[];b.enableFullScreen&&c.push("toggleFullScreen");c.push("+bold","+italic","+underline",new WK,"+blockquote","+code","+insertOrderedList","+insertUnorderedList","+equation");b.canUploadMedia_&&c.push(new WK,"image",TL);b.useRemoveFormat_&&c.push(new WK,"+removeFormat");for(var d=z.H(a),f=[],g=0,h;h=c[g];g++){if(z.pa(h)){var k=void 0;if(h=z.DH[h]){var k=h.factory||z.vD,m=h.Ca,n=h.V,t=h.caption,C=h.Pa,J=d||z.H(),k=k(m,n,t,C,null,J);h.jb&&(k.jb=!0)}h=k}h&&f.push(h)}c=z.H(a);
c=new PI(z.OC.aa(),z.WF,c);d=z.Ng(a);c.qh(d);c.Pe(!1);for(g=0;h=f[g];g++)h.Ub(32,!1),h.qh(d),c.K(h,!0);c.render(a);return c};var WL=function(a,b){var c=a.m(),d=new z.Uz;d.w(c);var f=z.M("div",{style:"display:none",className:"tr-spinner spinner-gray"});b.m().appendChild(f);d.on("willScrape",function(){z.P(f,!0)}).on("didScrape",function(){z.P(f,!1)});z.Bc(a,d)};z.Et.prototype.uh=z.Y(49,function(a,b){this.insertNode(a,!0);this.insertNode(b,!1)});
z.Jt.prototype.uh=z.Y(48,function(a,b){var c=z.Se(z.Ke(this.Y()));if(c=z.qu(c))var d=c.Y(),f=c.la(),g=c.xa(),h=c.La();var k=this.O.cloneRange(),m=this.O.cloneRange();k.collapse(!1);m.collapse(!0);k.insertNode(b);m.insertNode(a);k.detach();m.detach();if(c){if(3==d.nodeType)for(;g>d.length;){g-=d.length;do d=d.nextSibling;while(d==a||d==b)}if(3==f.nodeType)for(;h>f.length;){h-=f.length;do f=f.nextSibling;while(f==a||f==b)}z.bu(d,g,f,h).select()}});
z.Ot.prototype.uh=z.Y(47,function(a,b){var c=this.O.duplicate(),d=this.O.duplicate();z.Wt(c,a,!0);z.Wt(d,b,!1);this.Ed()});z.$t.prototype.uh=z.Y(46,function(a,b){z.du(this).uh(a,b);this.Ed()});z.v(BI,z.ut);BI.prototype.up=function(a){z.N(zI(this,!0));z.N(zI(this,!1));return a};
BI.prototype.nu=function(){var a=null,b=zI(this,!this.GA),c=zI(this,this.GA);if(b&&c){var a=b.parentNode,b=z.mb(a.childNodes,b),d=c.parentNode,c=z.mb(d.childNodes,c);d==a&&(this.GA?b--:c--);a=z.bu(a,b,d,c);a=this.up(a);a.select()}else this.up();return a};BI.prototype.D=function(){this.up();this.ca=null};z.Rw.prototype.Rx=z.Y(44,function(){return this.m().innerHTML});
z.Ot.prototype.cg=z.Y(41,function(){var a=this.Mr.body.createTextRange();a.moveToElementText(this.Mr.body);return this.Fg(new z.Ot(a,this.Mr),!0)});z.$t.prototype.cg=z.Y(40,function(){return(!this.Ba||AI(this.Ba))&&(!this.ua||AI(this.ua))&&(!(z.A&&!(9<=z.Ug))||z.du(this).cg())});z.fu.prototype.cg=z.Y(39,function(){var a=!1;try{a=z.uo(this.bi(),function(a){return z.A?!!a.parentNode:z.mf(a.ownerDocument.body,a)})}catch(b){}return a});z.lu.prototype.cg=z.Y(38,function(){return z.uo(z.yt(this),function(a){return a.cg()})});
z.Jt.prototype.bd=z.Y(37,function(){var a=this.O;a.extractContents();if(a.startContainer.hasChildNodes()){var b=a.startContainer.childNodes[a.startOffset];if(b){var c=b.previousSibling;""==z.Qp(b)&&z.N(b);c&&""==z.Qp(c)&&z.N(c)}}if(z.Gl){var b=this.Y(),c=this.xa(),d=this.la(),f=this.La(),g=b.nextSibling;b==d&&b.parentNode&&3==b.nodeType&&g&&3==g.nodeType&&(b.nodeValue+=g.nodeValue,z.N(g),a.setStart(b,c),a.setEnd(d,f))}});
z.Ot.prototype.bd=z.Y(36,function(){if(!this.isCollapsed()&&this.O.htmlText){var a=this.Y(),b=this.la(),c=this.O.text,d=this.O.duplicate();d.moveStart("character",1);d.moveStart("character",-1);d.text==c&&(this.O=d);this.O.text="";this.Ed();c=this.Y();d=this.xa();try{var f=a.nextSibling;a==b&&a.parentNode&&3==a.nodeType&&f&&3==f.nodeType&&(a.nodeValue+=f.nodeValue,z.N(f),this.O=z.Pt(c),this.O.move("character",d),this.Ed())}catch(g){}}});z.$t.prototype.bd=z.Y(35,function(){z.du(this).bd();this.Ed()});
z.fu.prototype.bd=z.Y(34,function(){if(this.O){for(var a=[],b=0,c=this.O.length;b<c;b++)a.push(this.O.item(b));z.w(a,z.N);this.collapse(!1)}});z.lu.prototype.bd=z.Y(33,function(){z.w(z.yt(this),function(a){a.bd()})});z.wt.prototype.mg=z.Y(32,function(a){this.isCollapsed()||this.bd();return this.insertNode(a,!0)});z.fu.prototype.mg=z.Y(31,function(a){a=this.insertNode(a,!0);this.isCollapsed()||this.bd();return a});
z.vt.prototype.Sp=z.Y(30,function(){var a=this.Lc?-1:1;this.Vb==a&&(this.Vb=-1*a,this.depth+=this.Vb*(this.Lc?-1:1))});z.Ft.prototype.Sp=z.Y(29,function(){z.Ft.v.Sp.apply(this);if(z.mf(this.node,this.ua))throw z.Pd;});z.Xq.prototype.Bi=z.Y(28,function(a,b){var c=a.rd(),d=this.T()+"-collapse-left",f=this.T()+"-collapse-right";a.mj(c?f:d,!!(b&1));a.mj(c?d:f,!!(b&2))});z.gr.prototype.Bi=z.Y(27,function(a){this.M.Bi(this,a)});z.vj.prototype.Lx=z.Y(23,function(){z.xj(this);return this.rc});
z.ad.prototype.Gl=z.Y(2,function(a,b){var c=this.kc[a.toString()],d=[];if(c)for(var f=0;f<c.length;++f){var g=c[f];g.dl==b&&d.push(g)}return d});z.F.prototype.Gl=z.Y(1,function(a,b){return this.$d.Gl(String(a),b)});z.v(PI,z.Vr);PI.prototype.fe=function(a){PI.v.fe.call(this,a);this.yf||z.Zr(this)};z.v(RI,BI);RI.prototype.up=function(a){var b=zI(this,!0),c=zI(this,!1),b=b&&c?z.Sp(b,c):b||c;RI.v.up.call(this);if(a)return OI(b,a);b&&(a=z.qu(z.Se(z.Ke(b))),(a=OI(b,a))&&a.select())};
var ZI={text:!0,file:!0,url:!0},bJ={ADDRESS:!0,ARTICLE:!0,ASIDE:!0,BLOCKQUOTE:!0,BODY:!0,CAPTION:!0,CENTER:!0,COL:!0,COLGROUP:!0,DETAILS:!0,DIR:!0,DIV:!0,DL:!0,DD:!0,DT:!0,FIELDSET:!0,FIGCAPTION:!0,FIGURE:!0,FOOTER:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0,HEADER:!0,HGROUP:!0,HR:!0,ISINDEX:!0,OL:!0,LI:!0,MAP:!0,MENU:!0,NAV:!0,OPTGROUP:!0,OPTION:!0,P:!0,PRE:!0,SECTION:!0,SUMMARY:!0,TABLE:!0,TBODY:!0,TD:!0,TFOOT:!0,TH:!0,THEAD:!0,TR:!0,UL:!0},TL,XL;z.v(iJ,z.F);
iJ.prototype.show=function(){this.df||(this.df=this.Gw(),this.df.g("hide",this.xO,!1,this));this.df.G(!0)};iJ.prototype.hide=function(){this.df&&this.df.G(!1)};iJ.prototype.rb=function(){return!!this.df&&this.df.U()};jJ.prototype.Na=function(a){this.Oi.Na(a);return this};jJ.prototype.Cd=function(a,b,c){c=c||z.pq();this.xn.set(c,a);this.wn[c]=b;return this};jJ.prototype.Ih=function(a){z.bj(this.Oi.ai(),a);return this};jJ.prototype.ka=function(a){this.Oi.R().appendChild(a);return this};z.e=iJ.prototype;
z.e.Lx=function(a){return this.df.sc.mf(a)};z.e.rP=function(a){return(a=this.Hn(a))?this.dispatchEvent(a):!1};z.e.lo=function(){return this.dispatchEvent("cancel")};z.e.D=function(){this.df&&(this.hide(),this.df.H(),this.df=null);iJ.v.D.call(this)};z.e.xO=function(){this.dispatchEvent("afterhide")};z.v(nJ,z.Xy);z.e=nJ.prototype;z.e.Ge=function(a){return a==this.bN};z.e.execCommand=function(a,b){return this.jf.apply(this,arguments)};z.e.nF=function(){return this.Ia};z.e.jf=function(a,b){this.cJ||pJ(this);this.Ia||(this.Ia=this.Fw(z.H(this.F.Uk),b));var c=z.xz(this.F);this.YI=DI(this);this.gJ=c&&new RI(c);z.vu(this.F.gb.Va());z.md(this.Ia,"afterhide",this.jo,!1,this);this.F.Ug=!0;this.Ia.show();this.dispatchEvent("dialogOpened");z.yz(this.F);return!0};
z.e.jo=function(){this.F.Ug=!1;oJ(this);this.YI();this.cJ||pJ(this);this.dispatchEvent("dialogClosed");z.yz(this.F);this.F.Fr.selectionchange=(0,z.G)()};z.e.D=function(){pJ(this);nJ.v.D.call(this)};z.e.cJ=!1;z.e.Vy=!1;var vJ=/^[\w-]+(\.[\w-]+)*\@([\w-]+\.)+(\d+|\w\w+)$/i;z.v(wJ,z.Xy);wJ.prototype.nd=function(){return"BTF"};var YL={QW:"+link",xW:"+createLink",GW:"+formatBlock",KW:"+indent",XW:"+outdent",dX:"+strikeThrough",IW:"+insertHorizontalRule",eX:"+subscript",fX:"+superscript",iX:"+underline",tW:"+bold",LW:"+italic",FW:"+fontSize",EW:"+fontName",DW:"+foreColor",nW:"+backColor",WW:"+insertOrderedList",mX:"+insertUnorderedList",MW:"+justifyCenter",NW:"+justifyFull",PW:"+justifyRight",OW:"+justifyLeft"},ZL=z.gq(YL);wJ.prototype.Ge=function(a){return a in ZL};
var $L=["+createLink"];z.e=wJ.prototype;z.e.MG=function(a){return z.x($L,a)};z.e.Ae=function(){return z.xz(this.F)};
z.e.jf=function(a,b,c,d){var f,g,h,k,m,n=b;switch(a){case "+backColor":if(null!==n)if(z.mG){a=n;g=z.xz(this.F);var t,C;g&&g.isCollapsed()&&(t=EI(this).createTextNode(z.y?" ":""),h=g.Y(),C=1==h.nodeType?h:h.parentNode,""==C.innerHTML?(C.style.textIndent="-10000px",C.appendChild(t)):(C=EI(this).B("SPAN",{style:"text-indent:-10000px"},t),g.mg(C)),z.tu(t).select());DJ(this,"hiliteColor",a,!1,!0);t&&(z.y&&(t.data=""),C.style.textIndent="")}else z.vg?DJ(this,"hiliteColor",n):DJ(this,a,n);break;case "+createLink":m=
NJ(this,b,c,d);break;case "+link":a:{m=n;this.F.wf||EI(this).Va().focus();g=(a=this.Ae())&&a.Qb();if((g=z.uf(g,"A"))&&z.vf(g,QI))z.ef(g);else if(m=NJ(this,a,"/",m)){if(!this.F.execCommand("link",m))if(h=this.F.Uk.prompt(z.PG,"http://"))a=rJ(m)||h,g=m.te,g.href=h,n=rJ(m),a!=n&&(h=z.yu(g),h.tagName&&"IMG"==h.tagName?h.setAttribute("alt",a?a:""):(3==h.nodeType&&(h=h.parentNode),z.Qp(h)!=n&&(h=g),z.af(h),g=z.H(h),h.appendChild(g.createTextNode(a))),m.Pw=null),a=m.te,z.qG?(g=a.nextSibling,g&&3==g.nodeType&&
(z.Ka(g.data," ")||z.Ka(g.data," "))||(g=z.H(a).createTextNode(" "),z.cf(g,a)),z.uu(g,1).select()):z.Hu(a,!1);else{a=z.tu(m.te);a=new RI(a);z.ef(m.te);for(m.te=null;m.rx.length;)z.ef(m.rx.pop());a.restore().select();m=null;break a}break a}m=null}break;case "+justifyCenter":case "+justifyFull":case "+justifyRight":case "+justifyLeft":DJ(this,a,null,!1,!0);z.y&&DJ(this,a,null,!1,!0);z.lG&&z.y||z.Qd(z.xz(this.F),CJ);break;default:z.A&&"+formatBlock"==a&&n&&(n="\x3c"+n+"\x3e");if("+foreColor"==a&&null===
n)break;switch(a){case "+indent":case "+outdent":z.lG&&(z.y&&(g=!0),z.vg&&(g="+outdent"==a?!xJ(this).queryCommandEnabled("outdent"):!0));case "+insertOrderedList":case "+insertUnorderedList":if(t=z.tG)t=xJ(this),t=UJ(this,!0,t,a,void 0);t?h="P"!=this.F.queryCommandValue("+defaultTag"):z.uG||yJ(this);z.y&&z.sG&&!this.queryCommandValue(a)&&(t=this.F.queryCommandValue("+defaultTag"),"P"==t||"DIV"==t?t=!1:(t=this.Ae(),t.isCollapsed()&&3!=t.vc().nodeType?(f=EI(this).createTextNode(" "),t.insertNode(f,
!1),z.tu(f).select(),t=!0):t=!1),k|=t);case "+formatBlock":f=!!this.F.Sb.Bidi;break;case "+subscript":case "+superscript":z.rG&&!this.queryCommandValue(a)&&(t="+subscript"==a?"+superscript":"+subscript",C=BJ(t),this.queryCommandValue(t)||xJ(this).execCommand(C,!1,null),xJ(this).execCommand(C,!1,null));break;case "+underline":case "+bold":case "+italic":g=z.y&&z.lG&&this.queryCommandValue(a);break;case "+foreColor":case "+fontName":g=z.lG&&z.y}DJ(this,a,n,f,!!g);k&&xJ(this).execCommand("Delete",!1,
!0);h&&xJ(this).execCommand("FormatBlock",!1,"\x3cdiv\x3e")}z.y&&!this.F.Ug&&EI(this).Va().focus();return m};
z.e.queryCommandValue=function(a){var b;switch(a){case "+link":return a=(a=this.Ae())&&a.Qb(),a=z.uf(a,"A"),!!a&&!!z.vf(a,QI);case "+justifyCenter":case "+justifyFull":case "+justifyRight":case "+justifyLeft":return RJ(this,a);case "+formatBlock":return QJ(z.xz(this.F));case "+indent":case "+outdent":case "+insertHorizontalRule":return!1;case "+fontSize":case "+fontName":case "+foreColor":case "+backColor":return this.$t(xJ(this),a,z.lG&&z.y);case "+underline":case "+bold":case "+italic":b=z.lG&&
z.y;default:var c=xJ(this);return UJ(this,!0,c,a,b)}};z.e.wI=function(a){z.jG&&a.match(/^\s*<script/i)&&(a="\x26nbsp;"+a);z.kG&&(a=a.replace(/<(\/?)strong([^\w])/gi,"\x3c$1b$2"),a=a.replace(/<(\/?)em([^\w])/gi,"\x3c$1i$2"));return a};z.e.TM=function(a){a=a.getElementsByTagName("IMG");for(var b=0,c;c=a[b];b++)if(z.A){c.removeAttribute("tabIndex");c.removeAttribute("tabIndexSet");var d=c;null!==d&&"removeAttribute"in d&&d.removeAttribute(z.va);try{delete d[z.va]}catch(f){}c.DR&&(c.tabIndex=c.DR)}};
z.e.UM=function(a){if(z.B){for(var b=z.Me(this.F.gb.Ka,"HEAD",void 0,void 0),c=[],d=b.length,f=1;f<d;++f)for(var g=b[f].getElementsByTagName("STYLE"),h=g.length,k=0;k<h;++k)c.push(g[k].outerHTML);return c.join("")+a}return a};z.e.ws=function(a,b,c){if(!c)return!1;var d;switch(b){case "b":d="+bold";break;case "i":d="+italic";break;case "u":d="+underline";break;case "s":return!0}return d?(this.F.execCommand(d),!0):!1};
var zJ=z.A?/<br([^\/>]*)\/?>/gi:/<br([^\/>]*)\/?>(?!<\/(div|p)>)/gi,FJ={indent:1,outdent:1,insertOrderedList:1,insertUnorderedList:1,justifyCenter:1,justifyFull:1,justifyRight:1,justifyLeft:1,ltr:1,rtl:1},EJ={insertOrderedList:1,insertUnorderedList:1},PJ={1:1,a:1,A:1,i:1,I:1},OJ={disc:1,circle:1,square:1},GJ={justifyCenter:1,justifyFull:1,justifyRight:1,justifyLeft:1,formatBlock:1},HJ={insertOrderedList:1,insertUnorderedList:1},TJ={center:1,justify:1,right:1,left:1};
wJ.prototype.$t=function(a,b,c){return UJ(this,!1,a,b,c)};z.v(VJ,z.yc);VJ.prototype.toString=function(){for(var a=[],b,c=0;b=this.Bt[c];c++)a.push(this.Gt[c]+","+b);return a.join("\n")};VJ.prototype.D=function(){delete this.Gt;delete this.Bt};z.v(XJ,z.Xy);z.e=XJ.prototype;z.e.tag="DIV";z.e.nd=function(){return"EnterHandler"};z.e.enable=function(a){XJ.v.enable.call(this,a);!z.wG||"P"!=this.tag&&"DIV"!=this.tag||EI(this).wa().execCommand("opera-defaultBlock",!1,this.tag)};z.e.wI=function(a){return!a||z.vq(a)?z.jG?this.nO():"":a};z.e.nO=z.jb("\x3cbr\x3e");
z.e.gP=function(a){if(z.y&&this.F.Ug)return!1;if(8==a.keyCode){var b=z.xz(this.F),c=this.F.m(),b=b&&b.Y();c.firstChild==b&&z.Bu(b)&&(a.preventDefault(),a.stopPropagation())}else if(13==a.keyCode)if(z.y){if(!a.shiftKey){var c=z.xz(this.F),b=!c||c.isCollapsed(),d=$J(this),f=this.F.execCommand("+splitBlockquote",d);f&&(a.preventDefault(),a.stopPropagation());z.eG||d.removeNode(!0);f||this.XO(a,b,c)}}else{this.F.Yh();c=$J(this);if(b=!!this.F.execCommand("+splitBlockquote",c))a.preventDefault(),a.stopPropagation();
z.eG||c.removeNode(!0);z.B&&this.YO(a);if(z.A||z.vg)YJ(this);else if(!b&&z.B){if(b=c=z.xz(this.F))a:{for(b=c.Qb();b;b=b.parentNode)if(aJ(b)){b="BLOCKQUOTE"==b.tagName;break a}b=!1}if(b){b=EI(this);d=b.createElement("BR");c.insertNode(d,!0);if(c=aJ(d.parentNode)){for(c=d.nextSibling;c&&3==c.nodeType&&!c.nodeValue;)c=c.nextSibling;c=!c}c&&z.bf(b.createElement("BR"),d);z.Hu(d,!1);a.preventDefault()}}this.F.ef()}else z.y&&46==a.keyCode&&(b=z.xz(this.F),b.isCollapsed()&&(c=b.la(),1==c.nodeType&&(b=c.childNodes[b.La()])&&
"BR"==b.tagName&&(d=z.zu(z.eq(new z.wu(b,!1,!0),z.Au)),f=b.nextSibling,c.removeChild(b),a.preventDefault(),f&&aJ(f)&&(d&&"BR"!=d.tagName&&!aJ(d)?z.uu(d,z.Du(d)).select():(a=z.yu(f),z.uu(a,0).select())))));return!1};z.e.vs=function(a){if(z.y&&this.F.Ug)return!1;(z.A||z.vg)&&13==a.keyCode&&YJ(this,!0);return!1};z.e.YO=z.p;z.e.XO=z.p;var ZJ={LI:!0,DIV:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0};var aM=new aK,bM=["click",z.y?"keypress":"keydown","keyup"];aK.prototype.g=function(a,b,c,d,f){function g(a){var c=z.dd(b),f=z.kf(a.target)?a.target.getAttribute("role")||null:null;"click"==a.type&&z.Uc(a)?c.call(d,a):13!=a.keyCode&&3!=a.keyCode||"keyup"==a.type?32!=a.keyCode||"keyup"!=a.type||"button"!=f&&"tab"!=f||(c.call(d,a),a.preventDefault()):(a.type="keypress",c.call(d,a))}g.Xj=b;g.ru=d;f?f.g(a,bM,g,c):z.E(a,bM,g,c)};
aK.prototype.qa=function(a,b,c,d,f){for(var g,h=0;g=bM[h];h++){var k;var m=a;k=g;var n=!!c;k=z.Wc(m)?m.Gl(k,n):m?(m=z.fd(m))?m.Gl(k,n):[]:[];for(m=0;n=k[m];m++)if(n.listener.Xj==b&&n.listener.ru==d){f?f.qa(a,g,n.listener,c,d):z.nd(a,g,n.listener,c,d);break}}};z.v(bK,z.F);bK.prototype.Pg=function(){return this.yc?this.yc.clone():null};bK.prototype.D=function(){bK.v.D.call(this);this.qz&&(z.od(this.qz),this.qz=null);this.yc=this.av=null};bK.prototype.my=function(){var a=z.Pe(this.av);z.Yp(a,this.yc)||(this.yc=a,this.dispatchEvent("resize"))};z.v(cK,z.F);var dK="tr_bubble";z.e=cK.prototype;z.e.D=function(){cK.v.D.call(this);z.N(this.Dd);this.Dd=null;this.S.H();this.S=null;this.dC.H();this.dC=null};z.e.R=function(){return this.tn};z.e.Qb=function(){return this.Dd};z.e.MP=function(){this.U()&&this.ha()};z.e.Bm=function(a){this.lg.Bm(a)};z.e.ND=function(){this.lg.G(!1)};z.e.vP=function(){for(var a in this.td)z.N(this.td[a].element);this.td={};z.dj(this.Dd,"tr_multi_bubble");this.S.removeAll();this.dispatchEvent("hide")};z.e.U=function(){return this.lg.U()};
var cM=z.A?4:2,gK=new z.qg(cM,0,cM,0);cK.prototype.ha=function(){var a=null,b=!0,c;for(c in this.td)var d=this.td[c],a=d.wB,b=b&&d.AT;c=496;a=z.Ng(this.Dd)!=z.Ng(a);b&&(c=fK(this,a?7:5,4,9));c&496&&(c=fK(this,a?6:4,5,9));c&496&&fK(this,a?7:5,4,5)};cK.prototype.qO=z.Dl;hK.prototype.R=function(){return this.element.lastChild};z.v(iK,z.Xy);var lK={};z.e=iK.prototype;z.e.si=null;z.e.fz=!1;z.e.nd=z.jb("AbstractBubblePlugin");z.e.vs=function(){this.U()&&this.Cj();return!1};
z.e.Cj=function(a,b){var c;if(a)c=a.target;else if(b)c=b;else{var d=z.xz(this.F);if(d){var f=d.Y(),g=d.la(),h=d.xa(),k=d.La();z.A&&d.isCollapsed()&&f!=g&&(d=z.uu(f,h));1==f.nodeType&&f==g&&h==k-1&&(f=f.childNodes[h],1==f.nodeType&&(c=f))}c=c||d&&d.Qb()}var m;a:{if(c){if(d=c)d="IMG"==c.nodeName&&(!!c.getAttribute("eeimg")||z.aj(c,"ee_img"));if(h=d?c:null){if(h!=this.Ju||!this.si)if(this.si&&mK(this),c=kK(this),!eK(c,this.Kx())){this.Ju=h;var f=this.Kx(),k=this.lF(),g=(0,z.q)(this.kN,this),n=this.UU(),
d=z.pq(),h=new hK(c.ca,d,f,k,h,!n);c.td[d]=h;k=0;for(n=c.tn.childNodes.length-1;k<n;k++){var t=c.tn.childNodes[k];if(c.td[t.id].type>f){m=t;break}}z.bf(h.element,m||c.tn.lastChild);g(h.R());YI(h.element,c.S);m=z.to(c.td);1==m?(c.S.g(c.MD,"click",c.ND).g(c.dC,"resize",c.MP).g(c.lg,"hide",c.vP),c.lg.G(!0),c.ha()):2==m&&z.bj(c.Dd,"tr_multi_bubble");c.ha();this.si=d;this.ic.g(c,"hide",this.KF);this.ri();this.fz&&this.ic.g(c.R(),"keydown",this.RR)}m=!1;break a}}this.si&&mK(this);m=!1}return m};
z.e.disable=function(a){if(a.bm==z.iz){var b=lK[a.id];b&&(a==this.F&&mK(this),b.H(),delete lK[a.id])}};z.e.Kx=function(){return""};z.e.lF=function(){return""};z.e.UU=z.Bl;z.e.ri=z.p;z.e.VM=z.p;z.e.KF=function(){this.si=this.Ju=null;this.ic.removeAll();this.VM()};z.e.jy=function(a){if(this.fz&&this.U()&&9==a.keyCode&&!a.shiftKey){var b=kK(this).R();if(b=z.L("tr_bubble_tabbable",b))return b.focus(),a.preventDefault(),!0}return!1};
z.e.RR=function(a){if(this.U()&&9==a.keyCode){var b=kK(this).R(),b=z.Xp("tr_bubble_tabbable",b);(a.shiftKey?b[0]:z.lb(b))==a.target&&(this.F.focus(),a.preventDefault())}};z.e.U=function(){return!!this.si};z.e.ha=function(){var a=kK(this);a&&a.ha()};
z.e.zr=function(a,b,c,d){b=this.ca.B("SPAN",{className:"tr_bubble_link"},b);this.fz&&(b.hasAttribute("tabindex")||b.setAttribute("tabindex",0),z.bj(b,"tr_bubble_tabbable"));b.setAttribute("role","link");d?d.appendChild(b):(d=this.ca.m(a))&&z.Wp(b,d);b.id=a;YI(b,this.ic);c&&(a=this.ic,aM.g(b,c,void 0,a.ea||a,a));return b};z.v(oK,iK);var dM=z.u("Equation:"),eM=z.u("Edit"),fM=z.u("Remove");z.e=oK.prototype;z.e.nd=function(){return"EquationBubble"};z.e.kN=function(a){a.appendChild(a.ownerDocument.createTextNode(dM+" "));this.zr("ee_bubble_edit",eM,this.JN,a);a.appendChild(a.ownerDocument.createTextNode(dM+" - "));this.zr("ee_remove_remove",fM,this.WT,a)};z.e.Kx=function(){return"IMG"};z.e.lF=function(){return z.u("Equation")};z.e.WT=function(){this.F.Yh();z.N(this.Ju);mK(this);this.F.ef()};
z.e.JN=function(){var a=this.Ju;mK(this);this.F.execCommand("+equation",a)};z.v(pK,z.Mc);pK.prototype.type="ok";z.v(qK,z.Mc);z.v(rK,z.Q);rK.prototype.Dj="";rK.prototype.G=function(a){z.P(this.m(),a)};z.v(sK,z.HC);z.e=sK.prototype;z.e.gi=function(){return this.dc};z.e.yl=function(a){return 0<=a&&a<this.cn.length?this.cn[a]:null};z.e.qf=function(a){sK.v.qf.call(this,a);this.jg.dispatchEvent(new uK(gM,this))};z.e.Ml=function(a){sK.v.Ml.call(this,a);a.relatedTarget&&!z.mf(this.m(),a.relatedTarget)&&this.jg.Er()};z.e.od=function(a){sK.v.od.call(this,a);a.relatedTarget&&!z.mf(this.m(),a.relatedTarget)&&this.jg.Qw.stop()};var gM="a";uK.prototype.Tx=function(){return this.mT};z.v(tK,z.zC);z.la(tK);
tK.prototype.T=function(){return"ee-palette"};z.v(vK,rK);z.e=vK.prototype;z.e.VG="";z.e.sw=0;
z.e.B=function(){var a=z.u("TeX 公式"),b=z.u("预览"),c=z.u("了解更多"),d=this.ca,c=d.B("DIV",{style:"display: none;"},d.B("SPAN",{"class":"ee-section-title ee-section-title-floating"},a),this.Dj?d.B("A",{id:"ee-section-learn-more",target:"_blank",href:this.Dj},c):null,d.B("DIV",{style:"clear: both;"}),a=this.nQ=d.B("DIV",{style:"position: relative"}));this.jg.setActive("mn").render(a);a.appendChild(d.B("DIV",{style:"clear:both"}));var f=this.wh=d.B("textarea",{"class":"ee-tex",dir:"ltr"});a.appendChild(f);
a.appendChild(d.B("DIV",{"class":"ee-section-title"},b));b=this.FT=d.B("DIV",{"class":"ee-preview-container"});a.appendChild(b);this.h=c};z.e.C=function(){this.KJ=new z.hC(this.wh);z.E(this.KJ,"input",this.PF,!1,this);this.o().g(this.wh,"keydown",this.PF);this.o().g(this.jg,gM,this.uP)};z.e.G=function(a){vK.v.G.call(this,a);a&&z.wd(this.cO,0,this)};z.e.cO=function(){this.wh.focus();z.ts(this.wh,this.wh.value.length)};z.e.PF=function(){this.sw++;z.wd((0,z.q)(this.DP,this,this.sw),500)};
z.e.DP=function(a){a==this.sw&&wK(this)};z.e.uP=function(a){var b=a.Tx(),c=this.jg,d=c.dn;a=this.wh;if("mn"==b.gi()){var f=b.Ta,f=-1!=f?b.yl(f):null;if(d!=b&&d.gi()==f){c.yF();return}f&&(b=this.jg.setActive(f),b.m()||b.render(this.nQ),b=b.m(),z.Ag(b,0,-b.clientHeight))}else{d=this.jg.dn;f=d.yl(d.Ta);if(!f)return;z.wd((0,z.q)(this.wQ,this,f+" "),0)}a.focus()};z.e.wQ=function(a){var b=this.wh,c=z.qs(b)[0],d=b.value,d=d.substring(0,c)+a+d.substring(c);b.value=d;z.ts(b,c+a.length);wK(this)};z.e.El=function(){return this.wh.value};
z.e.UA=function(a){this.wh.value=a;wK(this)};z.e.D=function(){this.KJ.H();this.jg=null;vK.v.D.call(this)};z.v(xK,z.Q);z.e=xK.prototype;z.e.xh=null;z.e.B=function(){xK.v.B.call(this);this.xr()};z.e.xr=function(){var a=this.m();this.xh=new vK(this.YD,this.Dj,this.ca);this.K(this.xh);this.xh.render(a);this.xh.G(!0)};z.e.ga=function(a){this.h=a;this.xr()};z.e.El=function(){return this.xh.El()};z.e.UA=function(a){this.xh.UA(a)};z.e.Rx=function(){var a=this.El(),b=nK(a);return b?'\x3cimg src\x3d"'+b+'" alt\x3d"'+z.Oa(a)+'" class\x3d"ee_img tr_noresize" eeimg\x3d"1" style\x3d"vertical-align: middle"\x3e':""};
z.e.isValid=function(){return 1024<this.El().length};z.e.G=function(a){this.xh.G(a)};z.e.D=function(){this.xh&&this.xh.H();this.YD=null;xK.v.D.call(this)};z.v(yK,iJ);yK.prototype.Gw=function(){var a=new jJ(this),b=z.u("公式编辑器"),c=z.u("插入公式"),d=z.u("保存修改"),f=z.u("取消"),c=this.nj.El()?d:c;kJ(lJ(a.Na(b).ka(this.nj.m()),f),c);return mJ(a)};yK.prototype.Hn=function(){if(this.nj.isValid())return null;var a=this.nj.Rx();return new pK(a)};yK.prototype.Rz=function(a){this.GH||(this.GH=this.Lx("ok"));this.GH.disabled=!a.isValid};z.v(zK,sK);z.v(AK,sK);z.v(BK,sK);z.v(CK,sK);z.v(DK,sK);DK.prototype.G=function(a,b){return DK.v.G.call(this,!0,b)};z.v(EK,tK);z.la(EK);EK.prototype.T=function(){return"ee-menu-palette"};z.v(FK,sK);z.v(GK,z.F);z.e=GK.prototype;z.e.Tx=function(a){var b=this.pI,c=b[a];if(!c){switch(a){case "mn":c=new DK(this);break;case "g":c=new BK(this);break;case "s":c=new FK(this);break;case "c":c=new AK(this);break;case "m":c=new CK(this);break;case "a":c=new zK(this);break;default:throw Error("Invalid palette type!");}b[a]=c}return c};z.e.setActive=function(a){var b=this.dn;b&&b.G(!1);this.dn=b=this.Tx(a);b.G(!0);return b};z.e.Er=function(){this.Qw.start()};z.e.yF=function(){this.setActive("mn")};
z.e.L=function(){return this.HN};z.e.D=function(){GK.v.D.call(this);this.pI=this.dn=null};z.v(HK,nJ);z.e=HK.prototype;z.e.nd=z.jb("EquationEditorPlugin");z.e.Fw=function(a,b){var c=b||null,d;c?(d=c.getAttribute("alt"),d||(d=(d=c.getAttribute("src"))?z.ce(d,"tex")||"":"")):d="";this.oI=c;c={};c.lT=new GK(a);c=new yK(c,a,d,this.Dj);c.addEventListener("ok",this.po,!1,this);return c};z.e.enable=function(a){HK.v.enable.call(this,a);this.isEnabled(a)&&(this.tN=z.E(a.m(),"dblclick",(0,z.q)(this.MO,this),!1,this))};z.e.disable=function(a){HK.v.disable.call(this,a);this.isEnabled(a)||z.od(this.tN)};
z.e.MO=function(a){(a=a.target)&&"IMG"===a.nodeName&&a.getAttribute("eeimg")&&this.execCommand("+equation",a)};z.e.po=function(a){oJ(this);this.F.Yh();a=z.Ye(EI(this).Ka,a.UN);if(this.oI)z.Wp(a,this.oI);else{var b=z.xz(this.F);b.isCollapsed()||b.bd();a=b.insertNode(a,!1)}z.Hu(a,!1);this.F.ef()};z.v(IK,z.Xy);IK.prototype.ws=function(a){return z.y&&this.F.Ug?!1:9!=a.keyCode||a.metaKey||a.ctrlKey?!1:KK(this,a)};z.v(JK,IK);JK.prototype.nd=function(){return"ListTabHandler"};z.v(LK,z.Xy);z.e=LK.prototype;z.e.nd=z.jb("LoremIpsum");z.e.Jq=z.Cl;z.e.sq=!1;z.e.queryCommandValue=function(a){return"usinglorem"==a&&this.sq};
z.e.execCommand=function(a,b){if("clearlorem"==a){var c=!!b,d=this.F;if(this.sq&&!d.Ug){var f=d.m();f||(f=d.Kc);this.sq=!1;f.style.fontStyle=this.CR;d.Pd(!0,null,!0);c&&d.xc()&&(z.B?(z.Ke(d.m()).body.focus(),d.Wf()):z.vg&&z.Dz(d))}}else"updatelorem"==a&&(c=this.F,this.sq||c.Ug||z.JG==c.id||((d=c.m())||(d=c.Kc),z.Bu(d)&&(this.sq=!0,this.CR=d.style.fontStyle,d.style.fontStyle="italic",c.Pd(!0,this.qR,!0))))};z.e.Ge=function(a){return"clearlorem"==a||"updatelorem"==a||"usinglorem"==a};z.v(MK,z.F);z.v(NK,z.F);z.e=NK.prototype;z.e.Ms=null;z.e.QB=function(){OK(this,this.Td,this.sk)};z.e.xA=function(){OK(this,this.sk,this.Td)};z.e.Jg=function(){if(!this.Ms&&0!=this.Rt.length){var a=this.Rt.shift();this.dispatchEvent({type:a.type,state:a.state})&&(a.state.pM?(this.Ms=z.E(a.state,"action_completed",this.YN,!1,this),a.iF.call(a.state)):(a.iF.call(a.state),this.Jg()))}};z.e.YN=function(){z.od(this.Ms);this.Ms=null;this.Jg()};z.v(PK,z.Xy);PK.prototype.wo=null;var hM=z.gq({kX:"+undo",ZW:"+redo"});z.e=PK.prototype;z.e.Ge=function(a){return a in hM};z.e.cK=function(a){this.disable(a);this.F=null};z.e.enable=function(a){if(!this.isEnabled(a)){z.Az(a);var b=new z.zd(this);z.y||b.g(a,"beforechange",this.zO);b.g(a,z.ez,this.IO);b.g(a,"blur",this.$x);this.oj[a.Sg]=b;QK(this,a)}};z.e.disable=function(a){z.Az(a);var b=this.oj[a.Sg];b&&(b.H(),delete this.oj[a.Sg]);this.Mn[a.Sg]&&delete this.Mn[a.Sg]};z.e.isEnabled=function(a){return!!this.oj[a.Sg]};
z.e.D=function(){PK.v.D.call(this);for(var a in this.oj)this.oj[a].H(),delete this.oj[a];this.F=null;this.If&&(this.If.H(),delete this.If)};z.e.nd=function(){return"UndoRedo"};z.e.execCommand=function(a){"+undo"==a?this.If.QB():"+redo"==a&&this.If.xA()};z.e.queryCommandValue=function(a){var b=null;"+undo"==a?b=0<this.If.Td.length:"+redo"==a&&(b=0<this.If.sk.length);return b};z.e.DN=function(){this.F.dispatchEvent({type:"cvc",cN:["+redo","+undo"]})};
z.e.jU=function(a,b,c){var d=this.F;if(d){z.zz(d,!0,!0);try{d.Yh();d.execCommand("clearlorem",!0);z.Eu(d.m(),b);c&&c.select();var f=this.F;d.focus();f&&f.Sg!=a.Vn&&f.execCommand("updatelorem");var g=this.Mn[a.Vn];g.Ji=b;g.$J=c}catch(h){}finally{this.wo=a,d.ef(),z.yz(d)}}};
z.e.ws=function(a,b,c){if(c){var d;"z"==b?d=a.shiftKey?"+redo":"+undo":"y"==b&&(d="+redo");if(d)return"+undo"==d?(a=this.If,a=a.Td[a.Td.length-1]):(a=this.If,a=a.sk[a.sk.length-1]),a&&a.Vn?this.F.execCommand(d):this.execCommand(d),!0}return!1};z.e.zO=function(a){if(!this.wo){a=a.target;var b=a.Sg;this.tG!=b&&(this.tG=b,QK(this,a))}};z.e.IO=function(a){this.wo?(a=this.wo,this.wo=null,a.dispatchEvent("action_completed")):QK(this,a.target)};z.e.$x=function(a){(a=a.target)&&z.Az(a)};z.v(SK,MK);
SK.prototype.QB=function(){this.ZI(this,this.Ji,this.$J)};SK.prototype.xA=function(){this.ZI(this,this.yA,this.PT)};SK.prototype.equals=function(a){return this.Vn==a.Vn&&this.Ji==a.Ji&&this.yA==a.yA};RK.prototype.isValid=function(){return this.at};RK.prototype.toString=function(){return z.eG?"W3C:"+this.Fa.toString()+"\n"+this.lB+":"+this.Da.toString()+"\n"+this.hx:"IE:"+this.Fa+","+this.Da};RK.prototype.select=function(){var a=this.Ae(this.ae.m());a&&(z.dG&&this.ae.m().focus(),z.su(a).select())};
RK.prototype.Ae=function(a){if(z.eG){var b=WJ(this.Fa,a);a=WJ(this.Da,a);return b&&a?z.bu(b,this.lB,a,this.hx).de():null}b=a.ownerDocument.body.createTextRange();b.moveToElementText(a);b.collapse(!0);b.moveEnd("character",this.Da);b.moveStart("character",this.Fa);return b};z.v(UK,z.F);z.e=UK.prototype;z.e.o=function(){return this.ea};z.e.Nx=function(){return this.ae};z.e.U=function(){return this.Cb.U()};z.e.G=function(a){this.Cb.G(a)};z.e.isEnabled=function(){return this.Cb.isEnabled()};z.e.Wa=function(a){this.Cb.Wa(a)};z.e.blur=function(){this.Cb.Zc(null)};z.e.D=function(){UK.v.D.call(this);this.ea&&(this.ea.H(),delete this.ea);this.Cb&&(this.Cb.H(),delete this.Cb);delete this.ae;delete this.tA};
z.e.VV=function(a){if(this.Cb.isEnabled()&&this.dispatchEvent("change")){var b;try{b=this.ae.queryCommandValue(a.cN||this.tA)}catch(f){b={}}a=b;for(var c in a)if(b=z.$g(this.Cb,c)){var d=a[c];b.Li?b.Li(d):b.Mc(!!d)}}};z.e.uO=function(a){var b=a.target.ee();this.ae.execCommand(b,a.target.W())};z.v(WK,z.gy);z.Yq("goog-toolbar-separator",function(){return new WK});z.v(XK,z.Xy);z.e=XK.prototype;z.e.defaults={RX:z.p};z.e.nd=z.jb("FastUpload");
z.e.enable=function(a){if(!this.isEnabled(a)&&(window.URL||window.webkitURL)&&window.FileReader&&window.FormData&&window.document.addEventListener){window.$.fn.draghover=function(){return this.each(function(){var a=(0,window.$)(),b=(0,window.$)(this),f=!0;b.on("dragenter",function(g){g=g.originalEvent;0===a.size()&&f&&z.x(g.dataTransfer.types,"Files")&&b.trigger("draghoverstart",g);a=a.add(g.target)});b.on("dragleave",function(g){(0,window.setTimeout)(function(){a=a.not(g.target);0===a.size()&&f&&
b.trigger("draghoverend",g)},1)});b.on("dragstart",function(){f=!1});b.on("drop dragend",function(){a=(0,window.$)();b.trigger("draghoverend");f=!0})})};this.oC=(0,window.$)(this.F.m());var b=this.LK=YK(this);new z.zd(this);a.m().addEventListener("paste",(0,z.q)(this.ly,this));window.document.addEventListener("dragover",(0,z.q)(this.VO,this),!1);b.on("dragover",(0,z.q)(this.UO,this));b.get(0).addEventListener("drop",(0,z.q)(this.ss,this),!1);(0,window.$)(window).draghover().on({draghoverstart:(0,z.q)(this.AF,
this),draghoverend:(0,z.q)(this.WO,this)});b.draghover().on({draghoverstart:(0,z.q)(this.OO,this),draghoverend:(0,z.q)(this.AF,this)})}};z.e.VO=function(a){z.x(a.dataTransfer.types,"Files")&&(a.dataTransfer.dropEffect="none",a.preventDefault())};z.e.UO=function(a){a=a.originalEvent;a.dataTransfer.dropEffect="copy";a.preventDefault();a.stopPropagation()};z.e.AF=function(a){a.preventDefault();a.stopPropagation();$K(this,1)};z.e.OO=function(a){$K(this,2);a.stopPropagation()};
z.e.WO=function(a){a.preventDefault();$K(this,0)};z.e.ly=function(a){var b=this;a.clipboardData&&z.x(a.clipboardData.types,"Files")&&1===a.clipboardData.items.length&&z.w(a.clipboardData.items,function(c){-1<c.type.indexOf("image")&&(aL(b,c.getAsFile()),a.preventDefault())})};
z.e.ss=function(a){var b=this;b.F.execCommand("clearlorem");var c=a.dataTransfer.files;a.preventDefault();var d=[];z.w(c,function(a){-1<a.type.indexOf("image")?(aL(b,a),d.push(!0)):d.push(!1)});z.uo(d,function(a){return!a})&&z.W.message("文件类型不支持！");$K(b,0)};var iM={};
(function(){function a(a,c,d){function t(a){z.ef(a)}function ca(b,c){for(;b!==a;){if(c(b))return b;b=b.parentNode}return null}function Xa(a){return a.tagName&&a.tagName===c}if(!a)throw"Missing Editable Container";c||(c="blockquote");c=c.toUpperCase();var cb=z.qu();if(function(b){return b&&g(a,z.zt(b))&&g(a,z.Bt(b))}(cb)){var Ha=h(cb),Ba=k(cb),yd=cb.Qb(),gi=ca(yd,Xa),oe=z.pb(Ba,function(a,b){1===b.nodeType&&(Xa(b)?a.push(b):a.push.apply(a,z.wb(b.getElementsByTagName(c))));return a},[]),Hd;if(gi){if(d)return n.zv;
z.ef(gi)}else if(oe.length){if(d)return n.zv;z.w(oe,t)}else{if(d)return n.GC;if(d=ca(yd,function(a){return z.x(m,a.tagName.toLowerCase())}))Hd=window.document.createElement(c),d.parentNode.insertBefore(Hd,d),Hd.appendChild(d);else if(cb.Y()!==cb.la())Hd=window.document.createElement(c),Ba[0].parentNode.insertBefore(Hd,Ba[0]),z.w(Ba,function(a){Hd.appendChild(a)});else return f(a,c)}b(a,Ha)}else if(d)return n.GC}function b(a,b){if(b){var c=function(b,c){return b&&g(a,b)&&z.Du(b)>=c};c(b.Y(),b.xa())&&
c(b.la(),b.La())&&b.select()}}function c(a){return a&&"BR"===a.tagName||aJ(a)||LI(a)}function d(a){a=z.vf(a,function(a){a=a.parentNode;return aJ(a)||LI(a)},!0);var b=eJ(new z.wu(a,!0,!0),z.lq(c));a=eJ(new z.wu(a,!1,!1),z.lq(c));return z.Rd(b).reverse().concat(z.Rd(a))}function f(a,b){if(t.AL)window.document.execCommand("formatBlock",!1,b);else{var c=z.qu(),f=c.vc();if(z.kf(f)&&z.Bu(f))c=window.document.createElement(b),f===a?f.appendChild(c):z.Wp(c,f),(z.B||z.y)&&c.appendChild(window.document.createElement("br")),
z.Gu(c);else if(f=c.la(),f=d(f),f.length){var c=window.document.createElement(b),g=z.lb(f),h=g.nextSibling;h&&h&&"BR"===h.tagName&&z.N(h);z.cf(c,g);z.$e(c,f);(z.B||z.y)&&c.appendChild(window.document.createElement("br"));z.Hu(c.lastChild)}}}function g(a,b){return 3===a.nodeType?a===b:a.contains(3===b.nodeType?b.parentNode:b)}function h(a){return GI(a.Y(),a.xa(),a.la(),a.La())}function k(a){function b(a){return!(a.previousSibling&&g(a.previousSibling,h))}function c(a){return f!==d&&!g(a,f)}if(a.isCollapsed())return[];
var d=a.vc(),f=a.Y(),h=a.la();a=d.childNodes;return z.Rd(1===a.length?a:eJ(fJ(a,c),b))}var m=["ul","ol","dl","table"],n={zv:1,GC:0},t=iM;t.AL=!z.A;t.toggle=a;t.getState=function(b,c){return a(b,c,!0)};t.vL=n})();z.v(bL,z.Xy);z.e=bL.prototype;z.e.nd=z.jb("Blockquote");z.e.Ge=function(a){return"+blockquote"===a};z.e.jf=function(a){this.Ge(a)&&iM.toggle(this.F.m())};z.e.queryCommandValue=function(){return iM.vL.zv===iM.getState(this.F.m())};z.e.jy=function(a){if(13===a.keyCode)return this.fy(a)};z.e.$A=function(a,b){return dL(a,b).$A};
z.e.fy=function(a){var b=z.xz(this.F);if(b.isCollapsed()){var c;a:{c=b.la();for(var d=this.F.Ha;c!==d;){if("BLOCKQUOTE"===c.tagName)break a;c=c.parentNode}c=void 0}if(c&&(b=dL(c,b),b.$A)){a.preventDefault();a=window.document.createElement("div");z.cf(a,c);if(z.B||z.y)c=c.nextSibling,(c=cL(c)&&c)||(c=window.document.createElement("br")),a.appendChild(c);z.uu(a,0).select();b.CH&&z.N(b.CH)}}};z.DH["+blockquote"]={jb:!0,V:"引用内容",Ca:"+blockquote",Pa:"tr-icon tr-blockquote",factory:z.vD};z.v(fL,z.Q);
var iL=[["ABAP","abap"],["ABNF","abnf"],["ActionScript 3","as3"],["ActionScript","as"],["Ada","ada"],["ADL","adl"],["Agda","agda"],["Alloy","alloy"],["AmbientTalk","at"],["ANTLR","antlr"],["ApacheConf","apacheconf"],["APL","apl"],["AppleScript","applescript"],["Arduino","arduino"],["AspectJ","aspectj"],["aspx-cs","aspx-cs"],["aspx-vb","aspx-vb"],["Asymptote","asy"],["autohotkey","ahk"],["AutoIt","autoit"],["Awk","awk"],["Base Makefile","basemake"],["Bash Session","console"],["Bash","bash"],["Batchfile",
"bat"],["BBCode","bbcode"],["BC","bc"],["Befunge","befunge"],["BlitzBasic","blitzbasic"],["BlitzMax","blitzmax"],["BNF","bnf"],["Boo","boo"],["Boogie","boogie"],["Brainfuck","brainfuck"],["Bro","bro"],["BUGS","bugs"],["C","c"],["C#","csharp"],["C++","cpp"],["c-objdump","c-objdump"],["ca65 assembler","ca65"],["cADL","cadl"],["CAmkES","camkes"],["CBM BASIC V2","cbmbas"],["Ceylon","ceylon"],["CFEngine3","cfengine3"],["cfstatement","cfs"],["ChaiScript","chai"],["Chapel","chapel"],["Cheetah","cheetah"],
["Cirru","cirru"],["Clay","clay"],["Clojure","clojure"],["ClojureScript","clojurescript"],["CMake","cmake"],["COBOL","cobol"],["COBOLFree","cobolfree"],["CoffeeScript","coffee-script"],["Coldfusion CFC","cfc"],["Coldfusion HTML","cfm"],["Common Lisp","common-lisp"],["Component Pascal","componentpascal"],["Coq","coq"],["cpp-objdump","cpp-objdump"],["CPSA","cpsa"],["Crmsh","crmsh"],["Croc","croc"],["Cryptol","cryptol"],["Csound Document","csound-document"],["Csound Orchestra","csound"],["Csound Score",
"csound-score"],["CSS","css"],["CUDA","cuda"],["Cypher","cypher"],["Cython","cython"],["D","d"],["d-objdump","d-objdump"],["Darcs Patch","dpatch"],["Dart","dart"],["Debian Control file","control"],["Debian Sourcelist","sourceslist"],["Delphi","delphi"],["dg","dg"],["Diff","diff"],["Django/Jinja","django"],["Docker","docker"],["DTD","dtd"],["Duel","duel"],["Dylan session","dylan-console"],["Dylan","dylan"],["DylanLID","dylan-lid"],["Earl Grey","earl-grey"],["Easytrieve","easytrieve"],["EBNF","ebnf"],
["eC","ec"],["ECL","ecl"],["Eiffel","eiffel"],["Elixir iex session","iex"],["Elixir","elixir"],["Elm","elm"],["EmacsLisp","emacs"],["Embedded Ragel","ragel-em"],["ERB","erb"],["Erlang erl session","erl"],["Erlang","erlang"],["Evoque","evoque"],["Ezhil","ezhil"],["Factor","factor"],["Fancy","fancy"],["Fantom","fan"],["Felix","felix"],["Fish","fish"],["Fortran","fortran"],["FortranFixed","fortranfixed"],["FoxPro","foxpro"],["FSharp","fsharp"],["GAP","gap"],["GAS","gas"],["Genshi Text","genshitext"],
["Genshi","genshi"],["Gettext Catalog","pot"],["Gherkin","cucumber"],["GLSL","glsl"],["Gnuplot","gnuplot"],["Go","go"],["Golo","golo"],["GoodData-CL","gooddata-cl"],["Gosu Template","gst"],["Gosu","gosu"],["Groff","groff"],["Groovy","groovy"],["Haml","haml"],["Handlebars","handlebars"],["Haskell","haskell"],["Haxe","hx"],["Hexdump","hexdump"],["HTML","html"],["HTML+Django/Jinja","html+django"],["HTML+Handlebars","html+handlebars"],["HTTP","http"],["Hxml","haxeml"],["Hy","hylang"],["Hybris","hybris"],
["IDL","idl"],["Idris","idris"],["Igor","igor"],["Inform 6 template","i6t"],["Inform 6","inform6"],["Inform 7","inform7"],["INI","ini"],["Io","io"],["Ioke","ioke"],["IRC logs","irc"],["Isabelle","isabelle"],["J","j"],["Jade","jade"],["JAGS","jags"],["Jasmin","jasmin"],["Java Server Page","jsp"],["Java","java"],["JavaScript","js"],["JCL","jcl"],["JSON","json"],["JSON-LD","jsonld"],["Julia console","jlcon"],["Julia","julia"],["Kal","kal"],["Kconfig","kconfig"],["Koka","koka"],["Kotlin","kotlin"],["Lasso",
"lasso"],["Lean","lean"],["LessCss","less"],["Lighttpd configuration file","lighty"],["Limbo","limbo"],["liquid","liquid"],["Literate Agda","lagda"],["Literate Cryptol","lcry"],["Literate Haskell","lhs"],["Literate Idris","lidr"],["LiveScript","live-script"],["LLVM","llvm"],["Logos","logos"],["Logtalk","logtalk"],["LSL","lsl"],["Lua","lua"],["Makefile","make"],["Mako","mako"],["MAQL","maql"],["Mask","mask"],["Mason","mason"],["Mathematica","mathematica"],["Matlab session","matlabsession"],["Matlab",
"matlab"],["MiniD","minid"],["Modelica","modelica"],["Modula-2","modula2"],["MoinMoin/Trac Wiki markup","trac-wiki"],["Monkey","monkey"],["MOOCode","moocode"],["MoonScript","moon"],["mozhashpreproc","mozhashpreproc"],["mozpercentpreproc","mozpercentpreproc"],["MQL","mql"],["Mscgen","mscgen"],["MSDOS Session","doscon"],["MuPAD","mupad"],["MXML","mxml"],["Myghty","myghty"],["MySQL","mysql"],["NASM","nasm"],["Nemerle","nemerle"],["nesC","nesc"],["NewLisp","newlisp"],["Newspeak","newspeak"],["Nginx configuration file",
"nginx"],["Nimrod","nimrod"],["Nit","nit"],["Nix","nixos"],["NSIS","nsis"],["NumPy","numpy"],["objdump","objdump"],["objdump-nasm","objdump-nasm"],["Objective-C","objective-c"],["Objective-C++","objective-c++"],["Objective-J","objective-j"],["OCaml","ocaml"],["Octave","octave"],["ODIN","odin"],["Ooc","ooc"],["Opa","opa"],["OpenEdge ABL","openedge"],["PacmanConf","pacmanconf"],["Pan","pan"],["ParaSail","parasail"],["Pawn","pawn"],["Perl","perl"],["Perl6","perl6"],["PHP","php"],["Pig","pig"],["Pike",
"pike"],["PkgConfig","pkgconfig"],["PL/pgSQL","plpgsql"],["PostgreSQL console (psql)","psql"],["PostgreSQL SQL dialect","postgresql"],["PostScript","postscript"],["POVRay","pov"],["PowerShell Session","ps1con"],["PowerShell","powershell"],["Praat","praat"],["Prolog","prolog"],["Properties","properties"],["Protocol Buffer","protobuf"],["Puppet","puppet"],["PyPy Log","pypylog"],["Python 3","python3"],["Python 3.0 Traceback","py3tb"],["Python console session","pycon"],["Python Traceback","pytb"],["Python",
"python"],["QBasic","qbasic"],["QML","qml"],["QVTO","qvto"],["Racket","racket"],["Ragel","ragel"],["RConsole","rconsole"],["Rd","rd"],["REBOL","rebol"],["Red","red"],["Redcode","redcode"],["reg","registry"],["ResourceBundle","resource"],["reStructuredText","rst"],["Rexx","rexx"],["RHTML","rhtml"],["Roboconf Graph","roboconf-graph"],["Roboconf Instances","roboconf-instances"],["RobotFramework","robotframework"],["RPMSpec","spec"],["RQL","rql"],["RSL","rsl"],["Ruby irb session","rbcon"],["Ruby","rb"],
["Rust","rust"],["S","splus"],["Sass","sass"],["Scala","scala"],["Scalate Server Page","ssp"],["Scaml","scaml"],["Scheme","scheme"],["Scilab","scilab"],["SCSS","scss"],["Shen","shen"],["Slim","slim"],["Smali","smali"],["Smalltalk","smalltalk"],["Smarty","smarty"],["Snobol","snobol"],["SourcePawn","sp"],["SPARQL","sparql"],["SQL","sql"],["sqlite3con","sqlite3"],["SquidConf","squidconf"],["Stan","stan"],["Standard ML","sml"],["SuperCollider","sc"],["Swift","swift"],["SWIG","swig"],["systemverilog",
"systemverilog"],["TADS 3","tads3"],["TAP","tap"],["Tcl","tcl"],["Tcsh Session","tcshcon"],["Tcsh","tcsh"],["Tea","tea"],["Termcap","termcap"],["Terminfo","terminfo"],["Terraform","terraform"],["TeX","tex"],["Text only","text"],["Thrift","thrift"],["Todotxt","todotxt"],["TrafficScript","rts"],["Treetop","treetop"],["Turtle","turtle"],["Twig","twig"],["TypeScript","ts"],["UrbiScript","urbiscript"],["Vala","vala"],["VB.net","vb.net"],["VCTreeStatus","vctreestatus"],["Velocity","velocity"],["verilog",
"verilog"],["VGL","vgl"],["vhdl","vhdl"],["VimL","vim"],["X10","x10"],["XML","xml"],["XQuery","xquery"],["XSLT","xslt"],["Xtend","xtend"],["XUL+mozpreproc","xul+mozpreproc"],["YAML","yaml"],["YAML+Jinja","yaml+jinja"],["Zephir","zephir"]],kL=z.ob(iL,gL);z.e=fL.prototype;z.e.defaults={EU:"lang-select",or:"collapsed",XQ:"lang-list",gT:"lang-option",Cg:"active",JD:"checked"};z.e.D=function(){fL.v.D.call(this);this.o().H();this.Z.H();z.N(this.h);this.as=this.Nu=this.h=null};
z.e.B=function(){var a=this.J;this.h=z.M("div",{innerHTML:this.template,className:[a.EU,a.or].join(" ")})};z.e.template='\x3cdiv class\x3d"title-button"\x3e选择语言\x3c/div\x3e\x3ci class\x3d"zg-icon zg-icon-double-arrow"\x3e\x3c/i\x3e\x3cdiv class\x3d"input-wrapper"\x3e\x3cinput class\x3d"filter-input zg-form-text-input" placeholder\x3d"搜索语言"\x3e\x3c/div\x3e';
z.e.C=function(){fL.v.C.call(this);this.Nu=z.L("title-button",this.h);this.as=z.L("filter-input",this.h);z.Ip(this.Nu,!0);lL(this,this.as,this.h);this.o().g(this.h,"click",this.Jl).g(this.Nu,"click",this.EP)};z.e.W=function(){return this.ne};z.e.Ea=function(a){var b=a&&z.rb(kL,function(b){return b.value===a});b&&(this.wk(b.label),this.dispatchEvent({type:"change",fT:b}));this.ne=a};
z.e.Jl=function(a){var b=this.Z,c=b.M.m();c&&window.document.activeElement!==this.as&&!c.contains(a.target)&&(a.preventDefault(),a.stopPropagation(),z.os(b))};z.e.EP=function(){this.isCollapsed()&&this.Bi(!1)};z.e.es=function(){return this.Z};z.e.isCollapsed=function(){return z.V.has(this.h,this.J.or)};z.e.Bi=function(a){if(this.isCollapsed()!==a){var b=this.as,c=this.J;a?z.V.add(this.h,c.or):(z.V.remove(this.h,c.or),a=this.Z,c=a.M,a.vm(kL),c.m().scrollTop=0,c.show(),b.value="",b.focus())}};
z.e.wk=function(a){var b=this.Nu;b.title=a;z.nf(b,a)};z.e.Wz=function(a){this.Ea(a.value);this.Z.Fc()};z.v(mL,z.Xy);var zL=z.B||z.vg||z.y;z.e=mL.prototype;z.e.nd=z.jb("CodePlugin");z.e.Ge=function(a){return"+code"===a};z.e.jf=function(a){this.Ge(a)&&this.trigger()};z.e.queryCommandValue=function(){var a="1"===uL(this).state,b=this.F.Sb.EnterHandler;b&&(a?b.disable(this.F):b.enable(this.F));sL(this,a);return a};z.e.defaults={uN:""};z.e.PU=function(a){this.Cb=a;this.ox=["toggleFullScreen"].concat("+code")};z.e.D=function(){mL.v.D.call(this);this.Cb=null};
z.e.trigger=function(){var a=uL(this),b=a.du,c=a.code;switch(a.state){case "1":var d=!(0,z.bb)(z.Qp(c)),a=cJ(c);d?(c.parentNode.removeChild(c),a&&z.Hu(a,!0)):(b=HI(b),d=z.Na(c.innerHTML),z.zu(z.eq(new z.wu(c,!1,!0),z.Au))&&(d="\x3cbr\x3e"+d),a&&"BR"!==a.tagName&&(d+="\x3cbr\x3e"),a=z.Xe(d),c.parentNode.replaceChild(a,c),b.restore());break;case "2":c=CL,a=(0,z.bb)(b.Kd())?rL(b.$f()):zL?"\n":"",c(this,b,a)}};
z.e.Fn=function(a,b){var c=window.document.createElement(a);c.id=z.Xg(z.Wg.aa());return b(c,function(){c=z.I(c.id);c.removeAttribute("id");return c})};z.e.Bg=function(){var a=this.F;this.bn=qL(this.F.Ha);z.Bc(a,this.bn);z.E(a,"delayedchange",this.eU,!1,this);z.E(a.Ha,"paste",this.ly,!1,this)};z.e.eU=function(){var a=this.bn&&this.bn.Qx();a&&a.U()&&a.anchor&&a.ha()};
z.e.ly=function(a){var b=uL(this),c=b.du,d=b.code;if("1"===b.state)if(b=a.jc.clipboardData)b.types&&z.x(b.types,"text/plain")&&(a.preventDefault(),b=b.getData("text/plain"),vL(c,b));else if(window.clipboardData){if(b=window.clipboardData.getData("Text"))a.preventDefault(),wL(this,c,b)}else{var f=c.xa();a=c.Kd().length;var g=(d.firstChild?z.Du(d.firstChild):0)-f-a;(0,window.setTimeout)(function(){var a=rL(d.innerHTML);z.nf(d,a);a=(d.firstChild?z.Du(d.firstChild):0)-g;d.firstChild&&z.uu(d.firstChild,
Math.max(f,a)).select()})}};z.e.jy=function(a){if(13===a.keyCode)return this.fy(a);if(40===a.keyCode)return yL(this)};z.e.fy=function(a){var b=uL(this),c=b.du;if("1"===b.state)return a.preventDefault(),z.A?BL(this,c):window.document.queryCommandSupported("insertLineBreak")?window.document.execCommand("insertLineBreak"):(a=window.document.createTextNode("\n"),c.insertNode(a),z.Hu(a)),this.F.ef(),!0};z.DH["+code"]={jb:!0,V:"插入代码",Ca:"+code",Pa:"tr-icon tr-code",factory:z.vD};z.v(EL,z.Xy);var jM=/^(DIV|TR|LI|BLOCKQUOTE|H\d|PRE|XMP)/;z.e=EL.prototype;z.e.nd=function(){return"RemoveFormatting"};z.e.Ge=function(a){return"+removeFormat"==a};z.e.jf=function(a){"+removeFormat"==a&&GL(this)};z.e.ws=function(a,b,c){return c?" "==b?(this.F.execCommand("+removeFormat"),!0):!1:!1};
z.e.RI=function(a){var b=window.document.createElement("DIV");b.innerHTML=a;a=[];for(var b=[b.childNodes,0],c=[],d=0,f=[],g=0,h=0;0<=h;h-=2){for(var k=!1;0<g&&h<=f[g-1];)g--,k=!0;k&&FL(a);for(k=!1;0<d&&h<=c[d-1];)d--,k=!0;k&&FL(a);for(var k=b[h],m=b[h+1];m<k.length;){var n=k[m++],t=n.nodeName,C=this.vF(n);if(null!=C)a.push(C);else{switch(t){case "#text":n=0<d?n.nodeValue:z.uq(n.nodeValue);n=z.Oa(n);a.push(n);continue;case "P":FL(a);FL(a);break;case "BR":FL(a);continue;case "TABLE":FL(a);f[g++]=h;
break;case "PRE":case "XMP":c[d++]=h;break;case "STYLE":case "SCRIPT":case "SELECT":continue;case "A":if(n.href&&""!=n.href){a.push("\x3ca href\x3d'");a.push(n.href);a.push("'\x3e");a.push(this.RI(n.innerHTML));a.push("\x3c/a\x3e");continue}else break;case "IMG":a.push("\x3cimg src\x3d'");a.push(n.src);a.push("'");"0"==n.border&&a.push(" border\x3d'0'");a.push("\x3e");continue;case "TD":n.previousSibling&&a.push(" ");break;case "TR":n.previousSibling&&FL(a);break;case "DIV":if(C=n.parentNode,C.firstChild==
n&&jM.test(C.tagName))break;default:jM.test(t)&&FL(a)}n=n.childNodes;0<n.length&&(b[h++]=k,b[h++]=m,k=n,m=0)}}}return a.join("").replace(/\xa0|[ \t]+/g," ")};z.e.vF=function(){return null};z.v(JL,EL);JL.prototype.vF=function(a){var b;if("IMG"!==a.nodeName)return null;b=[];b.push('\x3cimg src\x3d"');b.push(z.Oa(a.src));b.push('"');a.getAttribute("eeimg")&&a.getAttribute("alt")&&b.push(' eeimg\x3d"'+z.Oa(a.getAttribute("eeimg"))+'" alt\x3d"'+z.Oa(a.getAttribute("alt"))+'"');b.push("\x3e");return b.join("")};z.v(KL,iJ);z.v(LL,z.Mc);z.e=KL.prototype;z.e.template=(0,z.jn)('\x3cdiv class\x3d"zm-img-uploader"\x3e\x3ciframe src\x3d"about:blank" name\x3d"av_up_frame" style\x3d"position: absolute; height: 0; width: 0; left: -9000px; "\x3e\x3c/iframe\x3e\x3cdiv class\x3d"zg-section zm-img-uploader-tab"\x3e\x3ca href\x3d"javascript:;" class\x3d"tab-nav selected"\x3e上传图片\x3c/a\x3e 或 \x3ca href\x3d"javascript:;" class\x3d"tab-nav"\x3e引用站外图片\x3c/a\x3e\x3c/div\x3e\x3cform class\x3d"zg-clear" target\x3d"av_up_frame" method\x3d"POST" enctype\x3d"multipart/form-data" action\x3d"\x3c%\x3d uploadURL %\x3e"\x3e\x3cdiv class\x3d"tab-content selected \x3c% if (canStylize) { %\x3einline\x3c% } %\x3e"\x3e\x3c% if (canStylize) { %\x3e\x3cinput type\x3d"file" name\x3d"upload_file" style\x3d"opacity:0;height:0;width:0;font-size:0;position:absolute;"\x3e\x3ca href\x3d"javascript:;" class\x3d"browser zg-btn-blue"\x3e选择图片\x3c/a\x3e\x3c% } else { %\x3e\x3cinput type\x3d"file" name\x3d"upload_file"\x3e\x3c% } %\x3e\x3c/div\x3e\x3cdiv class\x3d"tab-content"\x3e\x3cinput type\x3d"text" autocomplete\x3d"off" name\x3d"upload_file_url" class\x3d"zm-editable-editor-input zg-form-text-input"\x3e\x3ca href\x3d"javascript:;" class\x3d"insert zg-btn-blue zm-uploader-button-fix"\x3e确认\x3c/a\x3e\x3c/div\x3e\x3cspan style\x3d"display: none; " class\x3d"zm-img-uploader-loading"\x3e正在上传\x3c/span\x3e\x3cspan style\x3d"display: none; " class\x3d"zm-img-uploader-error"\x3e上传图片失败，请稍后重试\x3c/span\x3e\x3c/form\x3e\x3cdiv class\x3d"zg-gray"\x3e请不要上传与回答问题无关的图片，详细请看 \x3ca href\x3d"/question/20064580" target\x3d"_blank"\x3e知乎图片使用规范\x3c/a\x3e\x3c/div\x3e\x3cdiv class\x3d"zm-command"\x3e\x3ca class\x3d"cancel" href\x3d"javascript:;"\x3e取消\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e');
z.e.Gw=function(){var a=z.Xe(this.template({uploadURL:this.UB,canStylize:this.MM}));z.Eb({form:"form",uB:".zm-img-uploader-tab",dh:".zm-img-uploader-loading",hf:".zm-img-uploader-error",LJ:"input[type\x3dtext]",Wn:"input[type\x3dfile]",wD:".browser",qw:".cancel",uQ:".insert"},function(b,d){this[d]=(0,window.$)(b,a).get(0)},this);this.S.g(z.X,"iframe_data",this.Nv).g(this.Wn,"change",this.yT).g(this.uQ,"click",this.vQ).g(this.qw,"click",function(){this.lo();this.hide()}).g(this.uB,"click",function(a){a=
(0,window.$)(a.target);a.is("a")&&!a.is(".selected")&&ML(this,a.index())});this.XD=a;z.Tm||(ML(this,1),(0,window.$)(this.uB).replaceWith("\x3cstrong\x3e输入站外图片地址：\x3c/strong\x3e"));this.wD&&this.S.g(this.wD,"click",function(){this.Wn.click()});var b=new jJ(this);b.Na("插入图片").ka(this.XD);b=mJ(b);z.Fj(b,null);return b};z.e.yT=function(){this.Wn.value&&(dJ(this.Wn.value)?(this.LJ.value="",z.P(this.dh,!0),z.P(this.hf,!1),this.form.submit()):NL(this,"图片不是 .jpg 或 .png 格式无法上传"))};
z.e.vQ=function(){var a=z.Ao(this.LJ.value);a?z.Ka(a,"http://")?(this.Wn.value="",z.P(this.dh,!0),z.P(this.hf,!1),this.form.submit()):NL(this,"我们目前不支持该协议。"):NL(this,"请填写图片地址。")};z.e.Nv=function(a){z.P(this.dh,!1);this.Fm(a.zf)};z.e.Fm=function(a){a&&!a.r?(this.dispatchEvent(this.Hn(a.msg)),this.hide()):NL(this,a.msg)};z.e.Hn=function(a){return new LL(a)};z.e.D=function(){this.S.H();this.S=null;KL.v.D.call(this)};z.v(OL,nJ);z.e=OL.prototype;z.e.nd=z.jb("ImageDialogPlugin");
z.e.jf=function(a,b){var c=this.F;return c.wf||(c.Wf(),c.wf)?OL.v.jf.call(this,a,b):!1};z.e.Cj=function(a){if(a&&"mouseup"===a.type){var b=a.target;b&&"IMG"===b.nodeName&&(a=cJ(b),a||(a=window.document.createElement("br"),z.cf(a,b)),z.Gu(a))}};z.e.jo=function(a){OL.v.jo.call(this,a)};z.e.Fw=function(a){a=new KL(a);this.S.g(a,"ok",this.po).g(a,"cancel",this.ay);return a};z.e.D=function(){OL.v.D.call(this);this.S.H()};
z.e.po=function(a){oJ(this);var b=EI(this),c;c=a.nI?b.B("IMG",{"class":"origin_image zh-lightbox-thumb","data-original":a.nI,title:"点击查看原图",src:a.Vl}):b.B("IMG",{"class":"content_image",src:a.Vl});a.JI&&c.setAttribute("data-rawwidth",a.JI);a.II&&c.setAttribute("data-rawheight",a.II);a=z.xz(this.F);if(WI(a))a.mg(c),z.A||(z.Hu(c,!1),b.Va().focus()),z.yz(this.F),this.F.ef();else return null;this.S.removeAll()};z.e.ay=function(){this.S.removeAll()};z.v(PL,iJ);z.v(QL,z.Mc);z.e=PL.prototype;z.e.show=function(){PL.v.show.call(this);this.Yu.focus()};z.e.hide=function(){PL.v.hide.call(this)};
z.e.Gw=function(){var a=z.pm.Wu+"/upload_video",a=this.ld.B("div","zm-img-uploader zm-img-uploader-upload-tab-selected",[this.ld.B("div","zg-section",this.ld.B("strong",null,"输入视频页地址：")),this.ld.B("iframe",{id:"video_up_frame",src:"about:_blank",name:"video_up_frame",style:"visible:hidden;position:absolute;height:0;width:0;left:-9000px"}),this.gF=this.ld.B("form",{"class":"zg-section-title",target:"video_up_frame",method:"post",enctype:"multipart/form-data",action:a},[this.Yu=this.ld.B("input",{type:"text",
"class":"zg-form-text-input",name:"upload_file_url",autocomplete:"off"}),this.Dn=this.ld.B("a",{"class":"zg-btn-blue zm-uploader-button-fix",name:"save",href:"javascript:;"},"确定"),this.ld.B("div","zm-video-uploader-info",[this.dh=this.ld.B("span",{style:"display:none","class":"zm-img-uploader-loading"},"正在上传"),this.hf=this.ld.B("span",{style:"display:none","class":"zm-img-uploader-error"},"插入视频失败，请稍后重试")])]),this.fQ=this.ld.B("div","zg-gray"),this.Bn=this.ld.B("div","zm-command",[this.qw=this.ld.B("a",
{href:"javascript:;"},"取消")])]);this.fQ.innerHTML='我们目前支持\x3ca class\x3d"zg-link-gray" target\x3d"_blank" href\x3d"http://youku.com"\x3e优酷\x3c/a\x3e、\x3ca class\x3d"zg-link-gray" target\x3d"_blank" href\x3d"http://tudou.com"\x3e土豆\x3c/a\x3e、\x3ca href\x3d"http://video.sina.com.cn/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e新浪\x3c/a\x3e、\x3ca href\x3d"http://v.qq.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e腾讯\x3c/a\x3e、\x3ca href\x3d"http://www.56.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e56\x3c/a\x3e、\x3ca href\x3d"http://tv.sohu.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e搜狐\x3c/a\x3e、\x3ca href\x3d"http://www.iqiyi.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e爱奇艺\x3c/a\x3e视频服务。\x3cbr /\x3e请不要上传与回答问题无关的视频，详细请看 \x3ca href\x3d"http://www.zhihu.com/question/20118966" target\x3d"_blank"\x3e知乎视频使用规范\x3c/a\x3e';
this.S.g(this.qw,"click",function(){this.lo();this.hide()}).g(this.Dn,"click",this.vI).g(this.Bn,"click",this.Qa).g(this.gF,"submit",function(){return RL(this,this.Yu.value)}).g(z.X,"iframe_data",this.Nv);this.XD=a;var b=new jJ(this);b.Na("插入视频").ka(a);a=mJ(b);z.Fj(a,null);return a};z.e.vI=function(){if(this.Yu.value){var a=z.Ao(this.Yu.value);a&&RL(this,a)&&(z.P(this.dh,!0),z.P(this.hf,!1),this.gF.submit())}};z.e.Qa=function(a){"save"===(a.target&&a.target.name)&&this.vI()};
z.e.Nv=function(a){z.P(this.dh,!1);this.Fm(a.zf)};z.e.Fm=function(a){a&&!a.r?(this.dispatchEvent(this.Hn(a.msg[0],a.msg[1],a.msg[2],a.msg[3],a.msg[4])),this.hide()):(a=a.msg,z.P(this.dh,!1),this.hf.innerHTML=a,z.P(this.hf,!0))};z.e.Hn=function(a,b,c,d,f){return new QL(a,b,c,d,f)};z.e.D=function(){this.S.H();this.S=null;PL.v.D.call(this)};z.v(SL,nJ);z.e=SL.prototype;z.e.nd=z.jb("VideoDialogPlugin");z.e.jf=function(a,b){var c=this.F;return c.wf||(c.Wf(),c.wf)?SL.v.jf.call(this,a,b):!1};
z.e.jo=function(a){SL.v.jo.call(this,a)};z.e.Fw=function(a){a=new PL(a);this.S.g(a,"ok",this.po).g(a,"cancel",this.ay);return a};z.e.D=function(){SL.v.D.call(this);this.S.H()};
z.e.po=function(a){oJ(this);var b=EI(this),c=b.B("a",{"class":"video-link",href:a.eV,"data-src":a.dW,"data-name":a.qK,"data-poster":a.poster,"data-videoid":a.cW});z.nf(c,a.qK);a=z.Rp(c);a=z.Xe(a+" ");var c=a.firstChild,d=z.xz(this.F);if(WI(d))d.mg(a),z.A?window.document.selection&&(b=window.document.selection.createRange(),b.move("character",-1),b.select()):(z.Hu(c),b.Va().focus()),z.yz(this.F),this.F.ef();else return null;this.S.removeAll()};z.e.ay=function(){this.S.removeAll()};z.az=!0;(function(a){z.Xy.prototype.execCommand=function(b){var c=this.F;return z.so(YL,b)&&!c.wf?(c.Wf(),!1):a.apply(this,arguments)}})(z.Xy.prototype.execCommand);(function(a,b){nJ.prototype.execCommand=function(c){var d=this.F;return!z.x(b,c)||d.wf||(d.Wf(),d.wf)?a.apply(this,arguments):!1}})(nJ.prototype.execCommand,["+equation"]);TL="video";XL=z.Vc?"⌘":"ctrl";z.DH[TL]={Ca:TL,V:"插入视频",Pa:"tr-icon tr-video",factory:z.tD};z.DH["+equation"]={Ca:"+equation",V:{}.UW,Pa:"tr-icon tr-equation",factory:z.tD};
z.DH["+bold"].V="粗体 ("+XL+"+b)";z.DH["+italic"].V="斜体 ("+XL+"+i)";z.DH["+underline"].V="下划线 ("+XL+"+u)";z.DH["+superscript"].V="引用内容";z.DH["+insertOrderedList"].V="有序列表";z.DH["+insertUnorderedList"].V="无序列表";z.DH["+removeFormat"].V="清除格式";z.DH.image.V="插入图片";z.DH[TL].V="插入视频";z.DH["+equation"].V="插入公式";z.la(UL);
UL.prototype.bf=function(a,b){this.config=b;var c,d,f;d=z.L("zm-editable-toolbar-container",a);c=z.L("zm-editable-editor-outer",a);f=z.L("zm-editable-editor-field-element",a);var g=new z.Fz(f.id);g.BM=89;var h=VL(d,b);new UK(g,h);z.Bc(g,h);CI(g,new wJ);CI(g,new JK);if(b.loremIpsum_&&(CI(g,new LK(b.loremIpsum_)),z.y))g.on("load",function(){z.md(g.m(),"focus",function(){g.execCommand("clearlorem",!0)})});CI(g,new XJ);CI(g,new JL);CI(g,new PK);d=new mL;CI(g,d);CI(g,new OL);CI(g,new SL);CI(g,new XK);
CI(g,new HK);CI(g,new oK);CI(g,new bL);b.enableFullScreen&&(c=new z.DD({title:"写作模式",Ek:c}),CI(g,c));g.on("load",function(){b.useScraper_&&WL(g,h)},!1,this);return[g,h]};z.Fa("ZH.createRichTextEditor",function(a,b){return UL.aa().bf(a,b)});z.kg("richtexteditor");}).call(this, __z_z__);
//# sourceURL=/static/revved/-/js/closure/richtexteditor.3011a22d.js