(function(z){
var kM=function(a){a.ji=!1;a.status=0;z.BF(a)};var lM=function(a){a.Wy=!0;a.hE=z.Io(a.m()).height;z.xG+=a.hE;z.w(z.Mu,function(a){a&&!a.Wy&&a.wl&&a.xp()})};var mM=function(a){var b={};z.w(a.data.md(),function(a){b[a]=this.data.get(a)},a);return b};var nM=function(){this.sB="";this.uL=oM};var pM=function(){this.pk="";this.jL=qM};var rM=function(a){return a instanceof nM&&a.constructor===nM&&a.uL===oM?a.sB:"type_error:Const"};var sM=function(){this.BI="";this.xL=tM};
var uM=function(a){function b(a){if(z.na(a))z.w(a,b);else{if(!(a instanceof z.Fd)){var g=null;a.By&&(g=a.Dl());a=z.Jd(z.Oa(a.Fj?a.Qg():String(a)),g)}d+=z.Id(a);a=a.Dl();0==c?c=a:0!=a&&c!=a&&(c=null)}}var c=0,d="";z.w(arguments,b);return z.Jd(d,c)};var vM=function(a,b){b.all=!0;return z.mo(a,b)};var wM=function(){z.it.call(this,null,null,"搜索话题");this.Ee="";this.data=[z.jm[0]]};var xM=function(a,b){return window.$.post("/question/askpeople",{qid:a,uid:b,op:"remove"})};
var yM=function(a){return 1===a?!0:z.na(a)?a[3]===z.S[3]:!1};
var zM=function(a){if(!AM.test("input"))throw Error("Invalid tag name \x3cinput\x3e.");if("INPUT"in BM)throw Error("Tag name \x3cinput\x3e is not allowed for SafeHtml.");var b=null,c="\x3cinput";if(a)for(var d in a){if(!AM.test(d))throw Error('Invalid attribute name "'+d+'".');var f=a[d];if(null!=f){var g;g=d;if(f instanceof nM)f=rM(f);else if("style"==g.toLowerCase()){if(!z.ta(f))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof f+" given: "+f);
if(!(f instanceof z.Dd)){var h="",k=void 0;for(k in f){if(!/^[-_a-zA-Z0-9]+$/.test(k))throw Error("Name allows only [-_a-zA-Z0-9], got: "+k);var m=f[k];if(null!=m){if(m instanceof nM)m=rM(m);else if(CM.test(m)){for(var n=!0,t=!0,C=0;C<m.length;C++){var J=m.charAt(C);"'"==J&&t?n=!n:'"'==J&&n&&(t=!t)}n&&t||(m="zClosurez")}else m="zClosurez";h+=k+":"+m+";"}}f=h?(new z.Dd).yo(h):z.Ml}f=f instanceof z.Dd&&f.constructor===z.Dd&&f.iL===z.Ed?f.rA:"type_error:SafeStyle"}else{if(/^on/i.test(g))throw Error('Attribute "'+
g+'" requires goog.string.Const value, "'+f+'" given.');if(g.toLowerCase()in DM)if(f instanceof sM)f=f instanceof sM&&f.constructor===sM&&f.xL===tM?f.BI:"type_error:TrustedResourceUrl";else if(f instanceof pM)f=f instanceof pM&&f.constructor===pM&&f.jL===qM?f.pk:"type_error:SafeUrl";else if(z.pa(f))f instanceof pM||(f=f.Fj?f.Qg():String(f),EM.test(f)||(f="about:invalid#zClosurez"),h=new pM,h.pk=f,f=h),f=f.Qg();else throw Error('Attribute "'+g+'" on tag "input" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+
f+'" given.');}f.Fj&&(f=f.Qg());g=g+'\x3d"'+z.Oa(String(f))+'"';c+=" "+g}}d=void 0;null!=d?z.na(d)||(d=[d]):d=[];!0===FM.input?c+="\x3e":(b=uM(d),c+="\x3e"+z.Id(b)+"\x3c/input\x3e",b=b.Dl());(a=a&&a.dir)&&(b=/^(ltr|rtl|auto)$/i.test(a)?0:null);return z.Jd(c,b)};var GM=function(a,b){var c=z.sb(a,b,void 0);return 0<=c?(Array.prototype.splice.call(a,c,1),!0):!1};var HM=function(){z.Q.call(this);this.xf="zm-pm-item"};
var IM=function(a){if(a.lb().length){var b=new z.zl;b.use("locationSource",{param:function(a){return{start:a[a.length-1].getAttribute("data-token")}}});b.w(a.ot)}};var JM=function(a,b){z.W.confirm("删除私信","你确定要删除这封私信吗？",function(a){a&&KM(this,b)},a)};var KM=function(a,b){var c=new z.Z(!0);a.o().Aa(c,"success",function(){var a=z.Zn(c);a.r?z.W.message(a.msg):window.location.reload()});c.ajax("/inbox/delete","type\x3dsingle\x26token\x3d"+b)};var LM=function(){z.Q.call(this);this.xf="zm-pm-item"};
var MM=function(a){var b=new z.Z(!0);b.on("success",function(){var a=z.Zn(b);a.r?z.W.message(a.msg):window.location.reload()});b.ajax("/inbox/delete","type\x3dthread\x26token\x3d"+a)};var NM=function(a,b,c,d,f){z.aC.call(this,a,b,f);this.Ax=c||"people";this.aO=d||["zg-follow","zg-unfollow"]};var OM=function(a,b,c,d){z.F.call(this);this.h=a;this.Ax=b||"people";this.$N=c||["zg-btn-follow","zg-btn-unfollow"];this.text=d||["关注","取消关注"]};var PM=function(a){z.F.call(this);this.url=a||"/topic"};
var QM=function(a,b,c){var d=c[0],f="";"topic"!==d[0]&&d[3]&&(f='data-parent\x3d"'+d[3]+'"');b.html('\x3ca href\x3d"'+("topic"===d[0]?"/topic/"+d[2]+"/organize/entire":"javascript:;")+'" data-token\x3d"'+d[2]+'" '+f+' name\x3d"'+d[0]+'"\x3e'+d[1]+"\x3c/a\x3e\x3cul class\x3d'zm-topic-organize-list'\x3e\x3c/ul\x3e");"topic"!==c[0][0]&&b.addClass("zm-topic-organize-loadmore");b=(0,window.$)("ul",(0,window.$)(b));if(1<c.length)for(c=c[1],d=0;d<c.length;d++){var f=c[d],g=(0,window.$)("\x3cli\x3e").addClass("zm-topic-organize-item");
b.append(g);QM(a,g,f)}};var RM=function(a,b,c){z.mv.call(this,a,b,c)};var SM=function(){z.Q.call(this);var a=z.jm;this.Ff=a[0][3];this.Hi=a[0];this.cw=a[4];this.Yy=a[5];this.hh="topic"};
var TM=function(){(0,window.$)(".zm-topic-list-container").on("click",".js-questionUnhelpful",function(a){a=(0,window.$)(a.currentTarget);var b=a.data("qid"),c=a.data("isRevert");if(b)return c?(a.text("没有帮助").data("isRevert",!1),window.$.post("/question/revert-unhelpful",{qid:b})):(a.text("撤销没有帮助").data("isRevert",!0),window.$.post("/question/unhelpful",{qid:b})),!1})};
var UM=function(){var a=z.I("zh-topic-log-list");a&&((new NM(a,null,null,null,!0)).init(),(0,window.$)(a).on("click",'a[name\x3d"revert"]',z.Vo(function(a){!1!==a&&z.pC(this)},z.tC({jq:!0}))))};var VM=function(a){if(z.I("zh-topic-admin-page-wrap")){var b=z.I("zh-topic-del-btn");b&&a.o().g(b,"click",a.$R)}};var WM=function(a,b){var c=z.Me(window.document,"li",null,a.Pv);z.w(c,function(a){a.getAttribute("data-token")===b[1]&&z.P(a,!1)})};
var XM=function(a){var b=z.I("zh-topic-followers-list-wrap");b&&(a=new NM(b,["/topic",(0,window.encodeURI)(a.Hi[1]),"followers"].join("/"),null,["zg-btn-follow","zg-btn-unfollow"],!0),a.Ci("zm-person-item"),a.init())};
var YM=function(a){var b=z.I("zh-topic-side-head");if(b){var c=z.L("zu-entry-focus-button",b);c&&a.o().g(c,"click",function(){(0,z.qB)(c,"topic","",["zg-btn-green","zg-btn-white"])});a.ig=z.I("zh-topic-operation-menu");a.ig&&a.o().g(a.ig,"click",a.bB)}if(b=z.I("zh-current-topic-bio")){var d=new z.mv(!0,"/topic/bio/update","bio");z.nv(d,["tid\x3d"+a.Ff]);d.Wb='\x3ca href\x3d"javascript:;" name\x3d"edit"\x3e你在 '+a.Hi[0]+" 话题中的经验\x3c/a\x3e";d.vE=!0;d.w(b)}};var ZM=function(a){z.$e(a,z.Xe('\x3ca href\x3d"/question/23261456" class\x3d"zg-link-gray-normal"\x3e\x3ci class\x3d"icon-info" style\x3d"vertical-align: -3px; margin-right: 6px"\x3e\x3c/i\x3e如何参与知乎话题的公共编辑？\x3c/a\x3e'))};
var $M=function(a){if(z.I("zh-topic-organize-page-wrap")){var b=z.I("zh-topic-organize-parent-editor");if(b)if(z.S.Fs){var c=new z.qt(null,a.Ff,!0);c.Ct=!0;c.w(b);c.addEventListener("remove_tag",function(a){(a=a.data&&a.data.id)&&(0,window.$)("#wedge-"+a).remove()})}else ZM(b);if(b=z.I("zh-topic-organize-child-editor"))z.S.Fs?(c=new z.qt(null,a.Ff,!1),c.Ct=!0,c.w(b),(0,window.$)("a.entire-link").insertAfter(c.Qn).show()):ZM(b);(0,window.$)("#zm-topic-manage-relation").on("change",'[type\x3d"checkbox"]',
function(){var a=(0,window.$)(this).closest("li").attr("id").split("-")[1];window.$.post("/topic/update",{action:"set_topic_edge",parent_topic_id:a,topic_id:z.jm[0][3],edge:this.checked^0}).done(function(a){if(!a)return z.W.message("网络异常");if(a.r)return z.W.message(a.msg)})});a.Ov=z.I("zh-topic-alias-input");new z.qk(a.Ov,"输入话题别名");a.Pv=z.I("zh-topic-alias-list");a.o().g(z.I("zh-topic-alias-container"),"click",a.PS);if(b=z.I("zh-topic-merge"))a.Oa=new wM,a.Oa.w(b);(b=z.I("zh-topic-merge-btn"))&&a.o().g(b,
"click",a.mS)}};var aN=function(){var a=z.I("zh-topic-organize-page-children");a&&(new PM("/topic/"+(0,window.encodeURIComponent)(z.jm[0][1])+"/organize/entire")).w(a)};var bN=function(a){var b=z.I("zh-topic-side-related-topics");b&&(a.TT=b,a.zA=new z.Z(!1),a.o().g(a.zA,"complete",a.wS),a.zA.ajax("/topic/related?tid\x3d"+a.Ff))};
var cN=function(a){if(z.S.oX)(0,window.$)("div.topic-avatar").addClass("disabled");else{var b=z.L("zm-entry-head-avatar-edit-button");if(b){var c=new z.SB(2,z.jm[0][3]);c.w(b);var d=z.L("zm-avatar-editor-preview");z.E(c,"beforepost",function(){(0,window.$)("\x3cdiv class\x3d'avatar-edit-preview-loading topic'\x3e\x3cspan\x3e\x3c/span\x3e\x3c/div\x3e").appendTo(d.parentNode)});z.E(c,"success",function(){window.$.post("/topic/"+z.jm[0][1]+"/avatar",{avatar_path:c.getData().url}).then(function(a){if(!a)return z.W.message("网络异常");
if(a.r)return z.W.message(a.msg);d&&(d.src=c.getData().url)}).always(function(){(0,window.$)(".avatar-edit-preview-loading").remove()})});a.o().g(c,"beforeopen",z.Vo(z.tC({jq:!0}),z.Or(z.p,!0)))}}};var dN=function(a){eN(a);fN(a);a.fh&&a.o().g(a.fh,"afterload",function(b){z.X.fb({type:"ga_click_topic_more",data:b.data,target:a.fh.Nd})})};
var eN=function(a){var b=z.I("zh-topic-feed-list");if(b){var c=new z.zl;a.K(c);c.use("locationSource",{lt:0,offset:function(a){return z.lb(a).getAttribute("data-score")}});c.use("childConstructor",{factory:z.LF}).use("expandLimit");c.w(b);a.o().g(c,"click!",function(a){"comment"===a.namespace&&a.Ac.fill("category",this.hh).fill("label","topic_activity")})}};
var fN=function(a){var b=z.I("zh-topic-top-page-list");if(b){var c=new z.zl({pg:!1});a.K(c);c.use("childConstructor",{factory:z.LF}).use("expandLimit");c.w(b);a.o().g(c,"click!",function(a){"comment"===a.namespace&&a.Ac.fill("category",this.hh).fill("label","topic_activity")})}};
var gN=function(){function a(a){if(!a)return z.W.message("网络异常");if(a.r)return z.W.message(a.msg)}(0,window.$)("#zh-topic-manage-relation-form").on("change",'input[type\x3d"radio"]',function(){window.$.post("/topic/update",{action:"set_topic_weaknode",topic_id:z.jm[0][3],weak:(0,window.$)(this).val()}).done(a)});(0,window.$)("#zh-topic-manage-lock-form").on("change",'[type\x3d"checkbox"]',function(){window.$.post("/topic/lock",{url_token:z.jm[0][1],lock_type:this.name,lock_value:(0,window.$)(this).is(":checked")?
1:0}).done(a)})};var hN=function(a){var b=(0,window.$)(".topic-info a[name\x3dshare]"),c=b.get(0),d=window.location.href,f={hot:[/\/topic\/\d+$/,/\/topic\/\d+\/newest/],top_answers:[/\/topic\/\d+\/top-answers/],unanswered:[/\/topic\/\d+\/unanswered/,/\/topic\/\d+\/questions/]},g=Object.keys(f).find(function(a){return f[a].some(function(a){return a.test(window.location.pathname)})})||"";c&&(z.fB(c,"topic",a.Hi[1],d).Ob(a),b.click(function(){z.T("share","click_share_topic_page",g)}))};
var iN=function(a){z.Q.call(this,a)};var jN=function(a,b,c){var d,f,g=[];for(d in c)f=c[d],z.oa(f)?z.w(f,(0,z.q)(function(a){g.push(zM({type:"hidden",name:d,value:String(a)}))},a)):g.push(zM({type:"hidden",name:d,value:String(f)}));z.Ge(b,uM(g))};var kN=function(a){return window.$.get("/node/ExploreAnswerListV2",{params:JSON.stringify({offset:a,type:"day"})})};var lN=function(a){return window.$.get("/node/ExploreHotFavlistsInnerV2",{params:JSON.stringify({offset:a})})};
var mN=function(a){return window.$.get("/node/ExploreAnswerListV2",{params:JSON.stringify({offset:a,type:"month"})})};var nN=function(){z.F.call(this)};var oN=function(){z.Q.call(this);var a=z.lh||[0,0];this.kt=a[0];this.visible=!!a[1];this.hh="collection"};
var pN=function(a){var b=z.I("zh-list-answer-wrap");if(b){(0,window.$)(b).on("click","a[name\x3dunfavo]",window.$.proxy(a.IP,a));var c=new z.zl({pg:!1});a.K(c);c.use("childConstructor",{Uh:z.FF}).use("expandLimit");c.w(b);a.o().g(c,"click!",function(a){"comment"===a.namespace&&a.Ac.fill("category",this.hh).fill("label","collection_answer")})}};
var qN=function(){var a=z.I("zh-favlist-following-wrap");a&&((new NM(a,null,"favlist",null,!0)).init(),(0,window.$)(a).on("click","a.zg-unfollow",function(a){"/collections"===window.location.pathname&&(a=(0,window.$)(a.target).attr("href"),/\/collection\/\d+\/followers/.test(a)?z.wi({category:"collection",action:"visit_collection_followers",label:"collections_my_followed_collections_collection_followers_count"}):z.wi({category:"collection",action:"click_unfollow_collection",label:"collections_my_followed_collections_unfollow_collection"}))}).on("click",
".zm-item-title \x3e a",function(){var a=window.location.pathname;"/collections"===a?z.wi({category:"collection",action:"visit_collection",label:"collections_my_followed_collections_collection"}):"/collections/mine"===a&&z.wi({category:"collection",action:"visit_collection",label:"collections_my_collection"})}))};
var rN=function(a){var b=z.I("zh-list-side-head");if(b){var c=z.L("zu-entry-focus-button",b);c&&a.o().g(c,"click",function(){(0,z.qB)(c,"favlist","",["zg-btn-green","zg-btn-white"])});a.ig=z.I("zh-list-operation-menu");a.ig&&a.o().g(a.ig,"click",a.bB)}(b=z.I("zh-single-answer-author-info"))&&(new OM(b)).init();(b=z.I("zh-list-create-new-list"))&&a.o().g(b,"click",a.YU);(b=z.I("zh-fav-list-side-bar-creator"))&&(new OM(b)).init();(0,window.$)("#zh-fav-list-side-bar-report").on("click",function(){(new z.Oz({type:"favlist",
id:a.kt})).render()})};var sN=function(a){z.W.confirm("删除收藏夹","你确定要删除这个收藏夹吗？",function(a){a&&(a=new z.fp,a.add("favlist_id",this.kt),a.add("_xsrf",(new z.Ri(window.document)).get("_xsrf")),(new iN).post(mM(a),"/collection/delete"))},a)};
var tN=function(a){a.va||(a.va=new z.hA(a.kt,"favlist"),a.K(a.va),a.o().g(a.va,"click!",function(a){"comment"===a.namespace&&(a.Ac.fill("category",this.hh).fill("label","collection"),a.Ac.action=a.Ac.action.replace("favlist","collection"))}),z.lA(a.va,a.Mb,(0,window.$)(".toggle-comment",a.Mb)[0]))};var uN=function(a){a.fK=new z.Z(!0);a.o().g(a.fK,"complete",function(){window.location.reload()});a.fK.ajax("/collection/update","favlist_id\x3d"+a.kt+"\x26is_public\x3d1")};
var vN=function(a,b){z.F.call(this);this.pa=a;this.Gb=b;this.data=z.R};var wN=function(a){a.Mt&&a.Mt.ka(a.data.mb?"撤消匿名身份":"使用匿名身份")};var xN=function(a,b){return a?b?new z.VD(a):new z.ey(a):new z.iy};var yN=function(a){a.rk.innerHTML="";z.P(a.rk,!1);a.Ko=!1;a.mm.Gp("问题重定向");z.xq("/question/unredirect",null,"POST","qid\x3d"+a.pa+"\x26rqid\x3d"+a.pu)};var zN=function(a,b){z.Q.call(this);this.KT=a;this.dD=b};var AN=function(a,b,c,d,f){z.sv.call(this,d,b,c);this.pa=a;this.Zy=this.zp=!1;this.eT=f};
var BN=function(a,b){a.Zy=b};var CN=function(){var a=z.M("select",{style:"1px solid #999 "}),b=z.M("option",{value:"none"},"请选择一个修改理由...");a.appendChild(b);z.w(DN,function(b,d){var f=z.M("option",{value:b.value},d+1+". "+b.label);a.appendChild(f)});return a};var EN=function(a,b,c){a.rH.innerHTML=b;z.V.set(a.rH,c||"zg-error-text")};var FN=function(){z.Q.call(this)};var GN=function(){z.U.call(this);this.Cf(!0);this.G(!0)};
var HN=function(a,b){a.Na("提问无人问津？");a.ka(b);a.ha();(0,window.$)(".js-gonext",a.h).on("click",function(){var b=(0,window.$)(this).parents('[class^\x3d"view"]').attr("class");"view-starting"===b?(a.Na("第一条"),IN(a,"firsttip")):"view-firsttip"===b?(a.Na("第二条"),IN(a,"secondtip")):"view-secondtip"===b?(a.Na("第三条"),IN(a,"thirdtip")):"view-thirdtip"===b&&a.G(!1)})};var JN=function(a,b){a.Na("邀请回答小窍门");a.ka(b);a.ha();(0,window.$)(".js-close",a.h).on("click",function(){a.G(!1)})};
var IN=function(a,b){(0,window.$)('[class^\x3d"view"]',a.h).hide();(0,window.$)(".view-"+b,a.h).show()};var KN=function(a,b){z.Q.call(this);this.JT=a;this.mp=b;this.Z=null;this.Jb=!1;this.Wl=null;this.Pj=[];this.xc=!1;this.dR="loading";this.yG="zg-btn-white"};var LN=function(a){var b=a.dR;a.X.addClass(b).html(MN);window.$.get("/node/QuestionInvitePanelV2",{params:{question_id:a.JT}}).done(function(c){a.xc=!0;a.X.removeClass(b);c=(0,window.$)(c);a.X.replaceWith(c);a.h=c[0];c.toggle(a.wc());a.X=c;NN(a)})};
var NN=function(a){var b=a.m();a.o().g(z.Hq,"anon_change",a.MR);(0,window.$)(".cancel-anon",b).click(window.$.proxy(a.BO,a));if(!(0,window.$)(".error-message",b).length){var c=z.L("search-input",b),d=z.L("invite-title",b);a.Ey(c,d);a.uv=(0,window.$)(".suggest-persons",b);a.uv.on("click","button",window.$.proxy(a.EF,a));(0,window.$)(".js-more",b).one("click",function(){(0,window.$)(".person",this.uv).show();(0,window.$)(this).remove()});a.Bq=(0,window.$)(".invite-status",b);a.Bq.on("click","button",
window.$.proxy(a.CO,a)).on("mouseenter mouseleave",".invited-shortlist",function(a){(0,window.$)(".invited-hovercard",this).toggleClass("in","mouseenter"===a.type)});ON(a)}};var PN=function(a,b){var c=z.R;a.dispatchEvent(new z.Iz("click!invitation",{category:"invitation",action:"ask_to_answer",label:b,value:c.FG?null:c.ve}))};var QN=function(a,b){return!!z.rb(a.Pj,function(a){return a.id===b})};
var RN=function(a,b,c){var d=(0,window.$)(".invite-button",a.uv).filter(function(){return this.getAttribute("data-uid")===b}).get(0);d&&SN(a,d,c)};var SN=function(a,b,c){a=a.yG;c?(z.V.add(b,a),z.nf(b,"收回邀请")):(z.V.remove(b,a),z.nf(b,"邀请回答"))};var ON=function(a){a.Pj=window.$.map((0,window.$)(".invited-fulllist",a.Bq).children(),a.tI)};var TN=function(a,b){a.Pj&&GM(a.Pj,function(a){return a.id===b})&&UN(a)};
var UN=function(a){var b=a.Pj,c={each:z.w,fullList:function(){return(0,z.jn)(VN,{persons:b,helper:c})}};b.length?a.Bq.html((0,z.jn)(WN,{persons:b,helper:c,maxInvites:15})):a.Bq.html("你可以通过邀请其他用户来更快获得回答")};var XN=function(a){z.Q.call(this);this.data=a;this.va=null};var YN=function(a){var b=z.L("panel-container",a.h);b&&(a.em=new FN,a.K(a.em),a.em.w(b),a.va=new z.hA(a.data.pa,"question"),a.em.K(a.va),z.lA(a.va,a.em.m(),(0,window.$)(".toggle-comment",a.h)[0]),a.Kj(),a.Lj(),ZN(a))};
var ZN=function(a){if("normal"===z.R.status){var b=new KN(a.data.pa,a.data.Za);b.render(a.em.m());var c=(0,window.$)('a[name\x3d"invite"]',a.m());a.o().g(b,["expand","collapse"],function(a){c.text("expand"===a.type?"收起邀请":"邀请回答")});a.em.K(b);z.R.aV&&(b.Nc(!0),a.dispatchEvent(new z.Iz("show!invitation",{category:"invitation",action:"ask_to_answer_card",label:""})));a.Ty=b}};
var $N=function(a,b){var c=a.ML;c||(c=new z.YD,c.w(z.I("zh-question-admin-menu")),z.ch(c,function(a){a.Ea(a.m().getAttribute("data-action"))}),a.o().g(c,"action",function(a){a=this.NC=a.target;(new z.Lz).open(a.m(),{id:this.data.pa,type:"question"},(0,z.q)(this.fN,this))}),a.ML=c);c.U()?c.G(!1):z.ZD(c,new z.ly(b,1,!0),0,new z.qg(5,0,5,0))};
var aO=function(a){z.W.confirm("删除问题","你确定要删除这个问题吗？相关的评论也将被删除。",function(a){if(a){var c=new z.Z(!0);z.E(c,"complete",function(){var a=z.Zn(c);a&&!a.r?window.location.href="/":z.W.message(a.msg)});c.ajax("/question/delete/"+this.data.pa)}},a)};var bO=function(a){z.fF.call(this,a)};var cO=function(){z.Q.call(this);this.data=z.R||{};this.pa=this.data.pa;this.Ko=!1;this.Wi={};this.Xv=[];this.Rq=[];this.pi=0;this.ek=z.hm&&z.hm.url_token?z.hm:null};
var dO=function(a){z.S.ih&&window.$.post("/question/popup",{action:"no_answer",question_token:a.data.Za},function(a){a&&HN(new GN,a)})};
var eO=function(a){(0,window.$)(".js-ignore-invite").click(function(){(0,window.$)(".question-invited-by").hide();window.$.post("/question/askpeople",{qid:a.data.Za,uid:z.S.fg,op:"pass"})});(0,window.$)(".js-invite-others").click(window.$.proxy(function(){var a=(0,window.$)('#zh-question-meta-wrap a[name\x3d"invite"]')[0];a&&(z.yo(a,{cC:function(){return!1},Uv:!0}),this.bu.Ty.Nc(!0))},a))};
var fO=function(a){"close"===z.R.status||z.R.Fo||(a.Oa=new z.it(a.data.Rm,a.data.pa),a.Oa.tt=5,a.Oa.wt=1,a.Oa.QC=!0,a.Oa.Ct=!0,a.Oa.w(z.L("zm-tag-editor",a.h)),a.o().g(a.Oa,["remove_tag","add_tag"],function(){z.X.fb("ga_edit_question_topic_changed")}),a.o().g(a.Oa,"start_editing",function(){z.X.fb("ga_question_topic_edit_finish_changed")}),a.Oa.addEventListener("beforeedit",z.tC({qp:!0})))};
var gO=function(a){var b=z.I("zh-question-title");z.R.Fo?b.children[0].appendChild(z.Xe('\x3ca class\x3d"Button Button--text QuestionPage-titleButton" href\x3d"/question/24501563" target\x3d"_blank" data-tip\x3d"s$t$该问题已被锁定公共编辑"\x3e\x3cspan class\x3d"sprite-global-icon-lock"\x3e\x3c/span\x3e\x3c/a\x3e')):"false"!==b.getAttribute("data-editable")&&(a.dd=new AN(a.data.pa,"/question/title","content",!1,!0),a.dd.vE=!0,a.dd.Id=!0,a.dd.zp=!0,BN(a.dd,yM(a.data.ih)),a.dd.w(b),a.o().g(a.dd,"change",function(){z.Hq.dispatchEvent("question_title_change");
window.document.title=this.dd.Ua()+" - 知乎"}),a.o().g(a.dd,"click_edit",function(){z.X.fb("ga_question_title_edit_start")}),a.o().g(a.dd,"cancel_edit",function(){z.X.fb("ga_question_title_edit_cancel")}),a.o().g(a.dd,"save_changed",function(){z.X.fb("ga_question_title_edit_save_changed")}),a.o().g(a.dd,"save_unchanged",function(){z.X.fb("ga_question_title_edit_save_unchanged")}),a.dd.addEventListener("beforeedit",z.tC({qp:!0})))};
var hO=function(a,b){var c=z.I("zh-question-detail");if(c){var d=new z.jB;a.o().g(d,"expand",b).g(d,"invalid",b);d.w(c)}};var iO=function(a){a.QD&&(a.data.nr=+a.QD.innerHTML,z.S.kb()||(a.data.nr=0),z.P(a.Qh,0<a.data.nr),a.Sq&&z.nf(a.Sq,a.data.ve?a.data.ve+" 个回答":"还没有回答"),a.Nm&&z.P(a.Nm,1<a.data.ve),z.P(a.Qh,0<a.data.nr))};
var jO=function(a){var b=z.I("zh-question-answer-wrap");if(b){var c=new z.zl({use:["expandLimit","nodeSource"],pg:a.data.ve>a.data.kT&&!z.L("question-page-pager")});a.K(c);a.o().g(c,"itemcreated",function(a){c.K(kO(this,a.item));(0,window.$)("img.lazy",a.item).lazyload({data_attribute:"actualsrc",threshold:400})});c.w(b)}};
var kO=function(a,b,c){var d=new bO({pa:a.pa});d.Ob(a);d.w(b);a.Wi[d.sa]=d;a.Rq.push(d.sa);a.o().g(d,"change",a.Pz);d.Le&&(a.pi=d.sa,d.rM=z.S,a.o().g(d.ue,"change",a.pP),a.hM=d);d.Qj?d.Le&&a.zn.appendChild(d.m()):a.Xv.push({added_time:d.Iw,vote:c,aid:d.sa});d.ji&&z.P(d.m(),!1);return d};
var lO=function(a){var b=null,c=null,d,f={suggest:"建议修改",evaluate:"建议修改",close:"关闭"};z.dm.Xd||"normal"===z.R.status||(c="被"+f[z.R.status]+'的问题不允许添加新的回答。\x3ca data-tip\x3d"s$b$为什么部分问题会被「关闭」「建议修改」？" href\x3d"//www.zhihu.com/question/21290061"\x3e\x3ci class\x3d"zg-icon zg-icon-question-mark"\x3e\x3c/i\x3e\x3c/a\x3e');a.pi?(d=a.Wi[a.pi],b="#answer-"+d.sa,d=d.ji):a.ek&&(b="/question/"+z.R.Za+"/answer/"+a.ek.url_token,d=a.ek.is_delete);b&&(c=d?'你已经删除了对该问题的回答，如果需要修改，请先 \x3ca href\x3d"javascript:;" name\x3d"cancel_delete"\x3e撤消删除\x3c/a\x3e':
'一个问题你只能回答一次，但你可以对 \x3ca href\x3d"'+b+'"\x3e现有的回答\x3c/a\x3e 进行修改');!z.S.ih||a.pi||a.ek||(c='添加回答：\x3ca href\x3d"javascript:;" name\x3d"answer_my_question"\x3e回答自己的提问\x3c/a\x3e');a.data.Yy&&(c='该问题目前已经被锁定，无法添加新答案。\x3ca href\x3d"/question/19604313" target\x3d"_blank"\x3e问题为什么会被锁定？\x3c/a\x3e');c&&a.wb.Wa(!1,c)};
var mO=function(a){a.Sq=z.I("zh-question-answer-num");a.Tq=z.I("zh-question-answer-wrap");a.Qh=z.I("zh-question-collapsed-link");a.zn=z.I("zh-question-collapsed-wrap");a.QD=z.I("zh-question-collapsed-num");a.cD=z.I("zh-question-answer-form-wrap");a.Ck=z.I("zh-question-notification-summary");a.Nm=z.I("zh-answers-filter");a.cu=z.I("zh-add-question-sug");a.Sq&&(a.data.ve=+a.Sq.getAttribute("data-num"));a.Tq&&(a.data.kT=+a.Tq.getAttribute("data-pagesize"));a.Qh&&a.o().g(a.Qh,"click",a.mV);a.cu&&a.o().g(a.cu,
"click",a.BF);a.Nm&&z.Sm&&a.o().g(a.Nm,"click",function(a){a.stopPropagation();z.V.add(this.Nm,"activated");this.o().Aa(window.document,"click",function(){z.V.remove(this.Nm,"activated")})})};var nO=function(a,b){var c=z.I("zh-question-collapsed-switcher");b?(c.name="collap",a.PD=!0,z.P(a.zn,!0),z.V.add(a.Qh,"zu-question-collap-title-active")):(a.PD=!1,c.name="expand",z.P(a.zn,!1),z.V.remove(a.Qh,"zu-question-collap-title-active"))};
var oO=function(a){a.aN=!0;var b=a.zn,c=window.$.get("/node/QuestionCollapsedAnswerListV2",{params:{question_id:a.data.pa}});c.done(function(c){c=z.Xe(c);nO(a,!0);z.V.remove(b,"zm-question-collapsed-list-loading");b.appendChild(c);z.w(z.ff(b),function(b){b!==d&&kO(a,b,99999)});(0,window.$)("img.lazy",b).lazyload({data_attribute:"actualsrc",threshold:400})});var d=z.ff(b)[0];d&&(z.P(d,!1),c.done(function(){z.P(d,!0)}));z.P(b,!0);z.V.add(b,"zm-question-collapsed-list-loading")};
var pO=function(a){if(a.cD){a.wb=new z.ME(a.data.mb,z.S);a.K(a.wb);a.wb.w(a.cD);z.dm.Xd&&z.dm.Xd.length?a.wb.ka(z.dm.Xd[0]):!z.pm.qb&&z.y&&a.wb.ka("\x3cp\x3e\x3c/p\x3e");if(!(a.data.Yy||a.pi||a.ek&&a.ek.url_token))if(a.data.jn&&a.data.jn.length&&a.data.jn[3]!==z.S.fg)a.wb.Wa(!1,"只有 "+z.pp(a.data.jn)+" 能回答此问题");else if("normal"===z.R.status||z.dm.Xd)z.S.ih||a.wb.qg();a.o().g(a.wb,"change",a.KR);a.o().g(a.wb,z.MH,a.VR);a.wb.ready(function(){var a=this.Nx();a&&"writing"===window.location.hash.slice(1)&&
a.execCommand("toggleFullScreen")})}};var qO=function(a,b){if(b=b||window.location.hash.slice(1)){var c=b.split("-"),d=c[1];"answer"===c[0]&&(c=a.jF(d))&&(c.Qj&&!a.PD?rO(a,a.Qh):rO(a,c.m()))}};var rO=function(a,b){if(b){var c=z.Qg(window.document.body).top,d=a.QP?z.Ig(a.Ck).height:0,c={paddingTop:c+d};"number"===window.$.type(c)&&(c={offsetTop:c});c.cC=vM;z.yo(b,c);z.kp(b);a.sj&&a.sj.oq()}};var sO=function(){cO.call(this);this.data=z.R;this.pa=this.data.pa};
var tO=function(a){var b=(0,window.$)(".awesome-answer-list").get(0);if(b){var c=new z.zl({use:["expandLimit"],pg:!1});a.K(c);a.o().g(c,"itemcreated",function(a){var b=new z.FF;b.w(a.item);c.K(b)});c.w(b)}};var uO=function(a,b){var c=(0,window.$)("#js-sidebar-author-info");if(!(0,window.$)("a[name\x3dfocus]",c).length){var d={0:"fullname",1:"url_token",2:"avatar_path",3:"hash",4:"headline"},f=z.pb(z.S,function(a,b,c){a[d[c]]=b;return a},{}),f=(0,z.jn)(a.sM,{author:!b&&f});c.html(f)}};
var vO=function(){var a=(0,window.$)("#zh-question-answer-collestions");a.length&&(0,window.$)("a[name\x3dfocus]",a).click(function(){(0,z.qB)(this,"favlist")})};var wO=function(a){a.Gb?a.Gb.ji?(a.Jr.innerHTML=a.Gb.Le?'你已经删除了对该问题的回答，如果需要修改，请先 \x3ca href\x3d"javascript:;" name\x3d"cancel_delete"\x3e撤消删除\x3c/a\x3e':"此答案已经被作者删除",z.P(a.Gb.m(),!1)):z.P(a.Gb.m(),!0):a.Jr.innerHTML="此答案已经被作者删除"};var xO=function(a){z.Q.apply(this,arguments)};
var yO=function(a){var b=window.$.makeArray((0,window.$)("\x3cdiv\x3e").html(a.MK.html()).children().add(a.$a.children()));a.gA=new z.JD(b,zO);a.Cq.on("click",function(){AO(a,a.$a.find("."+a.Cx).length)})};
var BO=function(a){a.$a.on("click","[data-follow]",function(b){var c=(0,window.$)(b.target),d={id:c.data("id"),name:c.closest(".topic-item").find("h3 a").text(),dY:c.data("token")};c.hasClass(a.Cx)?(b=(0,window.$)(b.target).closest(".topic-item"),a.gA.remove(b[0]),1===a.$a.find("."+a.Cx).length&&(a.Cq.hasClass("disabled")?a.vb.fadeOut():(0,window.setTimeout)(function(){AO(a,0)})),a.dispatchEvent({type:CO,data:d})):c.hasClass(a.OV)&&a.dispatchEvent({type:DO,data:d})})};
var AO=function(a,b){a.Cq.hasClass("disabled")||(a.gA.random(b)||(a.Cq.addClass("disabled"),a.vb.find(".hidden-topics-plaza").show()),a.$a.html(z.LD(a.gA)))};var EO=function(a){z.Q.apply(this,arguments)};
var FO=function(a){a.o().g(window,"hashchange",a.TF);a.TF({data:!0});a.vb.on("click",".zm-topic-cat-more a",function(){var b=a.Fh.find(GO).length;window.$.get("/followed_topics",{offset:b,limit:HO-b},function(b){b.payload.length&&(b=b.payload.map(function(b){return IO(a,b)}).join(""),a.Fh.append(b));a.Fh.find(".zm-topic-cat-more").remove();+(0,window.$)(".topic-feed-title .follow-topics-count").text()>HO&&a.Fh.append('\x3cli class\x3d"zm-topic-cat-more js-topic-all"\x3e\x3ca target\x3d"_blank" class\x3d"zg-link-gray" href\x3d"'+
(0,window.$)(".topic-feed-title a").attr("href")+'"\x3e查看全部\x3c/a\x3e\x3c/li\x3e')})})};var JO=function(a){a.zq.on("click","a",function(b){(0,window.$)(b.currentTarget).hasClass("current")||(a.zq.find("a").removeClass(KO),(0,window.$)(b.currentTarget).addClass(KO),LO(a))})};var MO=function(a,b){var c=a.vb.find(".no-topics"),d=a.vb.find(".topic-feed-title a"),f=d.find("span"),g=+f.text();(g+=b)?(d.show(),c.hide()):(d.hide(),c.show());f.html(g);a.DQ&&NO(a,g)};
var NO=function(a,b){a.rv||(a.rv=(0,window.$)('\x3ca href\x3d"#" class\x3d"new-follow-topics"\x3e新关注 \x3cspan\x3e'+b+"\x3c/span\x3e 个话题，点击查看\x3c/a\x3e"),a.rv.insertBefore(".topic-recommend").click(function(a){a.preventDefault();window.location.reload()}));a.rv[b?"show":"hide"]().find("span").html(b)};var OO=function(a,b){return a.filter(function(a,d){return(0,window.$)(d).text()===b})};
var PO=function(a){a.eg&&(a.removeChild(a.eg),a.eg.H(),a.eg=null);var b=a.$a,c=new z.zl({use:["autoload"]});a.K(c);c.use("nodeSource",{offset:function(){return Number(b.find(".feed-item").last().data("score"))||0}});c.use("childConstructor",{factory:z.LF}).use("expandLimit");c.w(b.get(0));a.o().g(c,"next",a.UC);a.eg=c};
var LO=function(a,b){var c=a.zq.find(".current").data("feedType"),c={params:{topic_id:b,feed_type:c}},d=a.$a.data("init");window.$.extend(!0,d,c);a.$a.attr("data-init",JSON.stringify(d));a.$a.empty();a.eg.Io()&&PO(a);a.eg.Th();a.sz=a.eg.Yj()};
var QO=function(a,b,c){a.tz&&"pending"===a.tz.state()&&a.tz.abort();a.tz=window.$.get("/node/TopicAvatarV2",{params:{topic_id:b,avatar_type:"topic"}},function(b){if(b&&b.r)z.W.message("错误");else{var f=c.data("href");a.Zm.find(".js-topic-title-avatar").html(b).attr("href",f);a.Zm.find(".js-topic-title-name").text(c.text()).attr("href",f);a.Zm.show()}})};var IO=function(a,b){a.RJ||(a.RJ=(0,z.jn)(RO));return a.RJ(b)};var SO=function(){z.Q.call(this)};var TO=function(){z.Q.call(this);this.BU=z.qm.searchKeyword};
var UO=function(){var a=(0,window.$)("#js-search-question-form");a.length&&a.submit(function(b){b.preventDefault();b=z.xv.aa();b.show();z.yv(b,(0,window.$)(".title-input",a).val())})};var VO=function(a){var b=(0,window.encodeURIComponent)(a.BU);(0,window.$)("ul.list[data-paging]").on("click",".item a[href!\x3d#]",function(a){a=a.currentTarget;a.host&&(a=(0,window.$)(a).closest(".item").index()+1,z.Vi.set("s-q",b),z.Vi.set("s-i",a),z.Vi.set("sid",(0,z.ln)()))})};
var WO=function(a){function b(a,b){var h=(0,window.$)(a);window.$.each(b(),function(a,b){h.on("click",a,function(a){d.apply(null,c(b,a))})})}function c(a,b){return z.ob(a,function(a){return z.sa(a)?a(b):a})}var d=z.Aa(z.T,"search");b(".related-topics",function(){return{"a.avatar-link":["visit_topic","search_result_card_topic_avatar"],"a.name-link":["visit_topic","search_result_card_topic"],"a[href$\x3dquestions]":["visit_topic_questions","search_result_card_topic"],"a[href$\x3dtop-answers]":["visit_topic_topanswers",
"search_result_card_topic"],"a[href$\x3dfollowers]":["visit_topic_followers","search_result_card_topic"],"button.zg-btn-follow":["click_follow_topic","search_result_card_topic"],"button.zg-btn-unfollow":["click_unfollow_topic","search_result_card_topic"],'a[href^\x3d"/search?"]':["click_search_result_more","search_result_card_topic"]}});b(".related-users",function(){return{"a.avatar-link":["visit_people_profile","search_result_card_people_avatar"],"a.name-link":["visit_people_profile","search_result_card_people"],
"a[href$\x3danswers]":["visit_people_answers","search_result_card_people"],"a[href$\x3dfollowers]":["visit_people_followers","search_result_card_people"],"a[href$\x3dposts]":["visit_people_posts","search_result_card_people"],"button.zg-btn-follow":["click_follow_people","search_result_card_people"],"button.zg-btn-unfollow":["click_unfollow_people","search_result_card_people"],'a[href^\x3d"/search?"]':["click_search_result_more","search_result_card_people"]}});b(window.document.body,function(){var a=
z.Aa(z.La,"search_result_%s_more_button");return{"ul.list.contents + .zu-button-more":["click_search_result_more",a("all")],"ul.list.users + .zu-button-more":["click_search_result_more",a("user")],"ul.list.topics + .zu-button-more":["click_search_result_more",a("topic")]}});b(".search-tabs",function(){var a=z.Aa(z.La,"search_result_tab_%s");return{'a[href^\x3d"/search?type\x3dquestion"]':["click_search_result_tab",a("all")],'a[href^\x3d"/search?type\x3dpeople"]':["click_search_result_tab",a("user")],
'a[href^\x3d"/search?type\x3dtopic"]':["click_search_result_tab",a("topic")]}});b(".range-selector",function(){var a=z.Aa(z.La,"search_result_range_%s");return{'a[href*\x3d"range\x3d1d"]':["click_search_result_range",a("1d")],'a[href*\x3d"range\x3d1w"]':["click_search_result_range",a("1w")],'a[href*\x3d"range\x3d3m"]':["click_search_result_range",a("3m")]}});b("ul.list.contents",function(){function a(){return function(a){return"search_result_all_list_"+((0,window.$)(a.target).closest(".item").index()+
1)+""}}return{".js-title-link":["visit_question",a()],".js-expand, .summary":["click_expand",a()],".js-collapse":["click_collapse_answer",a()],"a.zg-follow":["click_follow_question",a()],"a.zg-unfollow":["click_unfollow_question",a()]}});b("ul.list.users",function(){function a(b){return function(a){return"search_result_user_list_"+((0,window.$)(a.target).closest(".item").index()+1)+(b||"")}}return{"a.avatar-link":["visit_people_profile",a("_avatar")],"a.name-link":["visit_people_profile",a()],"a[href$\x3danswers]":["visit_people_answers",
a()],"a[href$\x3dfollowers]":["visit_people_followers",a()],"a[href$\x3dposts]":["visit_people_posts",a()],"button.zg-btn-follow":["click_follow_people",a()],"button.zg-btn-unfollow":["click_unfollow_people",a()]}});b("ul.list.topics",function(){function a(b){return function(a){return"search_result_topic_list_"+((0,window.$)(a.target).closest(".item").index()+1)+(b||"")}}return{"a.avatar-link":["visit_topic",a("_avatar")],"a.name-link":["visit_topic",a()],"a[href$\x3dquestions]":["visit_topic_questions",
a()],"a[href$\x3dfollowers]":["visit_topic_followers",a()],"button.zg-btn-follow":["click_follow_topic",a()],"button.zg-btn-unfollow":["click_unfollow_topic",a()]}});a.o().g(a,"click!",function(a){"comment"===a.namespace&&a.Ac.fill("category","search").fill("label","search_result_answer")})};var XO=function(a){YO||(this.Un=a,this.Eh=(0,window.$)(this.Un.m()),(0,window.setTimeout)((0,z.q)(this.Rb,this)))};
var ZO=function(a){(0,window.setTimeout)(function(){window.$.ajax({type:"POST",url:"/zreactor/deliver",data:JSON.stringify(a),contentType:"application/json",processData:!1})},50)};
var $O=function(a){var b=aP[a.Eh.data("type")];z.On(a.Eh[0],function(){bP(a,"display")},a.Un);a.Un.o().g(a.Un,"expand",function(c){c.target instanceof z.WA&&bP(a,"expand_"+b)}).g(a.Un,"collapse",function(c){c.target instanceof z.WA&&bP(a,"collapse_"+b)});a.Eh.on("click",'a[name\x3d"nohelp"]',function(){var b=!!(0,window.$)(this).data("revert");bP(a,b?"unhelpful":"revert_unhelpful");(0,window.$)(this).data("revert",!b)});window.$.each({".actioncard-body .more":"view_all",".actioncard-body .next:not(.disabled)":"next_page",
".actioncard-body .prev:not(.disabled)":"prev_page",".actioncard-body .items a":"open_topic",".js-validate, .js-headline-input, .js-choose-image":"open_form",'.zg-follow[data-follow^\x3d"t:"], .zg-btn-follow[data-follow^\x3d"t:"]':"follow_topic",'.zg-unfollow[data-follow^\x3d"t:"], .zg-btn-unfollow[data-follow^\x3d"t:"]':"unfollow_topic",'a.zg-follow:not([data-follow^\x3d"t:"]):not([data-follow^\x3d"m:"])':"follow_"+cP[b],'a.zg-unfollow:not([data-follow^\x3d"t:"]):not([data-follow^\x3d"m:"])':"unfollow_"+
cP[b],"a.toggle-comment":"expand_comments",'a[name\x3d"addnew"]':"comment",".content h2 a":"open_"+dP[b],"a.ignore:not(.close)":"uninterest","a.revert":"revert_uninterest","a.ignore.close":"confirm_uninterest","button.up.pressed":"vote_up_"+b,"button.down.pressed":"vote_down_"+b,"button.up:not(.pressed)":"revert_vote_up_"+b,"button.down:not(.pressed)":"revert_vote_down_"+b,'a[name\x3d"favo"]':"collect_answer",'a[name\x3d"thanks"]':"thanks",'a[name\x3d"share"]':"share",'a[name\x3d"report"], .js-report':"report",
"a.answer-date-link":"open_answer"},function(b,d){a.Eh.on("click",b,function(){bP(a,d)})})};var bP=function(a,b){var c=window.$.extend({},eP(a),{action_type:b,time:(0,z.G)()});c.object_id&&("display"===b?a.wT(c):ZO(c))};
var eP=function(a){var b=a.tC,c=window.$.extend({},b.data("meta"),{create:a.Eh.find(".source .time").data("timestamp"),offset:(0,window.$)(".feed-item").index(a.Eh)+1});return{mid:z.qm.ga_vars.user_hash,object_type:aP[a.Eh.data("type")],object_id:b.data("id"),object_meta:c,context:fP,others:""}};var gP=function(a,b,c){z.aC.call(this,a,b,c)};var hP=function(){z.Q.call(this);this.He=[];this.hm=0;this.MQ=!!(0,window.$)("#is-topstory").length;this.XE="feed-item-hook"};
var iP=function(a){var b="/node/"+a.Bd.data("init").nodename,b=a.yt=new gP(a.Qr,b,!0);a.o().g(b,"itemcreated",function(a){this.He.push(a.data.PQ)}).g(b,"ignore",function(a){jP(this,a.key,a.value)});b.Ci(a.XE);b.Ob(a);b.init();if(a.Bd.data("delayed"))z.Hq.on("guider2:topicselected",(0,z.q)(b.Yj,b))};var kP=function(a){a.Bd.on("click",".js-more-similar",function(){(0,window.$)(this).parent().slideUp("fast").nextUntil(":not(.hidden)").slideDown("fast")})};
var jP=function(a,b,c){a.He.forEach(function(a){a.Sr[b]===c&&(0,window.$)(a.h).fadeOut(150)})};var lP=function(a){a.Bd.on("click contextmenu","a",function(a){var c=a.currentTarget.href,d=c.includes("topic/"),c=c.includes("people/");if(d||c)if("click"!==a.type||a.ctrlKey||a.metaKey)c="",c="contextmenu"===a.type?"contextmenu":a.ctrlKey?"ctrl_click":"meta_click",z.wi({category:"open_link_in_new_tab",action:c,label:d?"topic":"people"})})};var mP=function(){z.F.call(this);this.uy=[];this.qE=[]};
var nP=function(a){for(var b=[],c=0;3>c;c++){var d=a.qE.shift();d&&b.push(d)}3===b.length?(a.pt.innerHTML=b.join(""),oP(a)):pP(a)};var oP=function(a){var b=z.Xp("suggest-item",a.pt);z.w(b,function(a){this.uy.push(a.id.split("-")[1])},a)};var pP=function(a){a.pt.innerHTML='\x3cimg class\x3d"bubble-loading" src\x3d"'+z.pm.oB+'/img/noti-loading.gif"\x3e';window.$.post("/lookup/suggest_member",{ids:a.uy.join(",")}).done((0,z.q)(a.YR,a))};var qP=function(){this.interval=3E4};
var rP=function(a){a.Rd||(a.Rd=(0,window.setInterval)((0,z.q)(function(){sP()},a),a.interval))};var sP=function(){(0,window.$)(".feed-item-hook .time").each(function(){(0,window.$)(this).text(z.ui((0,window.$)(this).data("timestamp")))})};var tP=function(){z.Q.call(this)};
var uP=function(){var a=(0,window.$)("#js-global-notify");if(a.length){var b=new z.Lu;b.w(a[0]);lM(b);(0,window.$)(".zu-global-notify-close",a).click(function(){var c=(0,window.$)(this).data("id");window.$.post("/notice/read",{nid:c});b.H();a.remove()})}};var vP=function(){z.Q.call(this)};var wP=function(){z.Q.call(this);this.hh="explore";this.WN="explore_feed"};
var xP=function(a){var b=(0,window.$)("#js-explore-tab");if(b.length){var c=(0,window.$)(".tab-panel",b),d=(0,window.$)(".tab-nav",b),b=function(){var b={"daily-hot":0,"monthly-hot":1}[window.location.hash.slice(1)]||0;d.removeClass("active").eq(b).addClass("active");b=c.hide().eq(b).show().children("[data-type]");if(!b.data("inited")){b.data("inited",!0);var g={daily:kN,monthly:mN}[b.data("type")],g=new yP(g);g.use("expandLimit");a.K(g);g.w(b[0])}};a.o().g(window,"hashchange",b);b()}};
var zP=function(a){var b=(0,window.$)("#zh-recommend-list-full\x3e.zh-general-list")[0];if(b){var c=new z.zl;c.use("nodeSource");z.Xk(c,function(a){var b=z.LF(a);b&&(c.K(b),b.w(a))});a.K(c);c.w(b)}};
var AP=function(){function a(a,b,c,d,m){c=(0,window.$)(c.target).closest(d,c.delegateTarget).index();z.zi(a,b,m,c+1)}var b=z.Aa(a,"view_answer","visit_answer"),c=z.Aa(a,"view_topic","visit_topic"),d=z.Aa(a,"view_roundtable","visit_roundtable");(0,window.$)("#zh-recommend").on("click","a.question_link",function(a){b(a,".feed-item","editor_recommendations_question_title")});(0,window.$)('div[data-type\x3d"daily"]').on("click","a.question_link",function(a){b(a,".feed-item","daily_trending_question_title")});
(0,window.$)('div[data-type\x3d"monthly"]').on("click","a.question_link",function(a){b(a,".feed-item","monthly_trending_question_title")});(0,window.$)("ul.hot-topics").on("click",'a[href*\x3d"topic"]',function(a){c(a,"li","explore_sidebar_trending_topics_name")});(0,window.$)("ul.hot-roundtables").on("click",'a[href*\x3d"roundtable"]',function(a){d(a,"li","explore_sidebar_trending_roundtable")});(0,window.$)("ul.hot-topics").on("click","img.avatar",function(a){c(a,"li","explore_sidebar_trending_topics_avatar")})};
var yP=function(a){z.Wk.call(this,{source:BP(a),use:["autoload"]})};var BP=function(a){return function(){return a((0,window.$)(this.lb()).last().data("offset")).then(function(a){return{results:a}})}};var oM={};z.MF.prototype.SA=z.Y(45,function(a){this.yn=a});z.mv.prototype.Nx=z.Y(43,function(){return this.Ma});z.Fd.prototype.Dl=z.Y(3,function(){return this.wE});nM.prototype.Fj=!0;nM.prototype.Qg=function(){return this.sB};nM.prototype.toString=function(){return"Const{"+this.sB+"}"};var qM={},tM={};
pM.prototype.Fj=!0;pM.prototype.Qg=function(){return this.pk};pM.prototype.By=!0;pM.prototype.Dl=function(){return 1};var CM=/^[-,."'%_!# a-zA-Z0-9]+$/;sM.prototype.Fj=!0;sM.prototype.Qg=function(){return this.BI};sM.prototype.By=!0;sM.prototype.Dl=function(){return 1};
var EM=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,DM={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0},FM={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0},AM=/^[a-zA-Z0-9-]+$/,BM={EMBED:!0,IFRAME:!0,LINK:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,TEMPLATE:!0};z.v(wM,z.it);z.e=wM.prototype;z.e.w=function(a){this.h=a;this.rg=z.L("zm-tag-editor-labels",this.h);this.Je(!0);this.xe();this.fc()};
z.e.Sn=function(){this.Vc||(this.Vc=z.M("div","zm-tag-editor-editor",[this.Qn=z.M("div","zg-section zg-clear"),this.ff=z.M("div","zg-section zm-tag-editor-command-buttons-wrap",[this.nb=z.I("zh-topic-merge-input"),z.M("a",{"class":"zg-mr15 zg-btn-blue",href:"#",name:"add",style:"display:none;"},"添加"),this.$E=z.I("zh-topic-merge-btn")])]),z.cf(this.Vc,this.rg),this.Vg(this.ff))};
z.e.Vg=function(a){this.ba=new z.ht("/topic/autocomplete",this.nb,null,null,a,!0);this.ba.rh(!0);this.ba.cm=this.Ke;this.ba.Lp(this.xm());this.ba.nx=[this.Ee];this.o().g(this.ba,"select",this.Yo);this.o().g(this.ba,"suggestionsupdate",this.Lv)};z.e.xm=function(){return(0,z.q)(function(a){return z.nb(a,function(a){return z.uo(this.data,function(c){return c[1]!==a[1]&&3<a.length})},this)},this)};z.e.Yo=function(){var a=this.ba.wj().slice(1);a&&3<a.length&&(this.lE=a,this.We(a[3],a[0]))};
z.e.We=function(a,b){var c=this;(0,window.setTimeout)(function(){c.nb.value=b})};z.e.Oe=function(){};z.ja(HM,z.Q);
HM.prototype.init=function(){this.ot=z.I("zh-pm-detail-item-wrap");this.o().g(this.ot,"click",this.Qa);var a=z.I("zh-pm-editor-form");if(a){var b=this.lb()[0],c=void 0,c=b?(0,window.$)(b).data():z.mh?{member:z.mh.id,name:z.mh.Hx}:{},b=this.uu=new z.lx({iu:!0,Wk:"to_admin"===c.type?[!0,{Et:!1}]:!0});b.rq=!1;b.oh(a);b.show();z.nx(b,c.member,c.name);c.token&&(a=c.type,b.bq=c.token,b.zB=a);b.focus()}IM(this);this.Kj()};
HM.prototype.Kj=function(){(0,window.$)("#zh-pm-detail-item-wrap").on("click","a[name\x3dreport]",function(a){(new z.Oz({type:"message",id:(0,window.$)(a.currentTarget).closest(".zm-pm-item").data("token")})).render()})};HM.prototype.lb=function(){return z.ff(this.ot)};
HM.prototype.Qa=function(a){var b=z.gp(this.ot,a.target);if(b&&(a=z.Pp(b,this.xf))){a=(0,window.$)(a).data();var c=a.token;switch(b.name){case "reply":this.uu.show();var b=this.uu,d=a.type;b.bq=c;b.zB=d;z.nx(this.uu,a.member,a.name,!1);this.uu.focus();break;case "delete":JM(this,c)}}};z.ja(LM,z.Q);
LM.prototype.init=function(){var a=z.I("zh-create-pm");a&&this.o().g(a,"click",this.XR);var a=z.I("zh-pm-item-wrap"),b=new z.zl;b.use("locationSource",{param:function(a){return{start:a[a.length-1].getAttribute("data-token")}}});b.w(a);this.o().g(a,"click",this.Qa);(0,window.$)(function(){(0,window.$)("#zh-change-pm-admin").change(function(){var a=(0,window.$)(this).find("option:selected").attr("data-token");window.location.href="self"===a?"/admin_feedback":"/admin_feedback/"+a})});(0,window.$)("#zh-pm-item-wrap").on("click","a[name\x3dreport]",
function(a){(new z.Oz({type:"message",id:(0,window.$)(a.currentTarget).closest(".zm-pm-item").data("token")})).render()})};LM.prototype.XR=function(){var a=new z.lx({iu:!0});a.show();z.nx(a,-1);z.Wa(window.location.pathname,"admin_inbox")?a.Op("admin"):a.Op((0,window.$)("#zh-change-pm-admin option:selected").attr("data-token"))};
LM.prototype.Qa=function(a){var b=z.gp(this.TX,a.target);if(b){a=b.name;b=z.Pp(b,this.xf);if(!b||!a)return!0;var c=(0,window.$)(b).data(),d=c.member,f=c.name;switch(a){case "reply":a=!0;"to_admin"===c.type&&(a=[!0,{Et:!1}]);z.Or((0,z.q)(function(){var a=new z.lx({iu:!0,Wk:!1});a.show();var b=c.type;a.bq=c.token;a.zB=b;z.nx(a,d,f,!1);a.qd.focus()},this),a)();break;case "delete":var g=b.getAttribute("data-token");z.W.confirm("删除私信会话","你确定要删除与 "+f+"的所有会话吗？",function(a){a&&MM(g)},this);break;case "edit":z.lp(this.cd,
this.Ah),this.Qm=-1}}};z.v(NM,z.aC);NM.prototype.init=function(a){NM.v.init.call(this,a);this.fc(this.h)};NM.prototype.ZB=function(a){this.ZB=a};NM.prototype.fc=function(a){if(this.ZB){var b=new z.MF,c=this.aO;b.Ex=this.Ax;b.Dx=c||b.Dx;this.yn&&b.SA(this.yn);b.w(a)}};NM.prototype.SA=function(a){this.yn=a};z.v(OM,z.Rj);OM.prototype.init=function(){this.o().g(this.h,"click",this.$o)};OM.prototype.$o=function(a){a=z.gp(this.h,a.target);"focus"===(a&&a.name)&&(0,z.qB)(a,this.Ax,null,this.$N,{follow_text:this.text[0],unfollow_text:this.text[1]})};z.v(PM,z.Rj);z.e=PM.prototype;z.e.w=function(a){this.element=a;var b=(0,window.$)("\x3cul\x3e");this.VJ=(0,window.$)("\x3cli\x3e");b.append(this.VJ);(0,window.$)(a).append(b);this.WJ||(this.WJ=!0,this.MB=new z.Z(!0),this.o().Aa(this.MB,"success",this.dS),this.MB.ajax(this.url,null,"POST"))};z.e.dS=function(){var a=z.Zn(this.MB);a&&(a&&a.r?z.W.message(a.msg):(QM(this,this.VJ,a.msg),this.WJ=!1,this.C()))};z.e.C=function(){this.o().g(this.element,"click",this.$o)};
z.e.$o=function(a){var b=(a=a.target)?a.name:"";if(b)switch(b){case "load":case "loadmore":this.rz(a);break;case "topic":window.location.href=a.href}};z.e.rz=function(a){if(!this.Po){var b=a.getAttribute("data-token"),c=a.getAttribute("data-parent");this.Po=!0;this.Zj=new z.Z(!0);this.o().Aa(this.Zj,"success",this.Nq);this.OA=a.parentNode;this.OA.innerHTML='\x3cspan class\x3d"zg-gray"\x3e加载中...\x3c/a\x3e';this.Zj.ajax(this.url+"?child\x3d"+b+"\x26parent\x3d"+c,null,"POST")}};
z.e.Nq=function(){var a=z.Zn(this.Zj);if(a)if(a&&a.r)z.W.message(a.msg);else if(a=a.msg,a[1]){(0,window.$)(this.OA).hide();for(var b=(0,window.$)(this.OA.parentNode),c=0;c<a[1].length;c++){var d=a[1][c],f=(0,window.$)("\x3cli\x3e").addClass("zm-topic-organize-item");"topic"!==d[0][0]&&f.addClass("zm-topic-organize-loadmore");b.append(f);QM(this,f,d)}this.Po=!1}};z.v(RM,z.mv);RM.prototype.gh=function(a){z.jm[0][0]===a?this.Fi():RM.v.gh.apply(this,arguments)};RM.prototype.VC=function(a){if(a=z.Zn(a.target))a.r?z.W.message(a.msg):a.msg&&(window.location.href=a.msg)};z.v(SM,z.Q);z.e=SM.prototype;z.e.init=function(){z.CG.K(this);this.w(window.document.body)};
z.e.C=function(){SM.v.C.call(this);YM(this);var a=z.I("zh-topic-top-answerer");a&&(new OM(a,"people",["zg-follow","zg-unfollow"])).init();if(a=z.I("zh-topic-direct-question-list"))a=new NM(a,null,"question",null,!0),a.Ci("question-item"),a.init();if(a=z.I("zh-topic-title"))this.dd=new RM(!1,"/topic/update","title"),z.nv(this.dd,["tid\x3d"+this.Ff]),this.dd.addEventListener("beforeedit",z.tC({jq:!0})),this.dd.w(a),(0,window.$)(a).on("click",".js-pin",function(){var a=(0,window.$)(this),c=a.attr("data-action");
window.$.post(c,{tid:z.jm[0][3]}).done(function(c){if(!c)return z.W.message("网络异常");if(c.r)return z.W.message(c.msg);c=a.hasClass("pin")?'\x3ca href\x3d"javascript:;" data-action\x3d"/pin-topic/remove" class\x3d"js-pin zg-gray unpin topic-hover-content"\x3e\x3ci class\x3d"z-icon-unpin"\x3e\x3c/i\x3e取消常去话题\x3c/a\x3e':'\x3ca href\x3d"javascript:;" data-action\x3d"/pin-topic/add" class\x3d"js-pin zg-gray pin topic-hover-content"\x3e\x3ci class\x3d"z-icon-pin"\x3e\x3c/i\x3e设为常去话题\x3c/a\x3e';a.replaceWith(c)})});
if(a=z.I("zh-topic-desc"))(0,window.$)(a).find(".zm-editable-content").data("editable-maxlength"),this.ll=new z.sv(!0,"/topic/update","description"),this.ll.Wb='\x3ca href\x3d"javascript:;" name\x3d"edit"\x3e添加话题描述\x3c/a\x3e\x3c/div\x3e',z.nv(this.ll,["tid\x3d"+this.Ff]),this.ll.pw=!1,this.ll.jK=!1,this.ll.addEventListener("beforeedit",z.tC({jq:!0})),this.ll.w(a);if(a=z.I("zh-topic-faq"))this.ux=new z.sv(!0,"/topic/"+(0,window.encodeURIComponent)(z.jm[0][1])+"/faq","content"),this.ux.Wb='\x3cdiv class\x3d"zm-topic-faq-container"\x3e\x3cdiv class\x3d"zg-gray-normal"\x3e常见问题是该话题下经常会提到的问题的整理，以便后来者查阅（\x3ca href\x3d"/question/20388061" class\x3d"zg-link-litblue"\x3e如何创建？\x3c/a\x3e）\x3c/div\x3e\x3ca href\x3d"javascript:;" name\x3d"edit" class\x3d"zg-link-litblue"\x3e\x3cspan class\x3d"zg-blue-edit"\x3e\x3c/span\x3e为「'+
z.jm[0][0]+"」添加常见问题\x3c/a\x3e\x3c/div\x3e",this.ux.pw=!1,this.ux.w(a);cN(this);dN(this);XM(this);$M(this);aN();bN(this);VM(this);UM();(a=z.L("zm-topic-feed-container"))&&(new OM(a,"question",["zg-follow","zg-unfollow"])).init();(a=z.I("zh-topic-side-children-list"))&&(new OM(a,"topic",["zg-follow","zg-unfollow"])).init();gN();(0,window.$)(".js-may-disable").click(z.Or(z.p,!0));TM();hN(this)};
z.e.mS=function(){this.Ar=this.Oa.lE;if(!this.qH&&this.Ar){this.qH=!0;this.Dz=new z.Z(!0);this.o().Aa(this.Dz,"success",this.TL);this.Dz.ajax("/topic/"+(0,window.encodeURIComponent)(z.jm[0][1])+"/demand","action\x3dmerge\x26target_topic_id\x3d"+this.Ar[3]);var a=z.I("zh-topic-merged-msg");z.P(z.I("zh-topic-merge"),!1);z.P(a,!0);a=z.Me(window.document,"a",null,a)[0];a.href="/topic/"+this.Ar[1];a.innerHTML=this.Ar[0];this.Oa&&(this.Oa.nb.value="")}};
z.e.TL=function(){var a=z.Zn(this.Dz);if(!a)return z.W.message("网络异常");if(a.r)return z.W.message(a.msg);this.qH=!1};z.e.$R=function(){this.sE||(this.sE=!0,this.Uw=new z.Z(!0),this.o().Aa(this.Uw,"success",this.RL),this.Uw.ajax("/topic/"+(0,window.encodeURIComponent)(z.jm[0][1])+"/demand","action\x3dremove"))};
z.e.RL=function(){var a=z.Zn(this.Uw);if(!a)return z.W.message("网络异常");if(a.r)return z.W.message(a.msg);a=z.I("zh-topic-del-msg");z.P(z.I("zh-topic-del-btn"),!1);z.P(a,!0);this.Oa&&(this.Oa.nb.value="");this.sE=!1};
z.e.PS=function(a){if((a=a.target)&&a.name)if("add"===a.name){if(a=this.Ov.value)this.Qv=new z.Z(!0),this.o().Aa(this.Qv,"complete",this.QL),this.Qv.ajax(window.location.href,"action\x3dadd_alias\x26alias\x3d"+(0,window.encodeURIComponent)(a))}else"remove"===a.name?(this.AA=new z.Z(!0),a=a.parentNode.getAttribute("data-token"),this.o().Aa(this.AA,"complete",this.WL),this.AA.ajax(window.location.href,"action\x3dremove_alias\x26alias_token\x3d"+a)):"remove-merged"===a.name&&(this.BA=new z.Z(!0),a=a.parentNode.getAttribute("data-token"),
this.o().Aa(this.BA,"complete",this.XL),this.BA.ajax("/topic/"+(0,window.encodeURIComponent)(z.jm[0][1]+"/demand"),"action\x3dremove\x26target_topic_id\x3d"+a))};z.e.XL=function(){var a=z.Zn(this.BA);if(!a)return z.W.message("网络异常");if(a.r)return z.W.message(a.msg);WM(this,a.msg)};z.e.WL=function(){var a=z.Zn(this.AA);if(!a)return z.W.message("网络异常");if(a.r)return z.W.message(a.msg);WM(this,a.msg)};
z.e.QL=function(){var a=z.Zn(this.Qv);if(!a)return z.W.message("网络异常");if(a.r)return z.W.message(a.msg);var a=a.msg,b=z.M("li");b.setAttribute("data-token",a[1]);b.innerHTML=a[0]+' \x3ca name\x3d"remove" href\x3d"javascript:;" class\x3d"zg-link-gray"\x3e移除\x3c/a\x3e';this.Pv.appendChild(b);this.Ov.value="";z.P(this.Pv.parentNode,!0)};
z.e.bB=function(a){this.$z?this.ib.U()?this.ib.G(!1):(this.ib.G(!0),a.stopPropagation(),a.preventDefault(),this.$k()):(a.stopPropagation(),a.preventDefault(),this.Jj(),this.$k());this.$z=!0};z.e.$k=function(){this.o().Aa(window.document,"click",function(){this.ib.G(!1)})};
z.e.Jj=function(){var a=z.I("zh-topic-side-head"),b=this.ig.getAttribute("data-auth");this.ib=new z.jy;this.qy=!0;"f-topic-manage"===b&&this.ib.Ga(this.US=new z.ey("管理话题"));this.ib.Ga(this.VS=new z.ey("组织话题"));this.ib.Ga(this.TS=new z.ey("话题日志"));this.qy&&(this.ib.render(a),this.o().g(this.ib,"action",this.Bj))};z.e.Bj=function(a){var b="";a.target===this.US?b="admin":a.target===this.VS?b="organize":a.target===this.TS&&(b="log");window.location.href=["/topic",this.Hi[1],b].join("/")};
z.e.wS=function(){var a=z.Zn(this.zA);if(a&&!a.r){var b=[];z.w(a,function(a){b.push(z.op(a,null,!0))});this.TT.innerHTML=b.join("")+'\x3cdiv class\x3d"zg-clear"\x3e\x3c/div\x3e';a.length&&z.P(z.I("zh-topic-side-related-topics-wrap"),!0)}};z.v(iN,z.Q);iN.prototype.B=function(){this.h=this.L().B("FORM",{method:"POST",style:"display:none"})};iN.prototype.post=function(a,b,c){var d=this.m();d||(this.render(),d=this.m());d.action=b||"";d.target=c||"";jN(this,d,a);d.submit()};z.v(nN,z.Rj);nN.prototype.init=function(){var a=z.Un(new z.oh(window.location.href),"group_id");a&&(this.fk=new z.Z(!1),this.o().Aa(this.fk,"success",this.iA),a&&this.fk.ajax("/noti7/read","group_id\x3d"+a,"POST"))};nN.prototype.iA=function(){var a=z.Zn(this.fk);if(a&&!a.r&&a.msg){var b=a.msg;if(!0===b||"true"===b||"True"===b)return;this.AR=a.msg;this.dispatchEvent("change")}(a=z.BG)&&z.Jw(a)};z.v(oN,z.Q);z.e=oN.prototype;z.e.init=function(){z.CG.K(this);this.w(window.document.body)};
z.e.C=function(){oN.v.C.call(this);rN(this);if(this.Mb=z.I("zh-list-meta-wrap"))this.o().g(this.Mb,"click",this.ip),z.Un(new z.oh(window.location.href),"fc")&&tN(this);var a=z.I("zh-favlists-wrap");a&&(new NM(a,null,"favlist",null,!0)).init();pN(this);(a=z.I("zh-favlist-log-list-wrap"))&&(new NM(a,null,"favlist",null,!0)).init();qN();if(a=z.I("zh-favlist-followers-wrap"))a=new NM(a,null,"people",["zg-btn-follow","zg-btn-unfollow"],!0),a.Ci("zm-profile-section-item"),a.ZB(!0),a.init();this.o().g(window,
"hashchange",this.UX);this.Iy();this.Wo=new nN;this.Wo.init()};z.e.IP=function(a){a=a.target;var b=a.id.split("-"),c=b[1],b=b[2];(new z.Z(!0)).ajax("/collection/remove","answer_id\x3d"+c+"\x26favlist_id\x3d"+b);if(b=z.uf(a,"div","zm-item"))a=z.Xp("zm-item-answer",b),1===a.length?z.N(b):(a=z.rb(a,function(a){return a.getAttribute("data-aid")===c}))&&z.N(a.parentNode)};z.e.YU=z.Or(function(){z.zy.aa().show(!0);z.yi("collect","click_add_collection_start","collections_sidebar_create_collection")},!0);
z.e.bB=function(a){this.$z?this.ib.U()?this.ib.G(!1):(this.ib.G(!0),a.stopPropagation(),a.preventDefault(),this.$k()):(a.stopPropagation(),a.preventDefault(),this.Jj(),this.$k());this.$z=!0};z.e.$k=function(){this.o().Aa(window.document,"click",function(){this.ib.G(!1)})};z.e.Jj=function(){var a=z.I("zh-list-side-head");this.ib=new z.jy;this.qy=!0;this.visible||this.ib.Ga(this.XS=new z.ey("设置为公开"));this.ib.Ga(this.SS=new z.ey("删除此收藏夹"));this.qy&&(this.ib.render(a),this.o().g(this.ib,"action",this.Bj))};
z.e.ip=function(a){a=a.target;switch(a&&a.name){case "edit":z.Dy(z.zy.aa());break;case "addcomment":z.wi({category:"collect",action:"click_add_collection_comment_start",label:"collection_collection_name_add_collection_comment_start"});tN(this);this.va.Gf();this.va.wc()&&this.va.Ii("view_comments",(0,window.parseInt)(z.pf(a),10)||0);break;case "remove":sN(this)}};
z.e.Bj=function(a){a.target===this.XS?z.W.confirm("确定设置收藏夹为公开？","收藏夹设置为公开后，将不能再设置为私密。",function(a){a&&uN(this)},this):a.target===this.SS&&sN(this)};z.e.Iy=function(){var a=1,b=(0,window.$)("ul.hot-favlists"),c=null;(0,window.$)("#js-hot-fav-switch").click(function(){c&&"pending"===c.state()||(a=5<=a?1:a+1,c=lN(a).done(function(a){b.html(a)}))})};z.v(vN,z.Rj);
vN.prototype.init=function(){if(this.rk=z.I("zh-question-redirect-info"))this.rk.innerHTML&&(this.Ko=!0),this.o().g(this.rk,"click",function(a){"cancel"===a.target.name&&yN(this)});var a=z.I("zh-question-side-header-wrap");if(z.pm.qb&&!z.pm.NG&&a){var b=z.I("zh-question-filter-wrap");b?z.bf(a,b):a.style[z.A?"styleFloat":"cssFloat"]="none"}(this.ig=z.I("zh-question-operation-menu"))&&this.Jj();this.o().g(z.Hq,"anon_change",function(a){var b=z.I("zh-question-side-invitation-anon");b&&z.P(b,a.mb);(b=
z.I("zh-question-side-invitation-notanon"))&&z.P(b,!a.mb);this.mm&&this.mm.Wa(yM(this.data.ih)||!a.mb)})};
vN.prototype.Jj=function(){this.ib=new z.jy;var a=this.data.jn,b=this.ig.getAttribute("data-auth"),b=b?b.split(","):[];if(null==a||0===a)this.ib.Ga(this.Mt=xN("使用匿名身份",!1)),wN(this),z.om("question_op_redirect")||"close"===z.R.status||z.R.Fo||(this.ib.Ga(this.mm=xN(this.Ko?"撤消重定向":"问题重定向")),this.mm.Wa(yM(this.data.ih)||!this.data.mb)),z.x(b,"auth-f-manage")&&this.ib.Ga(this.WS=xN("更新话题页显示",!1)),this.o().g(this.ib,"action",this.Bj),this.Mt&&this.o().g(z.Hq,"anon_change",function(){wN(this)}),this.Gb&&
z.x(b,"auth-pu-mark")&&(this.ib.Ga(this.Zz=xN("优质回答",!0)),this.Zz.Mc(this.Gb.GQ)),a=new z.sy("Settings",this.ib),a.tk=!0,z.uy(a),a.w(this.ig)};
vN.prototype.Bj=function(a){if(a.target===this.Mt)z.Fq(this.data.mb?0:1);else if(a.target===this.mm){if(!1===z.tC({qp:!0})())return!1;this.sp||(this.sp=new z.mC(this.pa),this.o().g(this.sp,"change",this.iR));this.ib.G(!1);this.Ko?yN(this):this.sp.show()}else a.target===this.RS?(a=this.RS.tf()?"/unlock_summary":"/lock_summary",z.xq("/question/"+this.data.Za+a,function(){window.top!==window?window.top.location.href="/question/"+z.R.Za:window.location.reload()},"POST")):a.target===this.WS?window.$.post("/refresh_topic_feeds",
{q:z.R.Za}).done(function(a){a.r||z.W.message("操作成功！")}):a.target===this.Zz&&(a=this.Zz.tf()?"/good_mark":"/good_unmark",window.$.post("/answer/"+this.Gb.Za+a).done(function(a){a.r||z.W.message("操作成功！")}))};
vN.prototype.iR=function(){this.rk.innerHTML='\x3cdiv class\x3d"zg-wrap"\x3e\x3cdiv class\x3d"zu-global-nitify-inner"\x3e\x3cspan class\x3d"zu-global-notify-icon"\x3e\x3c/span\x3e此问题将跳转至 \x3ca href\x3d"/question/'+this.sp.pu+'"\x3e'+this.sp.FI+'\x3c/a\x3e（\x3ca href\x3d"javascript:;" name\x3d"cancel"\x3e撤消重定向\x3c/a\x3e）\x3c/div\x3e\x3c/div\x3e';z.P(this.rk,!0);this.Ko=!0;this.mm.Gp("撤消重定向")};z.v(zN,z.Q);zN.prototype.B=function(){zN.v.B.call(this);this.h=z.Xe(CP)};zN.prototype.C=function(){zN.v.C.call(this);this.Bd=(0,window.$)(this.m());this.Gm=z.ct("answer",this.dD);var a=z.aw(window.location.protocol+"//"+window.location.hostname+"/question/"+this.KT+"/answer/"+this.dD);(0,window.$)(".js-qrcode-image",this.Bd).attr("src",a);this.Rb()};
zN.prototype.Rb=function(){var a=this;(0,window.$)("button.weibo",this.Bd).click(function(){a.Gm.done(function(a){a.r||(z.eB(a.msg.sina),z.yi("share","click_share_answer_to_weibo_start","answer_box_after_submit_answer"))})})};var CP='\x3cdiv class\x3d"answer-share-tip"\x3e分享我的回答到\x3cbutton class\x3d"wechat hidden-phone"\x3e\x3cdiv class\x3d"qr-code"\x3e扫描二维码\x3cimg class\x3d"js-qrcode-image" alt\x3d"微信分享二维码"\x3e\x3c/div\x3e\x3cspan class\x3d"ico z-ico-wechat"\x3e\x3c/span\x3e微信\x3c/button\x3e\x3cbutton class\x3d"weibo"\x3e\x3cspan class\x3d"ico z-ico-weibo"\x3e\x3c/span\x3e微博\x3c/button\x3e\x3c/div\x3e';z.v(AN,z.sv);var DN=[{value:"精简文字描述",label:"精简文字描述"},{value:"补充必要的信息",label:"补充必要的信息"},{value:"改进标点或格式",label:"改进标点或格式"},{value:"other",label:"其他"}];z.e=AN.prototype;z.e.w=function(a){AN.v.w.call(this,a);this.o().g(z.Hq,"anon_change",this.yj)};z.e.yj=function(a){this.Zy||z.V.enable(this.h,"zm-editable-disabled",a.mb)};
z.e.gl=function(){AN.v.gl.call(this);this.wA=z.M("div",{"class":"zm-editable-require-reason-wrap",style:"padding:10px 0 0 0"},[z.M("a",{"class":"zg-right zg-link-litblue",href:"/question/19550238/answer/12202028",target:"_blank"},"为什么问题可以被公共编辑？"),CN(),this.rH=z.M("span"),this.MT=z.M("div",{"class":"zg-form-text-input",style:"height:22px;margin:10px 0 0 0;display:none"},this.LT=z.M("textarea",{style:"width:100%;height:22px !important;min-height:22px !important;"}))]);z.bf(this.wA,this.tc);this.zp&&
EN(this," * 必选","zg-gray-normal");var a=z.Me(window.document,"select",null,this.wA)[0];this.o().g(a,"change",function(){z.P(this.MT,"other"===a.value);EN(this," * 必选","zg-gray-normal")})};
z.e.gh=function(a){var b=z.Me(window.document,"select",null,this.wA)[0],c=b.value;if(this.zp){if("none"===c){EN(this,"请选择一个修改理由");return}if("other"===b.value&&(c=z.Ao(this.LT.value),!c)){EN(this,"请填写修改理由");return}}"title"===this.Dr&&-1===a.indexOf("?")&&-1===a.indexOf("？")?EN(this,"还没有输入问号"):("none"===c&&(c=""),this.params=["id\x3d"+this.pa+"\x26reason\x3d"+(0,window.encodeURIComponent)(c)+"\x26question_id\x3d"+this.pa],this.dispatchEvent("change"),AN.v.gh.call(this,a),EN(this,"* 必选","zg-gray-normal"),
this.zp=!0)};z.e.Zf=function(){return this.Id&&this.eT?(0,z.hn)(z.uq(this.Ma.value)):AN.v.Zf.call(this)};z.e.Mg=function(){(0,window.$)(window).on("beforeunload.EditorWithReason",(0,z.q)(function(){return"你对问题的修改还未保存，确认离开该页面吗？"},this))};z.e.Xh=function(){(0,window.$)(window).off("beforeunload.EditorWithReason")};z.e.Fi=function(){AN.v.Fi.call(this);this.Xh()};z.e.qg=function(){AN.v.qg.call(this);this.Mg()};z.v(FN,z.Q);FN.prototype.K=function(a,b){FN.v.K.call(this,a,b);this.o().g(a,"beforeexpand",this.FP)};FN.prototype.FP=function(a){var b=a.target;z.ch(this,function(a){b!==a&&a.wc()&&a.Nc(!1)})};FN.prototype.H=function(){this.o().H();FN.v.H.call(this)};z.v(GN,z.U);GN.prototype.C=function(){GN.v.C.call(this);z.Nj(this,490);(0,window.$)(this.m()).addClass("user-guiding-dialog")};z.v(KN,z.Q);z.e=KN.prototype;z.e.B=function(){KN.v.B.call(this);this.h=z.M("div",{className:"question-invite-panel"})};z.e.C=function(){KN.v.C.call(this);this.X=(0,window.$)(this.m())};z.e.D=function(){KN.v.D.call(this);this.Z&&this.Z.H();delete this.Z;delete this.Wl;delete this.Pj};z.e.wc=function(){return this.Jb};z.e.Gf=function(){this.Nc(!this.Jb)};
z.e.Nc=function(a){a!==this.wc()&&(this.dispatchEvent(a?"beforeexpand":"beforecollapse"),a&&!this.xc&&LN(this),this.Jb=a,this.X.toggle(a),this.dispatchEvent(a?"expand":"collapse"))};
z.e.Ey=function(a){var b=this,c=(0,z.jn)(DP),d=new z.Ss(a,{Ke:20,source:"/question/ac/invite-people?question_token\x3d"+this.mp,uk:this.m(),placeholder:"搜索你想邀请的人",ud:function(a,b,d){d.innerHTML=c(a.data)},filter:function(a){return z.nb(a,function(a){return!QN(b,a.member_hash)})},select:function(){return""},format:function(a){return a}});d.zi=function(){return!1};var f=d.M;f.className="suggest-persons search";f.lh="person";f.rh(!1);var g=(0,window.$)(".suggest-persons-wrapper",this.h),h=z.Kj(function(){(0,window.$)(f.m()).on("click",
"button",window.$.proxy(b.EF,b))}),k=(0,window.$)(".invite-title .spinner-gray");(0,window.$)(".search-input",this.h).on("input",function(){k.css("display","inline-block")});d.addEventListener("show",function(){k.hide();var a=f.m();g.hide();(0,window.$)(".no-result-tips",b.h).remove();var c=(0,window.$)(".person",a);5<c.length&&(c.hide().slice(0,5).show(),(0,window.$)('\x3ca class\x3d"js-more" href\x3d"#"\x3e更多搜索结果\x3c/a\x3e').appendTo(a).one("click",function(){c.show();(0,window.$)(this).remove();
return!1}));h()});d.addEventListener("hide",function(){k.hide();a.value.length?(0,window.$)(".no-result-tips",b.h).length||(g.hide(),(0,window.$)('\x3cspan class\x3d"no-result-tips"\x3e没有找到你想邀请的人\x3c/span\x3e').appendTo(b.h)):(g.show(),(0,window.$)(".no-result-tips",b.h).remove())});d.addEventListener("dismiss",function(){(0,window.$)(".no-result-tips",b.h).remove();g.show()});this.Z=d};z.e.MR=function(){this.wc()?(this.Z&&this.Z.H(),LN(this)):this.xc=!1};z.e.BO=function(){z.Fq(0)};
z.e.EF=z.Or(function(a){var b=a.target,c=this.tI((0,window.$)(b).parents(".person"));this.Wl&&"pending"===this.Wl.state()&&this.Wl.abort();a=b.getAttribute("data-type");var d=z.V.has(b,this.yG),f=(0,z.q)(function(a){a?(SN(this,b,!0),this.Pj.unshift(c),UN(this),RN(this,c.id,!0),this.QM()):(SN(this,b,!1),TN(this,c.id),RN(this,c.id,!1))},this);d?(this.Wl=xM(this.mp,c.id),f(!1)):(this.Wl=window.$.post("/question/askpeople",{qid:this.mp,uid:c.id,_source_type:a,op:"add"}).done(function(a){a.r&&(z.W.message(a.msg),
f(!1))}),f(!0),PN(this,a))},!0);z.e.CO=function(a){a=a.target.getAttribute("data-uid");xM(this.mp,a);RN(this,a,!1);TN(this,a)};z.e.QM=z.Kj(function(){z.S.ih&&window.$.post("/question/popup",{action:"invite",question_token:this.mp},function(a){a&&JN(new GN,a)})});z.e.tI=function(a){var b=(0,window.$)(".zm-item-link-avatar",a),c=(0,window.$)(".zg-link",a);return{id:String((0,window.$)("button",a).data("uid")),avatar:(0,window.$)("img",b).attr("src"),fullname:c.text(),url_token:b.attr("href").split("/").slice(-1)[0]}};
var MN='\x3ci class\x3d"icon icon-spike"\x3e\x3c/i\x3e\x3cdiv class\x3d"spinner"\x3e正在加载，请稍等 \x3ci class\x3d"spinner-gray"\x3e\x3c/i\x3e\x3c/div\x3e',WN='你已邀请 \x3cspan class\x3d"invited-shortlist"\x3e\x3c% helper.each(persons.slice(0, 2), function(person, i, sliced) { %\x3e\x3ca href\x3d"/people/\x3c%\x3dperson.url_token%\x3e" class\x3d"zg-link-gray" target\x3d"_blank"\x3e\x3c%\x3dperson.fullname%\x3e\x3c/a\x3e\x3c%\x3d i !\x3d\x3d sliced.length - 1 ? "、" : ""%\x3e\x3c% }); %\x3e\x3c%\x3dhelper.fullList()%\x3e\x3c/span\x3e\x3c% if (persons.length \x3e 2) { %\x3e 等 \x3c%\x3dpersons.length%\x3e 人 \x3c% } %\x3e\x3c% if (persons.length \x3c maxInvites) { %\x3e ，还可以邀请 \x3c%\x3dmaxInvites - persons.length%\x3e 人\x3c% } %\x3e',
VN='\x3cdiv class\x3d"invited-hovercard"\x3e\x3ci class\x3d"icon icon-spike"\x3e\x3c/i\x3e\x3cul class\x3d"invited-fulllist"\x3e\x3c% helper.each(persons, function(person, i) { %\x3e\x3cli\x3e\x3ca title\x3d"\x3c%-person.fullname%\x3e" class\x3d"zm-item-link-avatar" href\x3d"/people/\x3c%\x3dperson.url_token%\x3e" target\x3d"_blank"\x3e\x3cimg src\x3d"\x3c%\x3dperson.avatar%\x3e" class\x3d"zm-item-img-avatar"\x3e\x3c/a\x3e\x3ca href\x3d"/people/\x3c%\x3dperson.url_token%\x3e" class\x3d"zg-link-gray" title\x3d"\x3c%-person.fullname%\x3e" target\x3d"_blank"\x3e\x3c%\x3dperson.fullname%\x3e\x3c/a\x3e\x3cbutton class\x3d"cancel-button zg-link-btn zg-link-gray" data-uid\x3d"\x3c%\x3dperson.id%\x3e"\x3e收回邀请\x3c/button\x3e\x3c/li\x3e\x3c% }) %\x3e\x3c/ul\x3e\x3c/div\x3e',
DP='\x3ca data-tip\x3d"p$t$\x3c%\x3durl_token%\x3e" class\x3d"zm-item-link-avatar" href\x3d"/people/\x3c%\x3durl_token%\x3e" title\x3d"\x3c%\x3dfullname%\x3e" target\x3d"_blank"\x3e\x3cimg src\x3d"\x3c%\x3davatar_path%\x3e" class\x3d"zm-item-img-avatar"\x3e\x3c/a\x3e\x3cdiv class\x3d"content"\x3e\x3cbutton class\x3d"invite-button zg-btn zg-btn-green" data-uid\x3d"\x3c%\x3dmember_hash%\x3e" data-type\x3d"search"\x3e邀请回答\x3c/button\x3e\x3cdiv class\x3d"describe"\x3e\x3ca data-tip\x3d"p$t$\x3c%\x3durl_token%\x3e" href\x3d"/people/\x3c%\x3durl_token%\x3e" class\x3d"zg-link" target\x3d"_blank"\x3e\x3c%\x3dhighlighted_fullname%\x3e\x3c/a\x3e\x3c% if(headline) { %\x3e ，\x3cspan class\x3d"bio" title\x3d"\x3c%-headline%\x3e"\x3e\x3c%\x3dhighlighted_headline%\x3e\x3c/span\x3e \x3c% } %\x3e\x3c/div\x3e\x3cdiv class\x3d"reason"\x3e\x3c% if (detailed_info) {%\x3e \x3c%\x3ddetailed_info%\x3e\x3c% } %\x3e\x3c% if (topic["answer_num"]) {%\x3e在 \x3ca href\x3d"/people/\x3c%\x3durl_token%\x3e/topic/\x3c%\x3dtopic["url_token"]%\x3e/answers" data-tip\x3d"t$b$\x3c%\x3dtopic["url_token"]%\x3e" data-token\x3d"\x3c%\x3dtopic["url_token"]%\x3e" data-topicid\x3d"\x3c%\x3dtopic["id"]%\x3e" target\x3d"_blank"\x3e \x3c%\x3dtopic["name"]%\x3e \x3c/a\x3e 话题下有 \x3c%\x3dtopic["answer_num"]%\x3e 个回答 \x3c% } %\x3e\x3c/div\x3e\x3c/div\x3e';z.v(XN,z.Q);z.e=XN.prototype;z.e.C=function(){XN.v.C.call(this);this.o().g(this.h,"click",this.ip);YN(this);this.o().g(this,"click!",function(a){"comment"===a.namespace&&a.Ac.fill("label","question")});this.g("trackRequested",function(a){a.label="question_box";z.wi(a)})};z.e.Kj=function(){var a=this.h.querySelector("a[name\x3dreport-question]");if(a){var b=this;a.addEventListener("click",function(){(new z.Oz({type:"question",id:b.data.pa})).render()})}};
z.e.Lj=function(){var a=(0,window.$)('a[name\x3d"share"]',this.m()).get(0);a&&z.fB(a,"question",this.data.Za,window.location.protocol+"//"+window.location.host+"/question/"+this.data.Za).Ob(this)};
z.e.ip=function(a){var b=(a=z.gp(this.h,a.target))&&a.name;if(b)switch(b){case "addcomment":"添加评论"===window.$.trim((0,window.$)(a).text())?z.Or(this.ms).call(this,a):this.ms(a);break;case "remove":aO(this);break;case "admin":$N(this,a);break;case "invite":this.Ty.Gf(),this.dispatchEvent(new z.Iz("click!invitation",{category:"invitation",action:(this.Ty.wc()?"show":"hide")+"_ask_to_answer_card",label:"?",value:this.data.ve}))}};
z.e.ms=function(a){this.va.Gf();this.va.wc()&&this.va.Ii("view_comments",(0,window.parseInt)(z.pf(a),10)||0)};z.e.fN=function(a){this.NC.W(a.msg.action);this.NC.Gp(a.msg.caption)};z.v(bO,z.fF);bO.prototype.w=function(a){var b=this;bO.v.w.call(this,a);this.Le&&this.wu(this.Br.mb);this.g("trackRequested",function(a){a.label="answer_box";a.value=(0,window.$)(b.h).index(".zm-item-answer")+1;z.wi(a)})};bO.prototype.U=function(){return(0,window.$)(this.h).is(":visible")};z.v(cO,z.Q);z.e=cO.prototype;z.e.init=function(){z.CG.K(this);this.w(window.document.body)};z.e.C=function(){cO.v.C.call(this);this.My();eO(this);this.Wo=new nN;this.o().g(this.Wo,"change",this.iA);this.Wo.init();this.sJ();var a=z.I("zh-question-meta-wrap");a&&(this.bu=new XN(this.data),this.K(this.bu),this.bu.w(a),this.bu.Ob(this));dO(this);(a=z.qm.topic_errors_info)&&z.Rn(a)};
z.e.sJ=function(){this.data.Za=z.R.Za;this.Ao(!0);z.S.kb()&&(fO(this),gO(this));mO(this);(this.yw=z.I("zg-question-suggested-topics"))&&this.o().g(this.yw,"click",this.JR);this.zo();this.o().g(window,"hashchange",function(a){a=a.jc;a.oldURL&&"writing"===a.oldURL.split("#")[1]||qO(this)});jO(this);pO(this);lO(this);qO(this,null);iO(this);z.em&&(0,window.setTimeout)(function(){window.location.href=z.em},5E3)};
z.e.My=function(){(0,z.oB)("question",this.data.Za,"read");this.o().g(this,["click!","show!"],function(a){"comment"===a.namespace&&a.Ac.fill("category","question_answer").fill("label","question_answer");"invitation"===a.namespace&&a.Ac.fill("label","question_page")})};z.e.iA=function(){this.QP=!0;this.Ck=(0,window.$)(this.Wo.AR)[0];z.cf(this.Ck,z.L("zu-top"));z.P(this.Ck,!0);z.pm.qb||(this.sj=new z.Lu,this.sj.w(this.Ck),lM(this.sj));this.o().g(this.Ck,"click",this.BF);qO(this)};
z.e.Ao=function(a){z.S.kb()&&a?hO(this,this.gQ):hO(this,z.p)};
z.e.gQ=function(a){"close"===z.R.status||z.R.Fo||(a=a.target.m(),this.Pb=new AN(this.data.pa,"/question/detail","content",!0,null,600),BN(this.Pb,yM(this.data.ih)),z.L("zm-editable-content",a).innerHTML&&(this.Pb.zp=!0),this.Pb.w(a),this.o().g(this.Pb,"click_edit",function(){z.X.fb("ga_question_supplement_edit_start")}),this.o().g(this.Pb,"cancel_edit",function(){z.X.fb("ga_question_supplement_edit_cancel")}),this.o().g(this.Pb,"save_changed",function(){z.X.fb("ga_question_supplement_edit_save_changed")}),
this.o().g(this.Pb,"save_unchanged",function(){z.X.fb("ga_question_supplement_edit_save_unchanged")}),this.Pb.addEventListener("beforeedit",z.tC({qp:!0})))};
z.e.BF=function(a){if("close"===a.target.name){if(this.sj&&(z.Ou(this.sj),z.Nu(this.sj,!1),window.history.replaceState)){a=new z.oh(window.location.href);var b=a.Jd();b.remove("q");b.remove("psq");window.history.replaceState({},"",a.Me+"?"+b.toString())}z.P(this.Ck,!1);z.P(this.cu,!1)}else if("A"===a.target.tagName&&"zh-question-suggest-reask"===a.target.id&&(z.P(this.cu,!1),z.xv.aa().show()),b="a"===(0,window.$)(a.target).prop("tagName").toLowerCase()?a.target:this.Vf(a.target,"A"))a.preventDefault(),
a.stopPropagation(),a=b.getAttribute("data-source")||b.href,b=a.indexOf("#"),a=0>b?null:a.substr(b+1),qO(this,a?(0,window.decodeURIComponent)(a):a)};z.e.pP=function(){var a=this.hM,b=a.m(),c=a.ue.Ua()[0];z.P(b,!1);c=z.Xe((0,z.bb)(c));z.bf(c,b);this.Wi[a.sa]=null;this.Rq=z.nb(this.Rq,function(b){return b!==a.sa},this);var d=999;this.Xv=z.nb(this.Xv,function(b){b.aid===a.sa&&(d=b.vote);return b.aid!==a.sa},this);z.N(b);a.H();kO(this,c,d)};
z.e.Pz=function(a){a=a.target;if(a instanceof bO){var b=a.m();switch(a.Cv){case "collap":this.zn.appendChild(b);z.V.add(b,"zm-item-collapsed");this.data.ve--;iO(this);break;case "cancel_collap":this.Tq.appendChild(b);z.V.remove(b,"zm-item-collapsed");rO(this,b);this.data.ve++;iO(this);break;case "set_delete":lO(this);this.data.ve--;iO(this);break;case "cancel_delete":rO(this,this.Wi[this.pi].m()),lO(this),this.data.ve++,iO(this)}}};z.e.jF=function(a){return this.Wi[a]};
z.e.mV=function(a){(a=z.gp(this.Qh,a.target))&&a.name&&("expand"===a.name?(this.aN||oO(this),nO(this,!0)):nO(this,!1))};z.e.VR=function(){var a=this.Wi[this.pi],b;a?(kM(a),rO(this,a.m())):(b=this.ek,a=new z.Z(!0),this.o().Aa(a,"success",function(){window.location.href="/question/"+z.R.Za+"/answer/"+b.url_token}),a.ajax("/answer/unremove","aid\x3d"+b.id))};
z.e.KR=function(){var a=this.wb,b=a.Qq.checked,c=Number(!a.aE.checked),a={modal:!0,title:"确认放弃匿名身份？",content:"你在该问题下的赞同和关注行为将以实名显示。"},d=(0,z.q)(function(){if(!this.xhr||!this.xhr.bc()){var a=this.wb.Zf();if(a){var d=new z.Z(!0),h=new z.uh,k=b?1:0;h.add("id",this.pa).add("content",a).add("anon",k).add("copyable",c);d.on("success",function(){z.R.mb!==k&&(z.R.mb=k,z.Hq.dispatchEvent(new z.Gq(k)));var a=z.Zn(this.xhr);a?a.r?z.W.alert(a.msg):(a=z.Xe((0,z.bb)(a.msg[0])),this.Tq.appendChild(a),kO(this,a,
this.Rq.length),z.kp(a),lO(this),z.yE(this.wb.GE),z.BE(this.wb.GE),this.wb.H(),z.R.mb||(new zN(this.data.Za,this.Wi[this.pi].Za)).render((0,window.$)(".zu-main-content-inner").get(0)),this.data.ve++,iO(this)):z.W.message("网络异常")},!1,this);d.ajax("/answer/add",h.toString());this.xhr=d}}},this);z.R.mb&&!b?z.W.confirm(a,function(a){a&&d()}):d()};z.e.Vf=function(){};
z.e.JR=function(a){if((a=this.Vf(a.target))&&a.name){var b=a.name;"close"===b?z.P(this.yw,!1):"addtag"===b&&(this.Oa.We(a.id.split("-")[1],a.innerHTML),z.P(a,!1))}};z.e.zo=function(){this.eB=new vN(this.pa);this.eB.init()};z.v(sO,cO);z.e=sO.prototype;z.e.sJ=function(){(this.Jr=z.I("zh-single-answer-disable-wrap"))&&this.o().g(this.Jr,"click",this.mU);this.Rs();this.zo();vO();this.Ao(!1);var a=(0,window.$)("#zh-question-answer-collections \x3e .zh-general-list").get(0);if(a){var b=new z.zl({use:["autoload","nodeSource"]});this.K(b);b.w(a)}tO(this)};z.e.My=function(){this.o().g(this,["click!","show!"],function(a){"invitation"===a.namespace&&a.Ac.fill("label","answer_page")});sO.v.My.call(this)};
z.e.mU=function(a){a.target&&a.target.name&&kM(this.Gb)};z.e.Rs=function(){var a=z.L("zm-item-answer",z.I("zh-question-answer-wrap"));if(a){this.Gb=new bO({pa:this.pa,xE:!0});this.K(this.Gb);this.Gb.w(a);a=this.o();a.g(this.Gb,"change",this.Pz);if(this.Gb.Le){a.g(z.Hq,"anon_change",function(a){uO(this,a.mb)});var b=this.Gb.ue;b&&a.g(b,"change",function(){var a=(0,z.bb)(b.Ua()[0]),a=z.Xe(a);z.Wp(a,this.Gb.h);this.Gb.H();this.Rs(a)})}wO(this);this.Gb.sg();this.Gb.va.mD=!1}};
z.e.jF=function(a){if(this.Gb.sa===a)return this.Gb};z.e.sM='\x3ch3\x3e关于作者\x3c/h3\x3e\x3c% if (author) { %\x3e\x3ca class\x3d"zm-list-avatar-link" href\x3d"/people/\x3c%\x3d author.url_token %\x3e" tabindex\x3d"-1"\x3e\x3cimg class\x3d"zm-list-avatar-medium" src\x3d"\x3c%\x3d author.avatar_path.replace("_s.","_m.") %\x3e"/\x3e\x3c/a\x3e\x3cdiv class\x3d"zm-list-content-medium"\x3e\x3ch2 class\x3d"zm-list-content-title"\x3e\x3ca href\x3d"/people/\x3c%\x3d author.url_token %\x3e"\x3e\x3c%\x3d author.fullname %\x3e\x3c/a\x3e\x3c/h2\x3e\x3cdiv class\x3d"zg-gray-normal"\x3e\x3c%\x3d author.headline || "" %\x3e\x3c/div\x3e\x3c/div\x3e\x3c% } else { %\x3e\x3ca class\x3d"zm-list-avatar-link" href\x3d"javascript:;"\x3e\x3cimg class\x3d"zm-list-avatar-medium" src\x3d"http://img.zhihu.dev:4080/66/6b/666b0abfc_m.jpg"/\x3e\x3c/a\x3e\x3cdiv class\x3d"zm-list-content-medium"\x3e\x3ch2 class\x3d"zm-list-content-title"\x3e匿名用户\x3c/h2\x3e\x3c/div\x3e\x3c% } %\x3e';
z.e.zo=function(){this.eB=new vN(this.pa,this.Gb);this.eB.init();var a=z.I("js-sidebar-author-info");a&&(new OM(a)).init()};z.e.Pz=function(a){a=a.target;if(a instanceof bO)switch(a.Cv){case "collap":z.V.add(a.m(),"zm-item-collapsed");break;case "cancel_collap":z.V.remove(a.m(),"zm-item-collapsed");break;case "set_delete":case "cancel_delete":wO(this),window.location.reload()}};z.ja(xO,z.Q);xO.prototype.C=function(){z.Q.prototype.C.call(this);this.vb=(0,window.$)(this.m());this.Cq=this.vb.find(".js-pager");this.$a=this.vb.find(".js-list");this.MK=this.vb.find(".js-hidden-list");this.Cx=(this.wJ=!!this.vb.closest(".zu-main-sidebar").length)?"zg-follow":"zg-btn-follow";this.OV=this.wJ?"zg-unfollow":"zg-btn-unfollow";yO(this);BO(this)};var CO="follow_topic",DO="unfollow_topic",zO=6;z.ja(EO,z.Q);z.e=EO.prototype;z.e.init=function(){this.w((0,window.$)(".js-topic-feed-page")[0])};
z.e.C=function(){z.Q.prototype.C.call(this);this.vb=(0,window.$)(this.m());this.DQ=!this.vb.find(GO).length;this.Fh=this.vb.find(".js-topic-cat-main");this.Zm=this.vb.find(".js-topic-title");this.zq=this.vb.find(".js-feed-switcher");var a=(0,window.$)(".topic-recommend");if(a.length){var b=new xO;b.w(a[0]);this.o().g(b,CO,this.aP).g(b,DO,this.JP)}this.$a=this.vb.find(".zh-general-list");this.$a.length&&PO(this);FO(this);JO(this);this.Mj()};
z.e.TF=function(a){var b=(0,window.decodeURIComponent)(window.location.hash.slice(1)),c=this.Fh.find(GO),b=OO(c,b);!b.length&&a.data?(b=c.eq(0),this.vb.find(GO+"."+EP).removeClass(EP),b.addClass(EP),this.Zm.show(),this.UC(),window.location.hash=""):b.length&&(a=b.data("id"),this.$a.hide(),this.Zm.hide(),c=b,this.vb.find(GO+"."+EP).removeClass(EP),c.addClass(EP),c=this.zq.find("a"),c.removeClass(KO),c.eq(0).addClass(KO),LO(this,a),QO(this,a,b))};
z.e.aP=function(a){MO(this,1);a=a.data;this.Fh.find(".zm-topic-cat-more").length||this.Fh.append(IO(this,a))};z.e.JP=function(a){MO(this,-1);this.Fh.find('li[data-id\x3d"'+a.data.id+'"]').remove()};z.e.UC=function(){if(!this.$a.show().children().length)return this.$a.html('\x3cp class\x3d"zg-gray-normal" style\x3d"text-align:center;line-height:4;"\x3e该话题暂无动态\x3c/p\x3e')};
z.e.Mj=function(){function a(a,c){var d={action:a,category:"topic"};c&&(d.attributes=c);z.wi(d)}this.vb.on("click",".js-topic-cat-main .zm-topic-cat-item",function(b){a("click_topic",{topic_id:(0,window.$)(b.currentTarget).data("id")})}).on("click",".topic-recommend .zg-follow",function(){a("click_follow_topic")}).on("click",".topic-recommend .js-pager",function(){a("click_change_topics")}).on("click",".js-topic-more a",function(){a("click_expand")}).on("click",".js-topic-all a",function(){a("click_read_more")})};
var EP="current",KO="current",GO=".zm-topic-cat-item",HO=100,RO='\x3cli class\x3d"zm-topic-cat-item" data-id\x3d"\x3c%\x3d id %\x3e" data-href\x3d"/topic/\x3c%\x3d url_token %\x3e"\x3e\x3ca href\x3d"#\x3c%\x3d name %\x3e"\x3e\x3c%\x3d name %\x3e\x3c/a\x3e\x3c/li\x3e';z.v(SO,z.Q);SO.prototype.init=function(){z.CG.K(this);this.w(window.document.body)};SO.prototype.C=function(){SO.v.C.call(this);this.Jy("zh-question-followers-list-wrap")};SO.prototype.Jy=function(a){if(a=z.I(a)){var b=new z.zl;this.K(b);b.use("locationSource");b.w(a)}};z.v(TO,z.Q);TO.prototype.init=function(){z.CG.K(this);this.w(window.document.body);this.Ss();VO(this);WO(this);UO()};
TO.prototype.Ss=function(){function a(a){if((0,window.$)(a).hasClass("article-item"))return new TO.prototype.$m;var b=new z.Q;(0,window.$)(".answer-item",a).each(function(){var a=new z.mB.prototype.Rk;a.dm="actions";a.Hk="zm-votebar";a.Pn="z-icon-fold";a.Yp="sprite-global-icon-fold-white";b.K(a);a.w(this)});return b}var b=this;(0,window.$)("[data-paging]").each(function(){var c=new z.zl({use:["dataPagingSource"]});c.use("childConstructor",{factory:a});var d=(0,window.$)(this).data("navigable");d&&
c.use("shortcut",d);b.K(c);c.w(this)})};TO.prototype.$m=function(){z.JF.call(this);this.pj="entry-expaneded";this.dm="actions";this.Hk="zm-votebar";this.Pn="z-icon-fold";this.Yp="sprite-global-icon-fold-white"};z.v(TO.prototype.$m,z.JF);
TO.prototype.$m.prototype.Ao=function(){var a=new z.jB({ur:"post-content",yB:"script.content"});this.K(a);a.w(this.h);this.g("expandRequest",(0,z.q)(this.expand,this));this.g("expand",function(b){b.target===b.currentTarget&&a.expand()});this.g("collapse",function(b){b.target===b.currentTarget&&a.collapse()})};
TO.prototype.$m.prototype.rG=function(){var a,b,c=(0,window.$)("."+this.Hk,this.m())[0];c&&(a=new z.mE(this.zb,this.entryType),this.K(a),z.Bc(this,a),a.w(c),(c=(0,window.$)(".js-mobi-vote",this.m())[0])&&(new z.dF(a)).w(c));if(c=(0,window.$)(".zm-item-vote-info",this.m())[0])b=new z.qE(this.zb,this.entryType),this.K(b),z.Bc(this,b),b.w(c);a&&b&&this.o().g(a,"change",function(){z.tE(b)}).g(b,"change",function(){(0,window.$)("[data-bind-votecount]",this.m()).text(b.hb())})};
TO.prototype.$m.prototype.sG=z.p;var fP=(0,window.$)("#is-topstory").length?"topstory2":"homefeed",YO=z.A&&!z.D(9),aP={ac:"actioncard",q:"question",a:"answer",p:"article",c:"column",r:"roundtable"},cP={question:"question",answer:"question",article:"column",column:"column",roundtable:"roundtable"},dP={question:"question",answer:"question",article:"article",column:"column",roundtable:"roundtable"};XO.prototype.Rb=function(){this.tC=(0,window.$)('meta[itemprop\x3d"ZReactor"]',this.Eh);this.tC.length&&($O(this),this.hQ())};
XO.prototype.wT=function(){var a=[],b=z.$o(550,function(){a.length&&(ZO(a),a=[])});return function(c){a.push(c);b()}}();
XO.prototype.hQ=z.Kj(function(){z.E(z.X,"click_feed_fresh",function(a){ZO({mid:z.qm.ga_vars.user_hash,object_type:"btn",object_id:2,object_meta:{load_items:a.data.count},action_type:"click",context:fP,others:"",time:(0,z.G)()})});z.E(z.X,"topstory_feed_more",function(){ZO({mid:z.qm.ga_vars.user_hash,object_type:"btn",object_id:1,object_meta:{next:(0,window.$)("#js-home-feed-list .feed-item").length+1},action_type:"click",context:fP,others:"",time:(0,z.G)()})})});z.v(gP,z.aC);gP.prototype.hk=function(a){a&&!a.r&&(a=a.msg,a.length?(z.P(this.Nd,0<a.length),this.offset+=a.length,this.Vq(a),z.bC(this,!1),z.eC(this)):this.Ok.hide())};var FP={ROUNDTABLE_ADD_RELATED:"roundtable",ARTICLE_VOTE_UP:"post_vote",ARTICLE_CREATE:"post_create",RECOMMENDED:"feed_recommended",QUESTION_FOLLOW:"feed_question_follow",QUESTION_CREATE:"feed_question",ANSWER_VOTE_UP:"feed_answer_vote",ANSWER_CREATE:"feed_answer_answer"};
gP.prototype.HP=function(a){var b=a.currentTarget.h.getAttribute("data-feedtype"),b=FP[b];"comment"===a.namespace&&b&&a.Ac.fill("category","feed").fill("label",b)};gP.prototype.ep=function(a){var b=z.LF(a);this.K(b);this.o().g(b,"click!",this.HP);b.w(a);new XO(b);return b};gP.prototype.xI=function(a){return{params:a,method:"next"}};z.ja(hP,z.Q);hP.prototype.C=function(){z.Q.prototype.C.call(this);this.Qr=this.m();this.Bd=(0,window.$)(this.Qr);iP(this);this.Xm=(0,window.$)("#zh-main-feed-fresh-button");this.Xm.length&&(this.Xm.click(window.$.proxy(this.RT,this)),this.MQ?this.o().g(z.X,"topstory2",this.AH):this.o().g(z.X,"homefeed",this.AH));kP(this);lP(this)};hP.prototype.AH=function(a){if(a=(0,window.parseInt)(a.zf,10))this.hm+=a,this.Xm.text((99<this.hm?"99+":this.hm)+" 条新动态").show()};
hP.prototype.RT=function(){this.Xm.text("加载中…");var a=this.hm,b=this;this.yt.offset=a;this.yt.Ei="live";z.dC(this.yt,!0,null,function(c){b.Xm.hide();b.hm=0;if(c&&c.msg.length){b.lv||(b.lv=(0,window.$)('\x3cdiv class\x3d"feed-item-hook feed-divider"\x3e\x3cspan\x3e上次你看到这里\x3c/span\x3e\x3c/div\x3e'));var d=(0,window.$)("."+b.XE,b.Bd).eq(0);d.length&&3<=a?b.lv.insertBefore(d):b.lv.remove();b.yt.Vq(c.msg,"prepend")}})};z.v(mP,z.Rj);mP.prototype.init=function(){var a=z.I("home-suggest-block");a&&(this.h=a,a=z.I("home-suggest-close-button"),this.o().Aa(a,"click",function(){(new z.Z(!0)).ajax("/option","key\x3dno_show_lookup\x26value\x3d1");z.P(this.h,!1)}),a=z.I("home-suggest-refresh-button"),this.o().g(a,"click",this.vS),this.pt=z.I("home-suggest-list"),pP(this))};mP.prototype.vS=function(){nP(this);return!0};
mP.prototype.YR=function(a){a.r||((a=a.msg)&&z.na(a)&&a.length?(this.uy=[],this.qE=a,nP(this)):this.pt.innerHTML="")};z.la(qP);z.v(tP,z.Q);tP.prototype.init=function(){z.CG.K(this);this.w(window.document.body)};tP.prototype.C=function(){tP.v.C.call(this);z.Or(z.p,{Et:!0})();var a=z.I("js-home-feed-list");if(a){var b=new hP;this.K(b);b.w(a)}z.I("home-settings-page-wrap")&&(a=z.I("zh-topic-block-editor"))&&(new z.tt(z.km)).w(a);(new mP).init();uP();a=qP.aa();rP(a)};z.v(vP,z.Q);vP.prototype.init=function(){z.CG.K(this);this.w(window.document.body)};vP.prototype.C=function(){vP.v.C.call(this);var a=(0,window.$)("#zh-following-question-item-list").children(".zh-general-list");if(a.length){var b=new z.zl;this.K(b);b.use("nodeSource");b.w(a.get(0))}};z.v(wP,z.Q);wP.prototype.init=function(){z.CG.K(this);this.w(window.document.body)};wP.prototype.C=function(){wP.v.C.call(this);xP(this);this.Iy();zP(this);AP();this.o().g(this,"click!",function(a){"comment"===a.namespace&&a.Ac.fill("category",this.hh).fill("label",this.WN)})};
wP.prototype.Iy=function(){var a=1,b=(0,window.$)("ul.hot-favlists"),c=null;(0,window.$)("#js-hot-fav-switch").click(function(){c&&"pending"===c.state()||(a=5<=a?1:a+1,c=lN(a).done(function(a){b.html(a)}))});b.on("click",".content \x3e a",function(){var a=(0,window.$)(this).closest("li").index()+1;z.wi({category:"collection",action:"visit_collection",label:"explore_sidebar_trending_collections_collection_name",value:a})})};z.v(yP,z.zl);
yP.prototype.C=function(){yP.v.C.call(this);this.use("childConstructor",{Uh:z.FF})};z.Fa("ZH.entryQuestionFollowersPage",function(){(new SO).init()});z.Fa("ZH.entrySQ",function(){(new cO).init()});z.Fa("ZH.entrySA",function(){(new sO).init()});z.Fa("ZH.entryL",function(){(new oN).init()});z.Fa("ZH.entryT",function(){(new SM).init()});z.Fa("ZH.entrySearch",function(){(new TO).init()});z.Fa("ZH.entryPM",function(){(new LM).init()});z.Fa("ZH.entryPMDetail",function(){(new HM).init()});z.Fa("ZH.entryTopicFeed",function(){(new EO).init()});z.Fa("ZH.entryHome",function(){(new tP).init()});
z.Fa("ZH.entryQuestionFollowing",function(){(new vP).init()});z.Fa("ZH.entryExplore",function(){(new wP).init()});z.kg("page-main");}).call(this, __z_z__);
//# sourceURL=/static/revved/-/js/closure/page-main.833095c3.js